src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_InvestigationCorrectionAction.cls
global class EEC_InvestigationCorrectionAction implements Database.Batchable <sObject>{
	
	String caQuery = '';
	
	global EEC_InvestigationCorrectionAction(String query)
    {
        this.caQuery =  query;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(caQuery);
    } 
     
    global void execute(Database.BatchableContext BC, List <Investigation__c> investList)
    {
    	List<Task> visitTaks = new List<Task>();
    	Set<Id> investSet = new Set<Id>();
    	
    	for(Investigation__c invest : investList){
    		if(invest.Non_Compliant_Item__r != null && invest.Non_Compliant_Item__r.size() > 0){
	    		Task tsk = new Task();
	    		tsk.WhatId = invest.Id;
	    		tsk.OwnerId = invest.Provider_No__r.OwnerId;
	    		tsk.Subject = 'Corrective Action Not Received on Deadline';
	    		tsk.ActivityDate = Date.today().addDays(1);
	    		tsk.Status = 'Not Started';
	    		tsk.Priority = 'High';
	    		visitTaks.add(tsk);
    		}
    	}
    	
    	Database.insert(visitTaks);
    }
    
    global void finish(Database.BatchableContext BC)
    {
		
    }
    
}

//feedback requested = true