src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Restraint_Report__c.object
<CustomObject>
    <description>For R&amp;P, this object is used to capture DYS and Other types of Restraints. There will be a look up relationship from Restraint Report Object to Provider Object.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <description>Look up relationship from Restraint Report to Provider</description>
        <inlineHelpText>Look up relationship from Restraint Report to Provider</inlineHelpText>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Restraint Reports</relationshipLabel>
        <relationshipName>Restraint_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Restraint Report</label>
    <nameField>
        <displayFormat>RR-{00000}</displayFormat>
        <label>Report ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restraint Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_RestraintReportTest.cls
@IsTest public class EEC_RestraintReportTest {
    public static void testEEC_RestraintReportTest () {
        RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
        Account accnt = [select id from Account where RecordtypeID = :r.Id limit 1];  
        Contact con = [select id from Contact where AccountId = :accnt.id limit 1 ];
        Restraint_Report__c restraintReport = [SELECT Id 
									FROM Restraint_Report__c WHERE Provider__c = '0011100000vwa1WAAQ' limit 1];

        
         EEC_RestraintReport p1 = new EEC_RestraintReport();
		 p1.getRestraintReport(string.valueOf(accnt.id));
		 p1.getRestraintReportByID(restraintReport.id);
    }
    
	@isTest  static  void save() {
        City__c c = EEC_TestUtil.mockCity();
        Account a = EEC_TestUtil.mockProvider(c);
        ApexPages.currentPage().getParameters().put('accountId',a.Id);
    	EEC_RestraintReport p1 = new EEC_RestraintReport();
        User user = [SELECT ContactId FROM User WHERE Id =: userinfo.getuserid()];
    	p1.getRestraintReport(string.valueOf('0011100000vwa1WAAQ'));
		p1.getRestraintReportByID(string.valueOf('0011100000vwa1WAAQ'));
    	p1.save();
    }
}