src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <formula>Account.Provider_Email__c</formula>
        <label>Provider Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendCaseTriageEmail__c</fullName>
        <description>Flag to indicate that a case triage email should be sent.</description>
        <label>SendCaseTriageEmail</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TriggerTriageEscalationApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that will trigger an escalation in approvals for In Triage to Escalated for the Case object.</description>
        <label>TriggerTriageEscalationApproval</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Announced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Announced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <description>Copies the email id from the Provider record so it can be used as a Recipient in workflows on the Investigation object</description>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_TestCaseTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EEC_TestCaseTrigger {

    /*static testMethod void myUnitTest() {
        Account mockProvider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
    	Investigation__c i = EEC_TestUtil.mockInvestigation(mockProvider);
        Case c = EEC_TestUtil.mockCase(mockProvider, EEC_TestUtil.mockContact(), i);
        c.SendCaseTriageEmail__c = 'Recalled';
        c.TriggerTriageEscalationApproval__C = true;
        update c;
        c.SendCaseTriageEmail__c = 'Approved';
        update c;
        c.SendCaseTriageEmail__c = 'Rejected';
        update c;
    }*/

    static testMethod void testCaseTriggerHandlerEmail() {
        Test.startTest();
        EEC_CaseTriggerHandler.sendIEmail('test@test.com', 'Test', UserInfo.getUserId(), 'TestCaseEmail', 'investId', 'TestSubject', 'AccountName');
        Test.stopTest();
    }

    static testMethod void testEventTrigger() {
        RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
        Account pAccount = new Account(
          name='TestProvider1',
          RecordTypeId=r.Id,
          Provider_Email__c='test@test.com',
          Provider_Address_1__c='123 Test St.',
          Provider_City__c=EEC_TestUtil.mockCity().Id,
          Provider_Zip_Code__c='B3H0A2');
        insert pAccount;
        // Use a visit obj.

        //Inspection_Item__c item = EEC_TestUtil.mockInspectionItem(EEC_TestUtil.mockInspection(pAccount), EEC_TestUtil.mockStdInspectionItem(), 'Test', true, 'Test');
        Inspection__c item = EEC_TestUtil.mockInspection(pAccount);
        System.debug('*****Item Id: ' + item.Id);

        Event event = new Event(
            DurationInMinutes = 14400,
            ActivityDateTime = DateTime.now(),
            WhatId = item.Id,
            EndDateTime = DateTime.now().addDays(10)
        );
        insert event;
        event.Description = 'Testing!';
        update event;
    }
    static testMethod void testUpdateEventTrigger() {
        Inspection__c[] item = [SELECT ID, Name,Announced__c FROM Inspection__c LIMIT 1];
		if (item.size() > 0)
        	item[0].Announced__c = true;
        update item;
    }
}