src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Household_Member__c.object
<CustomObject>
    <fields>
        <fullName>Age_At_Submission__c</fullName>
        <formula>FLOOR((IF(ISBLANK( Licensing_Transactions__r.Submission_Date__c ), TODAY(), Licensing_Transactions__r.Submission_Date__c) -  Date_of_Birth__c )/365.2425)</formula>
        <label>Age At Submission</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BRC_Consent_Status__c</fullName>
        <inlineHelpText>Status of the electronic version of the document (DocuSign)</inlineHelpText>
        <label>BRC Consent Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BRC_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Licensing Transaction = Upgrade / Change of Address / Change of Household members and  Age at submission &gt;= 15 Then check the previous transaction (based on submission date)  on this provider among FCC New License / FCC Renewal / FCC License Upgrade / Change of Address / FCC Change of Household then check on that transaction if a household member exists with same first name / last name / birth date. If yes and BRC Required of that record = TRUE, then set  flag to FALSE else set flag to TRUE</description>
        <inlineHelpText>Is checked if a BRC was required at submission for this household member.</inlineHelpText>
        <label>BRC Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Licensing_Transactions__c</fullName>
        <label>Licensing Transactions</label>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Household Members and Regular Persons on Premise</relationshipLabel>
        <relationshipName>Household_Member</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Household Members and Regular Persons on Premise</relationshipLabel>
        <relationshipName>Household_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Household Member</label>
    <nameField>
        <displayFormat>HM-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household Member</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>Change_of_Address</fullName>
        <active>true</active>
        <label>Change of Address</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_Change_of_Household</fullName>
        <active>true</active>
        <label>FCC Change of Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_Change_of_Name</fullName>
        <active>true</active>
        <label>FCC Change of Name</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_License_Upgrade</fullName>
        <active>true</active>
        <label>FCC License Upgrade</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_New_License</fullName>
        <active>true</active>
        <label>FCC New License</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_Renewal</fullName>
        <active>true</active>
        <label>FCC Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_LicenseTransactionTriggerHandler.cls
public with sharing class EEC_LicenseTransactionTriggerHandler {
    public static boolean alreadyRan = false;
    List<Licensing_Transaction__c> newList;
    Map<Id,Licensing_Transaction__c> newMap;
    Map<Id,Household_Member__c> hhMAP;
    Map<Id,Account> providerMap;
    Map<String,ID> strHHMap;
    //Map<Id,ID> providerLTMap;
    Map<Id,Set<String>> ltHHMap;
    public EEC_LicenseTransactionTriggerHandler(List<Licensing_Transaction__c> newLTList){
        this.newList = newLTList;
    }
    
    public static boolean checkRecursive(){
        if(!alreadyRan){
            alreadyRan=true;
            return false;
        }else{
            return true;
        }
    }
    
    public void bulkAfter(){
        Set<Id> accountSet = new Set<Id>();
        Map<Id,Licensing_Transaction__c> newLTMap = new Map<Id,Licensing_Transaction__c>();
        newMap = new Map<Id,Licensing_Transaction__c>();
        ltHHMap = new Map<Id,Set<String>>();
        strHHMap = new Map<String, Id>();
        //providerLTMap = new Map<Id,Id>();
        
        for(Licensing_Transaction__c lt : newList){
            System.debug('*********** -- '+lt.Status__c);
            if(String.isNotBlank(lt.Status__c) && lt.Status__c == 'Submitted' && lt.RecordType.DeveloperName != 'FCC_Change_of_Name'){
                accountSet.add(lt.provider__c);
                newLTMap.put(lt.Id,lt);
            }
        }
        if(newLTMap != null && newLTMap.size() > 0){
            providerMap = new Map<Id,Account>([select Id, RecordType.DeveloperName from Account where Id in :accountSet]);
            newMap = new Map<Id,Licensing_Transaction__c>([select Id,RecordType.DeveloperName, Provider__c,(select Id,BRC_Required__c,First_Name__c,Last_Name__c,Date_of_Birth__c,Age_At_Submission__c,BRC_Consent_Status__c from Household_Member__r where Age_At_Submission__c >= 15) 
                                                           from Licensing_Transaction__c where Id in :newLTMap.KeySet()]);
            hhMAP = new Map<Id,Household_Member__c>([select Id,First_Name__c,Last_Name__c,Date_of_Birth__c,Provider__c,BRC_Consent_Status__c,Age_At_Submission__c from Household_Member__c where Provider__c = :accountSet 
                                                   and  Licensing_Transactions__c not in :newLTMap.KeySet()]);
            
            if(hhMAP != null){                                     
                for(Household_Member__c hh : hhMAP.Values()){
                    if(ltHHMap.containsKey(hh.Provider__c)){
                        ltHHMap.get(hh.Provider__c).add(hh.First_Name__c+'-'+hh.Last_Name__c+'-'+hh.Date_of_Birth__c);
                    }
                    else{
                        ltHHMap.put(hh.Provider__c,new Set<String>{hh.First_Name__c+'-'+hh.Last_Name__c+'-'+hh.Date_of_Birth__c});
                    }
                    strHHMap.put(hh.First_Name__c+'-'+hh.Last_Name__c+'-'+hh.Date_of_Birth__c,hh.Id);
                }
            }
            
            /*if(providerLTMap != null && providerLTMap.size() > 0){
                for(Household_Member__c hm :[select Id,Name,First_Name__c,First_Name__c,First_Name__c,BRC_Required__c,Licensing_Transactions__c from Household_Member__c where Licensing_Transactions__c in :providerLTMap.Values() and BRC_Required__c = true]){
                    if(ltHHMap.containsKey(hm.Licensing_Transactions__c)){
                        ltHHMap.get(hm.Licensing_Transactions__c).add(hm.First_Name__c+'-'+hm.Last_Name__c+'-'+hm.Date_of_Birth__c);
                    }
                    else{
                        ltHHMap.put(hm.Licensing_Transactions__c,new Set<String>{hm.First_Name__c+'-'+hm.Last_Name__c+'-'+hm.Date_of_Birth__c});
                    }
                }
            }*/
           
        }
        
    }
    
    public void updateHouseHoldMembers(){
        if(newMap != null && newMap.size() > 0){
            Account provider;
            Id tLTId;
            Set<String> tLTSet;
            List<Household_Member__c> hmList = new List<Household_Member__c>();
            String tStr = '';
            Boolean isBRCSet = false;
            
            for(Licensing_Transaction__c lt : newMap.values()){
                provider = providerMap.get(lt.Provider__c);
                if(provider.RecordType.DeveloperName == 'FCC'){
                    if((lt.RecordType.DeveloperName == 'FCC_New_License' || lt.RecordType.DeveloperName == 'FCC_Renewal')){
                        if(lt.Household_Member__r != null && lt.Household_Member__r.size() > 0){
                            for(Household_Member__c hm : lt.Household_Member__r){
                                hm.BRC_Required__c = true;
                                hmList.add(hm);
                            }
                        }
                    }
                    else if(lt.RecordType.DeveloperName == 'FCC_License_Upgrade' || lt.RecordType.DeveloperName == 'Change_of_Address'|| lt.RecordType.DeveloperName == 'FCC_Change_of_Household'){
                        Household_Member__c phm;
                        if(ltHHMap != null && ltHHMap.size()>0){
                            tLTSet = ltHHMap.get(lt.Provider__c);
                        }
                        for(Household_Member__c hm : lt.Household_Member__r){
                            isBRCSet = false;
                            if(tLTSet != null && tLTSet.size()>0){
                                tStr = hm.First_Name__c+'-'+hm.Last_Name__c+'-'+hm.Date_of_Birth__c;
                                Id hhId = strHHMap.get(tStr);
                                if(String.isNotBlank(hhId)){
                                    phm = hhMAP.get(hhId);
                                }
                                //System.debug('********** 3 -- '+ tLTSet + ' -- '+tStr + ' -- '+phm.Age_At_Submission__c + ' -- '+phm.BRC_Consent_Status__c);
                                if(tLTSet.contains(tStr) && phm != null && (/*phm.Age_At_Submission__c < 15 ||*/ (String.isNotBlank(phm.BRC_Consent_Status__c) && phm.BRC_Consent_Status__c == 'Completed'))){
                                    hm.BRC_Required__c = false;
                                    isBRCSet = true;
                                    hmList.add(hm);
                                }
                            }
                            if(!isBRCSet){
                                if(hm.Age_At_Submission__c >= 15 ){
                                    hm.BRC_Required__c = true;
                                    hmList.add(hm);
                                }
                            }
                        }
                    }
                }
            }
            System.debug('hmList' + hmList);
            if(hmList != null && hmList.size() > 0){
                update hmList;
            }
        }
    }
}