src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Foster Parent</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foster Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>New_First_Name__c</fullName>
        <inlineHelpText>New first name submitted by provider</inlineHelpText>
        <label>New First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Last_Name__c</fullName>
        <inlineHelpText>New last name submitted by provider</inlineHelpText>
        <label>New Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_First_Name__c</fullName>
        <inlineHelpText>First Name of the applicant prior to change</inlineHelpText>
        <label>Prior First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prior_Last_Name__c</fullName>
        <inlineHelpText>Last Name of the Provider prior submitted change</inlineHelpText>
        <label>Prior Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_New_Provider_Name__c</fullName>
        <inlineHelpText>Once this transaction is processed, the provider name will be changed to this value</inlineHelpText>
        <label>Proposed New Provider Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Provider Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Change_of_Name</fullName>
        <active>true</active>
        <label>FCC Change of Name</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_ContactTriggerHandler.cls
public with sharing class EEC_ContactTriggerHandler {
    
    public List<Contact> ct {get; set;}
    public List<Contact> newC {get; set;}
    public Map<Id,Contact> oldC {get; set;}
    private static list<case> caselist = new list<case> ();
    //private string contactid;
        
	public EEC_ContactTriggerHandler(List<Contact> newListC, Map<Id,Contact> oldMapC){
        this.newC = newListC;
        this.oldC = oldMapC;
	}
    
    public void createTransaction(){
        User portalUser = [SELECT Id, IsPortalEnabled, UserType  FROM USER WHERE Id =: Userinfo.getUserId() LIMIT 1];
        if(portalUser.UserType == 'PowerCustomerSuccess' || portalUser.UserType == 'CustomerSuccess'){
        Id fccRecordTypeId = EEC_RecordTypeUtil.findByName('ACCOUNT.FCC').Id;
        
        for(Contact newContact : newC){
            Contact oldContact = oldC.get(newContact.id);
            
            Account provider = [SELECT Id, Recordtype.Name, RecordTypeId FROM Account 
                                WHERE ID IN (SELECT AccountId FROM user WHERE id = :Userinfo.getUserId()) LIMIT 1];
            
            
            if((oldContact.FirstName != newContact.FirstName || 
               oldContact.LastName != newContact.LastName) && fccRecordTypeId == provider.RecordTypeId &&
              (portalUser.IsPortalEnabled == true || portalUser.UserType == 'PowerCustomerSuccess')){
                  
                Licensing_Transaction__c lt = new Licensing_Transaction__c();
                
                lt.RecordTypeId = EEC_RecordTypeUtil.findByName('Licensing_Transaction__c.FCC_Change_of_Name').Id;
                lt.Prior_First_Name__c = oldContact.FirstName;
                lt.Prior_Last_Name__c = oldContact.LastName;
                lt.New_First_Name__c = newContact.FirstName;
                lt.New_Last_Name__c = newContact.LastName;
                lt.Proposed_New_Provider_Name__c = newContact.FirstName + ' ' + newContact.LastName;
                lt.Provider__c = oldContact.AccountId;
                lt.Status__c = 'Submitted';
                lt.Submission_Date__c = Date.today();
                lt.Submitter__c = Userinfo.getUserId();
                lt.Source__c = 'Provider Portal';
                
                insert lt;
            	}
        	}
        }
    }
   public list<case> contactcaselist(string contactid){
     if(contactid!=null)	
     caselist =[select id,Contactid,Foster_Parent__c from case where contactid =: contactid];
    
     return caselist;
    
    }
    public void AccountMandatory(){
    	 for(contact c : newC){
    	 	system.debug('MMMM'+contactcaselist(c.id).size()+c.id);
         if(contactcaselist(c.id).size()==0 && c.accountid == null)
         
           c.adderror('All Contacts must have either an Associated Case or Provider Name');
       }
    }
}