src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Freeze Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Renewal_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is check by the daily Renewal batch if Expiration Date of the license is in 120 days. When checked, it&apos;ll trigger a workflow that sends emails / reminders</description>
        <label>Start Renewal Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EEC_BatchFCCLicenseRenewalScheduler.cls
global class EEC_BatchFCCLicenseRenewalScheduler implements schedulable {
  
  public void execute (SchedulableContext sc) {
    
   
    EEC_BatchFCCLicenseRenewal fr = new EEC_BatchFCCLicenseRenewal('Select Id,License_Status__c,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                                                               ' and Recordtype.Name = \'Family Child Care\'  ');
    id boccemea = database.executebatch(fr,10);
  }
  
}