src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Investigation_Visits</fullName>
        <active>true</active>
        <description>Visits done in the scope of an investigation, these visits will not generate a specific report as the visit report will be included in the investigation report</description>
        <label>Investigation Visits</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Review_on_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Provider needs to review the item on the portal</inlineHelpText>
        <label>To Review on Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Additional_Inspection_Item</fullName>
        <active>true</active>
        <description>Visit item that is not defined in LEAD Configuration, and most likely will reference a regulation article that needs to be or has been reviewed during the visit</description>
        <label>Non Standard Visit Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <description>Copies the email id from the Provider record so it can be used as a Recipient in workflows on the Investigation object</description>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To_Review_on_Portal__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, the Provider needs to review the item on the portal.</inlineHelpText>
        <label>To Review on Portal</label>
        <type>Checkbox</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Article__c</fullName>
        <description>Regulation article</description>
        <label>Article</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Active__c</fullName>
        <description>Date this regulation must be applied</description>
        <inlineHelpText>Date this regulation must be applied by Provider</inlineHelpText>
        <label>Date Active</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reg_key__c</fullName>
        <description>Regulation key from external system (EECRS)</description>
        <externalId>true</externalId>
        <label>Reg_key</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_TestInspectionItemTrigger.cls
@isTest
public with sharing class EEC_TestInspectionItemTrigger {

    @isTest static void testupdateRequireFeedbacknegative() {
        test.startTest();
        
        User u = EEC_TestUtil.mockUser();        
        System.runAs(u) {
            ID accountid;      
            Integer int1 =0;
            RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
            RecordType r1 = [select Id from RecordType where DeveloperName='Investigation_Visits' and sobjecttype='Inspection__c'];        
            Account pAccount = new Account(
            name='TestProvider1',
            RecordTypeId=r.Id,
            Provider_Email__c='test@test.com',
            Provider_Address_1__c='123 Test St',
            Provider_City__c=EEC_TestUtil.mockCity().Id,
            Provider_Zip_Code__c='B3H0A2');
            insert pAccount;
            Regulation__c reg = new Regulation__c(name='Test Reg',Date_Active__c=Date.today(),Reg_key__c='123456',Article__c='TEST Article',Applicable_To__c='Family Child Care');
            insert reg;
            RecordType aiRType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
            r1 = [select Id from RecordType where DeveloperName='Investigation_Visits' and sobjecttype='Inspection__c'];        
            Inspection__c insp = new Inspection__c(Provider_No__c=pAccount.Id,RecordTypeId=r1.Id,Status__c='Scheduled', Date_of_Visit__c=date.today());
            insert insp;
            Inspection_Item__c iItem = new Inspection_Item__c (Inspection_no__c = insp.Id,Associated_regulation__c=reg.Id,RecordTypeId=aiRType.Id,Inspection_Result__c='Compliant',Date_Implemented__c  = Date.Today(),Correction_Plan__c='Testing 1',observations__c='test',To_Review_on_Portal__c = true);
            insert iItem;
            System.debug('insp record type -->'+insp.RecordTypeId);  
            System.debug('insp id -->'+insp.Id);  
            List<Inspection_Item__c> iItemList = new List<Inspection_Item__c>([select Id,Inspection_No__c,Inspection_No__r.Provider_No__c from Inspection_Item__c where Inspection_no__c = :insp.Id limit 1]);                                   
            System.debug('Inspection_No__c -->' + iItemList[0].Inspection_No__c);  
            Investigation__c i = new Investigation__c(Provider_No__c = IItemList[0].Inspection_No__r.Provider_No__c,Created_on_the_Web__c=true,Require_Portal_Feedback__c=true);   
            insert i;
            i = [select id from Investigation__c where id = :i.id];
            insp.Investigation__c = i.id;
            update insp;
            Inspection__c insp1 = [select id ,Investigation__c from Inspection__c where id = :insp.id limit 1 ];
            System.debug('Test class value of Investigation__c' + insp1.Investigation__c);
            Non_Compliant__c nc = new Non_Compliant__c(Investigation__c = i.Id,Observations__c='Test');        
            insert nc;
            RecordType rType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
            iItemList[0].Inspection_Result__c = 'Non-Compliant';
            iItemList[0].Date_Implemented__c  = Date.Today();
            iItemList[0].Correction_Plan__c = 'Testing222';
            iItemList[0].Inspection_No__c = insp.id; 
            update iItemList;
                   
            
            i = [SELECT Require_Portal_Feedback__c  FROM Investigation__c WHERE ID = :i.Id];
            
            System.assertEquals(true,i.Require_Portal_Feedback__c);
            
            
             

        }
        
        test.stopTest();
    }  
    
    @isTest static void testupdateRequireFeedbackpositive() {
        test.startTest();
        
        User u = EEC_TestUtil.mockUser();        
        System.runAs(u) {
            ID accountid;      
            Integer int1 =0;
            RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
            RecordType r1 = [select Id from RecordType where DeveloperName='Investigation_Visits' and sobjecttype='Inspection__c'];        
            Account pAccount = new Account(
            name='TestProvider1',
            RecordTypeId=r.Id,
            Provider_Email__c='test@test.com',
            Provider_Address_1__c='123 Test St',
            Provider_City__c=EEC_TestUtil.mockCity().Id,
            Provider_Zip_Code__c='B3H0A2');
            insert pAccount;
            Regulation__c reg = new Regulation__c(name='Test Reg',Date_Active__c=Date.today(),Reg_key__c='123456',Article__c='TEST Article',Applicable_To__c='Family Child Care');
            insert reg;
            RecordType aiRType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
            r1 = [select Id from RecordType where DeveloperName='Investigation_Visits' and sobjecttype='Inspection__c'];        
            Inspection__c insp = new Inspection__c(Provider_No__c=pAccount.Id,RecordTypeId=r1.Id,Status__c='Scheduled', Date_of_Visit__c=date.today());
            insert insp;
            Inspection_Item__c iItem = new Inspection_Item__c (Inspection_no__c = insp.Id,Associated_regulation__c=reg.Id,RecordTypeId=aiRType.Id,Inspection_Result__c='Compliant',Date_Implemented__c  = Date.Today(),Correction_Plan__c='Testing 1',observations__c='test',To_Review_on_Portal__c = true);
            insert iItem;
            System.debug('insp record type -->'+insp.RecordTypeId);  
            System.debug('insp id -->'+insp.Id);  
            List<Inspection_Item__c> iItemList = new List<Inspection_Item__c>([select Id,Inspection_No__c,Inspection_No__r.Provider_No__c from Inspection_Item__c where Inspection_no__c = :insp.Id limit 1]);                                   
            System.debug('Inspection_No__c -->' + iItemList[0].Inspection_No__c);  
            Investigation__c i = new Investigation__c(Provider_No__c = IItemList[0].Inspection_No__r.Provider_No__c,Created_on_the_Web__c=true,Require_Portal_Feedback__c=true);   
            insert i;
            i = [select id from Investigation__c where id = :i.id];
            insp.Investigation__c = i.id;
            update insp;
            Inspection__c insp1 = [select id ,Investigation__c from Inspection__c where id = :insp.id limit 1 ];
            System.debug('Test class value of Investigation__c' + insp1.Investigation__c);
            RecordType rType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
            iItemList[0].Inspection_Result__c = 'Non-Compliant';
            iItemList[0].Date_Implemented__c  = Date.Today();
            iItemList[0].Correction_Plan__c = 'Testing222';
            iItemList[0].Inspection_No__c = insp.id; 
            update iItemList;
                   
            
            i = [SELECT Require_Portal_Feedback__c  FROM Investigation__c WHERE ID = :i.Id];
            
            System.assertEquals(false,i.Require_Portal_Feedback__c);
            
            
             

        }
        
        test.stopTest();
    }      
}