src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approver_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver&apos;s Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CaseApproverUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closing_Reasons__c</fullName>
        <label>Closing Reasons</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Foster_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Foster Parent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Name_For_Email_Merge__c</fullName>
        <description>Calculate the provider name depending if it&apos;s licensed or unlicensed. This is used for merging with email.</description>
        <formula>IF( OR(ISNULL(AccountId), ISBLANK(AccountId)),  Unlicensed_Provider_Name__c ,  Account.Name )</formula>
        <label>Provider Name For Email Merge</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SendCaseTriageEmail__c</fullName>
        <description>Flag to indicate that a case triage email should be sent.</description>
        <label>SendCaseTriageEmail</label>
        <picklist>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TriageEscalationApproverEmailList__c</fullName>
        <description>The list of the most recent approvers of  a case triage escalation.</description>
        <label>TriageEscalationApproverEmailList</label>
        <length>1300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Triage_Responsible__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User that will be / is / was in charge of the triage.</inlineHelpText>
        <label>Triage Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TriggerTriageEscalationApproval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that will trigger an escalation in approvals for In Triage to Escalated for the Case object.</description>
        <label>TriggerTriageEscalationApproval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Provider_City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider City</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Provider_Name__c</fullName>
        <description>Name of the provider in case of unlicensed provider</description>
        <label>Provider Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unlicensed_Provider_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider Region</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a valid Licensing Region (currently a subsidy region is selected)</errorMessage>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Approver_Email_Address__c</fullName>
        <description>Email address of the 1st level approver on escalated investigations. Will be used to send email alerts on rejected approvals on triage escalation approval process</description>
        <label>1st Escalation Approver Email Address</label>
        <type>Email</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City_Assignment__c.object
<CustomObject>
    <description>This object links a city with its default region based on the type of Provider</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>City</label>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>City Assignments</relationshipLabel>
        <relationshipName>City_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>City Assignments</relationshipLabel>
        <relationshipName>City_Assignments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>City Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>City Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>City Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Approval_Task_Creation__c</fullName>
        <label>Approval Task Creation</label>
        <picklist>
            <picklistValues>
                <fullName>NonEscalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonEscalated Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escalated_Investigation__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If this field is checked, it means that the investigation has been reviewed by Deputy Commissioner and has most likely been assigned to an Investigator. It will need to go through a full approval process of findings.</inlineHelpText>
        <label>Escalated Investigation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X1st_Escalation_Approver_Email_Address__c</fullName>
        <description>Email address of 1st escalation approver on the case. used as an email field when email alerts have to be sent to 1st escalation owner upon approved or rejected escalated investigations</description>
        <inlineHelpText>Email address of 1st escalation approver on the case. used as an email field when email alerts have to be sent to 1st escalation owner upon approved or rejected escalated investigations</inlineHelpText>
        <label>1st Escalation Approver Email Address</label>
        <type>Email</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City of the region office address</description>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCC_New_Case_Default_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default user new cases will be assigned to for FCC</inlineHelpText>
        <label>FCC - New Case Default Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SGLSA_New_Case_Default_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Default user who will be assigned new cases for SGLSA.</inlineHelpText>
        <label>SGLSA - New Case Default Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_CaseTriggerHandler.cls
public with sharing class EEC_CaseTriggerHandler {
    
    List<Case> newCaseList;
    Map<Id, Case> oldCaseMap;
    Map<Id,city__c> cityMap;
    Map<Id,Account> accountMap;
    Map<Id,Contact> contactMap;
    Map<Id,String> cityRegionMap;
    Map<Id,Investigation__c> investigationMap;
    List<ProcessInstance> processList;
    Map<Id, User> userList;
    Map<Id, UserRole> userRoleList;
    public static boolean FirstRun = true;
    
    EmailTemplate template20 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X20_Case_Escalated_Approved_info_to_initial_requestor'];
    EmailTemplate template21 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X21_Case_Escalated_Rejected_info_to_initial_requestor'];
    EmailTemplate template22 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'X22_Case_Escalated_Request_Recalled'];
    //EmailTemplate template13 = [SELECT Body, Subject FROM EmailTemplate WHERE DeveloperName = 'Test_13_Email_Template'];
    
    public EEC_CaseTriggerHandler(List<Case> newList){
        this.newCaseList = newList;
    }
    
    public EEC_CaseTriggerHandler(List<Case> newList, Map<Id, Case> oldList){
        this.newCaseList = newList;
        this.oldCaseMap = oldList;
        
        if(UserInfo.getUserType() == 'Standard'){
        	setup();
        }
    }
    
    private void setup(){ 
        
        Set<Id> actors = new Set<Id>{};
        Set<Id> roleIds = new Set<Id>{};
        
        processList = new List<ProcessInstance>([
            SELECT Status, Id, TargetObject.Name, TargetObjectID, TargetObject.Type, 
            (SELECT OriginalActorId, ActorId FROM WorkItems ORDER BY CreatedDate DESC LIMIT 1)  
            FROM ProcessInstance
            WHERE TargetObjectId IN :newCaseList AND Status = 'Pending'
            ORDER BY CreatedDate DESC
        ]);
        
        for(Case c : newCaseList){
            if(c.OwnerId!=null){
                actors.add(c.OwnerId);
            }
        }
        
        for(ProcessInstance pi : processList){
            if(pi.WorkItems.size() > 0){
                actors.add(pi.WorkItems[0].OriginalActorId);
                actors.add(pi.WorkItems[0].ActorId);
            }
        }
        
        userList = new Map<Id, User>([
            SELECT ManagerId, UserRoleId, Email, Name
            FROM User
            WHERE Id IN :actors
        ]);
        
        System.debug('ACTORS---->'+actors);
        for(User u : userList.values()){
            roleIds.add(u.UserRoleId);
        }
        
        userRoleList = new Map<Id, UserRole>([
            SELECT Name
            FROM UserRole
            WHERE ID IN :roleIds
        ]); 
    }
    
    private class TestException extends Exception {}
    
    private void sendTriageResultEmail(Case c, Case oldCase){ 
        if((oldCase == null || oldCase.SendCaseTriageEmail__c == null) && c.SendCaseTriageEmail__c != null){  
            EEC_EmailUtil email = new EEC_EmailUtil(); 
     
            if(c.SendCaseTriageEmail__c == 'Approved'){  
                
                // c.SendCaseTriageEmail__c = 'Approved and Email Triggered';
                email.htmlBody = template20.Body
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c)
                    .replace('{!Case.OwnerFullName}', userList.get(c.OwnerId).Name)
                    .replace('{!Case.Id}', c.Id);
                    
                email.subject = template20.Subject
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c);
                    
            }
            else if (c.SendCaseTriageEmail__c == 'Recalled') {
                email.htmlBody = template22.Body
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c)
                    .replace('{!Case.OwnerFullName}', userList.get(c.OwnerId).Name)
                    .replace('{!Case.Id}', c.Id);
                    
                email.subject = template22.Subject
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c);
            }
            else {
                email.htmlBody = template21.Body
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c)
                    .replace('{!Case.OwnerFullName}', userList.get(c.OwnerId).Name)
                    .replace('{!Case.Id}', c.Id);
                    
                email.subject = template21.Subject
                    .replace('{!Case.Provider_Name_For_Email_Merge__c}', c.Provider_Name_For_Email_Merge__c);
            }
            
            email.toAddresses = new List<String>();
            
            if(c.TriageEscalationApproverEmailList__c != null){
                if(c.TriageEscalationApproverEmailList__c.contains(',')) {
                    email.toAddresses.addAll(c.TriageEscalationApproverEmailList__c.split(',')); 
                } else {
                    email.toAddresses.add(c.TriageEscalationApproverEmailList__c); 
                }
            }
            if(userList.get(c.OwnerId).Email != null) 
            	email.toAddresses.add(userList.get(c.OwnerId).Email);
            if(c.X1st_Escalation_Approver_Email_Address__c != null)
            email.toAddresses.add(c.X1st_Escalation_Approver_Email_Address__c);
            
            System.debug(email.toAddresses);
            
            email.whatId = c.Id;
            email.saveAsActivity = false; 
            email.sendEmail();
        }
    }
    
    public void sendApprovalTriageResultEmail(){
        
        List<Investigation__c> updatedInvestigations = new List<Investigation__c>();
        for(Case c : newCaseList) {               
            sendTriageResultEmail(c, oldCaseMap.get(c.Id));
            
            if(c.SendCaseTriageEmail__c == 'Approved'){ 
                if(c.Investigation__c != null && investigationMap.containsKey(c.Investigation__c)){
                   Investigation__c i = investigationMap.get(c.Investigation__c);
                   i.Escalated_Investigation__c = true;
                   //i.Approval_Task_Creation__c = 'Escalated Approved'; 
                   updatedInvestigations.add(i); 
                }
            }
            c.TriageEscalationApproverEmailList__c = null;
            c.SendCaseTriageEmail__c = null; 
        }
        update updatedInvestigations;
    }
    
    public void updateApprovalManager(){ 
        for(Case c : newCaseList){  
        
            Case oldCase = oldCaseMap.get(c.Id);
            
            if(c.TriggerTriageEscalationApproval__C){
                c.Approver_Manager__c = null;
                c.TriggerTriageEscalationApproval__C = false;
                
                for(ProcessInstance pi : processList) {
                
                    if(pi.TargetObjectId == c.Id && pi.WorkItems.size() > 0){
                    
                        User oActor = userList.get(pi.WorkItems[0].OriginalActorId);
                        UserRole oActorRole = userRoleList.get(oActor.UserRoleId);
                        
                        if(c.TriageEscalationApproverEmailList__c == null){
                            c.TriageEscalationApproverEmailList__c = '';
                        }
                        
                        if(c.TriageEscalationApproverEmailList__c != null && c.TriageEscalationApproverEmailList__c != ''){
                            c.TriageEscalationApproverEmailList__c += ',';
                        }
                        c.TriageEscalationApproverEmailList__c += oActor.Email;
                        
                        if(oActor.ManagerId != NULL && (oActorRole == NULL || oActorRole.Name != 'Executive and Directors')){
                            c.Approver_Manager__c = oActor.ManagerId;
                        } 
                        
                        break;
                    }
                }
            }
            
        } 
    }
    
   
    public void bulkBefore(){
        
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> cityIdSet = new Set<Id>();
        Set<Id> investIdSet = new Set<Id>();
        cityRegionMap = new Map<Id,String>();
        Set<Id> contactIdSet = new Set<Id>();
         
        for(Case cse : newCaseList){
            if(String.isNotBlank(cse.AccountId)){// && String.isBlank(cse.Unlicensed_Provider_Name__c)){
                accountIdSet.add(cse.AccountId);
            }
            if(string.isNotBlank(cse.ContactId)){
            	contactIdSet.add(cse.ContactId);
            }
          //  else if(String.isBlank(cse.Unlicensed_Provider_Region__c) && !String.isBlank(cse.Unlicensed_Provider_City__c) && !String.isBlank(cse.Unlicensed_Provider_Name__c)){
            if(String.isBlank(cse.Unlicensed_Provider_Region__c) && !String.isBlank(cse.Unlicensed_Provider_City__c) && !String.isBlank(cse.Unlicensed_Provider_Name__c)){
                cityIdSet.add(cse.Unlicensed_Provider_City__c);
            }
            
            if(String.isNotBlank(cse.Investigation__c)){
                investIdSet.add(cse.Investigation__c);
            }
        }
        Map<Id,String> tempCRMap = new Map<Id,String>();
        String tRegion = '';
        if(cityIdSet != null && cityIdSet.size() > 0){
            for(City_Assignment__c ca : [SELECT id, city__r.name, Applicable_to__c, Region__c 
                                         FROM City_Assignment__c 
                                         WHERE city__c in :cityIdSet]){
                if(cityRegionMap.containsKey(ca.city__c)){
                    if(ca.Applicable_to__c.contains('Family Child Care')){
                        cityRegionMap.put(ca.city__c,ca.Region__c);
                    }
                }
                else{
                    cityRegionMap.put(ca.city__c,ca.Region__c);
                }
            }
        }
        if(accountIdSet != null && accountIdSet.size() > 0){
            accountMap = new Map<Id,Account>([select Id,name,RecordType.name,Region__c,OwnerId from Account where Id in :accountIdSet]);
        }
        
        if(contactIdSet != null && contactIdSet.size() > 0){
            contactMap = new Map<Id,Contact>([select Id,name,AccountId,Account.Name from Contact where Id in :contactIdSet]);
        }
        
        if(investIdSet != null && investIdSet.size() > 0){
            investigationMap = new Map<Id,Investigation__c>([SELECT Id,name,Investigation_Status__c,Assigned_To__c,Assigned_To__r.Email,
                                                            (SELECT Id,createdDate FROM Cases__r order by createddate) 
                                                             FROM Investigation__c WHERE Id in :investIdSet]);
        }
        
    }
    
    /*public void bulkAfter(){
        
        Set<Id> accountIdSet = new Set<Id>();
        Set<Id> investIdSet = new Set<Id>();
         
        for(Case cse : newCaseList){
            if(String.isNotBlank(cse.AccountId)){
                accountIdSet.add(cse.AccountId);
            }
          
            if(String.isNotBlank(cse.Investigation__c)){
                investIdSet.add(cse.Investigation__c);
            }
        }
        Map<Id,String> tempCRMap = new Map<Id,String>();
        
        if(accountIdSet != null && accountIdSet.size() > 0){
            accountMap = new Map<Id,Account>([select Id,name,RecordType.name,Region__c from Account where Id in :accountIdSet]);
        }
        
        if(investIdSet != null && investIdSet.size() > 0){
            investigationMap = new Map<Id,Investigation__c>([select Id,name,Investigation_Status__c,Assigned_To__c,Assigned_To__r.Email,
                                                            (select Id,createdDate from Cases__r order by createddate) 
                                                             from Investigation__c where Id in :investIdSet]);
        } 
        
    }*/
    
    public void updateCaseRegion(){
        Account accnt;
        Region__c region;
        Set<Id> regionIdSet = new Set<Id>();
        Map<Id,Region__c> regionMap;
        
        Map<string,Account> unlicensedProviderMap = new Map<string,Account>();
        for(Account a : [Select Id,Name,Region__c From Account where name like 'Unlicensed Provider -%']){
        	unlicensedProviderMap.put(a.Region__c,a);
        	regionIdSet.add(a.Region__c);
        }
        
        for(Case cse : newCaseList){
        	
          if(String.isBlank(cse.AccountId) && String.isBlank(cse.Unlicensed_Provider_Region__c) && !String.isBlank(cse.Unlicensed_Provider_City__c) && cityRegionMap.containsKey(cse.Unlicensed_Provider_City__c) && (cse.Status == 'New' || cse.Status == 'Not Submitted')){
             
                cse.Unlicensed_Provider_Region__c = cityRegionMap.get(cse.Unlicensed_Provider_City__c);
                  system.debug('*** cse.Unlicensed_Provider_Region__c ***'+cse.Unlicensed_Provider_Region__c);
                
            }
            if(String.isNotBlank(cse.Unlicensed_Provider_Region__c)){
                regionIdSet.add(cse.Unlicensed_Provider_Region__c);
            }
            if(accountMap != null && String.isNotBlank(cse.AccountId) ){
                accnt = accountMap.get(cse.AccountId);
                regionIdSet.add(accnt.Region__c);
            }
            
        }
        
        if(regionIdSet != null && regionIdSet.size() > 0){
            regionMap = new Map<Id,Region__c>([select Id,FCC_New_Case_Default_Assignee__c,SGLSA_New_Case_Default_Assignee__c from Region__c where Id in :regionIdSet]);
        }       
        
        Investigation__c invest;
        EEC_EmailUtil eu;
        List<String> toAddresses;
        
        Id templateId = [select id, name from EmailTemplate where developername = 'X13_Notification_that_a_new_case_has_been_attached_to_investigation'].id;
        //Id templateId = [select id, name from EmailTemplate where developername = 'Test_13_Email_Template'].id;
        //OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address = 'doNotReply@blahblah.com'];
        for(Case cse : newCaseList){
            if(cse.Status == 'New' || cse.Status == 'Not Submitted'){
                if(String.isBlank(cse.AccountId)){
                    system.debug('*** Account is BLANK ***');       
                    if(String.isNotBlank(cse.Unlicensed_Provider_Region__c)){
                        region = regionMap.get(cse.Unlicensed_Provider_Region__c);
                        cse.Triage_Responsible__c = region.FCC_New_Case_Default_Assignee__c;
                        if(String.isNotBlank(cse.ContactId)){
                            Contact con = contactMap.get(cse.ContactId);
                            if(con != null){
                                if(con.AccountId != null){
                                     Account acc = unlicensedProviderMap.get(cse.Unlicensed_Provider_Region__c);
                                     if (acc != null){
                                            cse.AccountId = unlicensedProviderMap.get(cse.Unlicensed_Provider_Region__c).Id;                   
                                            system.debug('*** cse.AccountId ***'+ cse.AccountId);  
                                      } 
                                }
                                else{
                                    cse.AccountId = con.AccountId;
                                }
                            }
                        }       
                    }
                }
                else{
                    //Assign unlicensed Provider (Bucket Provider) on Case
                     if(!String.isBlank(cse.Unlicensed_Provider_Name__c) && !String.isBlank(cse.Unlicensed_Provider_City__c) && cityRegionMap.containsKey(cse.Unlicensed_Provider_City__c)){  	
                            system.debug('******LD'+ cse.AccountId);
                            cse.Unlicensed_Provider_Region__c = cityRegionMap.get(cse.Unlicensed_Provider_City__c);
                            system.debug('******LD REgion ****'+ cse.Unlicensed_Provider_Region__c);
                            
                            region = regionMap.get(cse.Unlicensed_Provider_Region__c);
                            cse.Triage_Responsible__c = region.FCC_New_Case_Default_Assignee__c;
                            Account acc = unlicensedProviderMap.get(cse.Unlicensed_Provider_Region__c);
                            if (acc != null){
                            cse.AccountId = unlicensedProviderMap.get(cse.Unlicensed_Provider_Region__c).Id;
                       
                             system.debug('******LD Unlicensed Provider ****'+ acc);
                            }
                        }
                     else {
                        accnt = accountMap.get(cse.AccountId);
                        system.debug('****Account ***'+accnt);
                        if(String.isNotBlank(accnt.Region__c)){
                            region = regionMap.get(accnt.Region__c);
                            if(accnt.RecordType.name == 'Family Child Care'){
                                cse.Triage_Responsible__c = region.FCC_New_Case_Default_Assignee__c;
                            }
                            else if(accnt.RecordType.name == 'Large Group' || accnt.RecordType.name == 'Small Group' || accnt.RecordType.name == 'Umbrella'){
                                cse.Triage_Responsible__c = region.SGLSA_New_Case_Default_Assignee__c;
                            }
                            else{
                                system.debug('****Account Owner***'+accnt.OwnerId);
                                User[] owner = [SELECT Id,ManagerId FROM User WHERE Id =: accnt.OwnerId LIMIT 1];
                                if(owner.size() > 0)
                                    cse.Triage_Responsible__c = owner[0].ManagerId;
                            }
                        }
                     }
                } // end if
            }
        }       
    }
    
    public void updateCaseStatus(){
    	Investigation__c invest;
        Integer counter = 0;
    	for(Case cse : newCaseList){
    		if(String.isNotBlank(cse.Investigation__c) && cse.Status != 'Escalated'){
                invest = investigationMap.get(cse.Investigation__c);
                if(invest.Cases__r != null && invest.Cases__r.size() > 0 && String.isNotBlank(invest.Assigned_To__c)){
                    if(String.isNotBlank(invest.Investigation_Status__c) && invest.Investigation_Status__c != 'Closed' ){
                        cse.Status = 'Investigation in Progress';
                    }
                    else{
                        cse.Status = 'Closed';
                        cse.Closing_Reasons__c = 'Investigation completed';
                    }
                    
                    if(String.isBlank(cse.ParentId)){
                        Case[] pCase = [SELECT Id FROM Case WHERE ParentId = null AND Investigation__c =: invest.Id AND Id !=: cse.Id LIMIT 1];
                        if(pCase.size() > 0){
                            if(pCase[0].Id != cse.Id){
                                cse.ParentId = pCase[0].Id;
                            }
                        }
                    }
                }
            }
    	}
    }
    
    public void sendCaseEmail(){
        Investigation__c invest;
        EEC_EmailUtil eu;
        List<String> toAddresses;
        Id oldInvest;
        for(Case cse : newCaseList){
        	if(String.isNotBlank(cse.Investigation__c)){
                invest = investigationMap.get(cse.Investigation__c);
                oldInvest = (oldCaseMap == null || String.isBlank(oldCaseMap.get(cse.Id).Investigation__c)) ? null :oldCaseMap.get(cse.Id).Investigation__c;
                if(cse.Investigation__c != oldInvest && invest.Cases__r != null && invest.Cases__r.size() > 0){
                    toAddresses = new List<String>();
                    
                    if(String.isNotBlank(invest.Assigned_To__c)){ 
                        String accntName = '';
                        if(String.isNotBlank(cse.AccountId)){
                            accntName = accountMap.get(cse.AccountId).Name;
                        }
                        else{
                            accntName = cse.Unlicensed_Provider_Name__c;
                        }
                        sendIEmail(invest.Assigned_To__r.Email,invest.name,invest.Assigned_To__c,cse.CaseNumber,cse.Investigation__c,cse.Subject,accntName);
                    }
                }
            }
       }
    }
    
    @future
    public static void sendIEmail(String assignedEmail,String investName,Id assignedTo, String caseName,String investId, String caseSubject, String accntName){
        EEC_EmailUtil eu = new EEC_EmailUtil();
        List<String> toAddresses = new List<String>();
        List<OrgWideEmailAddress> orgList = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = 'EEC LEAD Alert'];
        String emailBOdy = '';
        URL hostURL = URL.getCurrentRequestUrl(); 
        String domain = 'https://' + hostURL.getHost() +'/'+investId;
        toAddresses.add(assignedEmail);
        if(orgList != null){
        	eu.orgWideEmailId = orgList.get(0).Id;
        }
        eu.targetObjectId = assignedTo;
        //eu.whatId = caseId;
        eu.toAddresses = toAddresses;
        caseSubject = String.isBlank(caseSubject)?'':caseSubject;
        eu.Subject = 'Subject Notification that a new case has been attached to investigation';
        //eu.templateId = templateId;
        emailBody = 'Hello\n\nA new case ('+caseName+' - ' + caseSubject + ') has been attached to investigation ' + investName+' associated to provider : '+accntName + ' you are in charge of.\n\n';
        emailBody = emailBody + 'Please review your investigation ('+domain+' ) in Salesforce to get more information on this case.\n\nLEAD System';
        eu.plainTextBody = emailBody;
        eu.sendEmail();
    }
    
}