src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Items_with_Corrective_Actions__c</fullName>
        <label>Number of Items with Corrective Actions</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Inspection_Item__c.Date_Implemented__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_non_compliant_items__c</fullName>
        <description>Provide the number of non-compliant items from an inspection</description>
        <label>Number of Non-Compliant items</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_CorrectionAction.cls
global class EEC_CorrectionAction implements Database.Batchable <sObject>{
	
	String caQuery = '';
	
	global EEC_CorrectionAction(String query)
    {
        this.caQuery =  query;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(caQuery);
    } 
     
    global void execute(Database.BatchableContext BC, List <Inspection__c> visitList)
    {
    	
    	List<Task> visitTaks = new List<Task>();
    	for(Inspection__c visit : visitList){
    		System.debug('*******12 -- '+visit.Number_of_non_compliant_items__c+' -- '+visit.Number_of_Items_with_Corrective_Actions__c);
    		if(visit.Number_of_non_compliant_items__c != visit.Number_of_Items_with_Corrective_Actions__c){
	    		Task tsk = new Task();
	    		tsk.WhatId = visit.Id;
	    		tsk.OwnerId = String.isNotBlank(visit.Inspector_del__c)?visit.Inspector_del__c:visit.Provider_No__r.OwnerId;
	    		tsk.Subject = 'Corrective Action Not Received on Deadline';
	    		tsk.ActivityDate = Date.today().addDays(1);
	    		tsk.Status = 'Not Started';
	    		tsk.Priority = 'High';
	    		visitTaks.add(tsk);
    		}
    	}
    	
    	Database.insert(visitTaks);
    }
    
    global void finish(Database.BatchableContext BC)
    {
		
    }
}