src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Restraint_Report_Automation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restraint Report Automation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Physical_Restraints__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Physical Restraints</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_BatchRestraintReportScheduler.cls
global class EEC_BatchRestraintReportScheduler implements schedulable {
  
  public void execute (SchedulableContext sc) {
    
   
    EEC_BatchRestraintReport rr = new EEC_BatchRestraintReport('Select Id,Restraint_Report_Automation__c from Account  where Use_Physical_Restraints__c = true' +
                                                               ' and Recordtype.Name in (\'Temporary Shelter\' ,\'Group Care\')');
    id boccemea = database.executebatch(rr,10);
  }
  
}