src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>No_of_Days_For_Investigation_Due_Date__c</fullName>
        <inlineHelpText>Number of days that will be used as default to set the investigation due date.</inlineHelpText>
        <label>No. of Days For Investigation Due Date</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Non_Comp_before_longer_visit__c</fullName>
        <inlineHelpText>Max Number of non-compliance in the last 14 months before the system proposed a longer visit tool. For example, if we want to use a longer visit tool if there are 2 or more substantiated citations, the value here should 1 (max 1 before longer visit)</inlineHelpText>
        <label>Number of Non-Comp. before longer visit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portal_Home_Latest_News__c</fullName>
        <description>The latest and up to date news for portal users.</description>
        <label>Portal Home Latest News</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Portal_Home_Useful_Links__c</fullName>
        <description>Useful links for portal users on the home page.</description>
        <label>Portal Home Useful Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Portal_Home_Welcome__c</fullName>
        <description>This is the portal&apos;s home page message.</description>
        <label>Portal Home Welcome</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_PortalLandingControllerTest.cls
@IsTest 
global with sharing class EEC_PortalLandingControllerTest {
    @IsTest(SeeAllData=false)     
     static void testEEC_PortalLandingController () {
       City__c city;  
       //User u;
       Account accnt;
       Contact con;
       User thisUser = [Select Id From User Where Id = :UserInfo.getUserId()];
       
         
       System.runAs(thisUser) {
         city = EEC_TestUtil.mockCity();
         RecordType r = [select Id from RecordType where DeveloperName='FCC' and sobjecttype='Account'];
         accnt = EEC_TestUtil.mockProvider(city);
         con = EEC_TestUtil.mockDirectorContact(accnt);
       }
       
       //Account accnt = [select id from Account where RecordtypeID = :r.Id limit 1];  
       //Contact con = [select id from Contact where AccountId = :accnt.id limit 1 ];
       //EEC_TestUtil.mockDirectorContact(accnt);  
       System.debug('Accnt id ' + accnt.id);
       System.debug('Contact id '+ con.id);
       
       //ApexPages.currentPage().getParameters().put('accountid',accnt.id);    
       
      Account acc = [Select RecordType.Name From Account Where Id = :accnt.Id];
      
       Test.startTest();
       User u = EEC_PortalLandingControllerTest.mockuser(con);
       Lead_Configuration__c config = new Lead_Configuration__c(
         Name = acc.RecordType.Name,
         No_of_Days_For_Investigation_Due_Date__c = 1,
         Number_of_Non_Comp_before_longer_visit__c = 1,
         Portal_Home_Useful_Links__c = 'Links go here',
         Portal_Home_Welcome__c = 'Welcome to the testing home page.',
         Portal_Home_Latest_News__c = 'No news for testers!'  
       );  
       insert config;
       
     system.runas(u){
         EEC_PortalLandingController p1 = new EEC_PortalLandingController();
         p1.actionMethod();
         p1.gotoPersonalPage();
         p1.goToProviderPage();
         p1.goToUmbrellaPage();
         p1.goToSubmitNewTransaction();
         p1.noncomp();
         p1.investigationPage();
         p1.goToSubmitNewIncident();
         System.assertNotEquals(null, p1.getLeadConfiguration());
         System.assertNotEquals(null, p1.getAccount());
         
         PageReference restraintPage = Page.EEC_RestraintReport; 
         restraintPage.getParameters().put('accountId', accnt.Id);
         
         //System.assertEquals(restraintPage.getUrl(), p1.goToSubmitNewRestraint().getUrl());
      }
       
       //System.assertEquals(null, p1.actionMethod());       
    }  
    
    public static User mockUser(Contact cont){
    User u;     
    //City__c city = EEC_TestUtil.mockCity();
    //Account a = EEC_TestUtil.mockProvider(city);
    
    //Contact c = new Contact(LastName = 'Contact Last Name', AccountId = a.id, Role__c = 'Main Contact / Licensee');
    //insert c;    
    
    Profile p = [SELECT ID,Name FROM Profile where name = 'Community Standard User without transactions for EEC' LIMIT 1];
    //UserRole roleId = [Select Id,PortalType, PortalAccountId From UserRole where PortalType ='CustomerPortal' limit 1];  
    //System.debug('-----> UserRole ID: ' + roleId);
    u = new User(
            Email = 'test@test.com',
            LastName =  EEC_TestUtil.generateRandomString(5),
            FirstName = EEC_TestUtil.generateRandomString(5),
            Username =  EEC_TestUtil.generateRandomString(26) + '@test.com',
            Alias = EEC_TestUtil.generateRandomString(5),
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            ProfileID = p.Id,
            //PortalRole = 'Worker',
        	//UserRoleID = roleId.Id,
            ContactId = cont.Id,
        	IsActive = true,
        	CommunityNickname = 'testUser123',
            LanguageLocaleKey = 'en_US'
        );
       insert u;
       return u;
    }
}