src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Freeze Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Deadline__c</fullName>
        <label>Estimated Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Visit__c</fullName>
        <description>Reason of Visit</description>
        <label>Reason of Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_BatchGetVisitCoordinatesTest.cls
@isTest(SeeAllData=true)
private class EEC_BatchGetVisitCoordinatesTest {
	
	@isTest static void test_method_one() {
		Id cityId = (Id)[select id from City__c where Name = 'Boston'].id;
		Account acc1 = new Account();          
		Date cDate =  System.today();  
		acc1.Name = 'Test account 1 ';
		acc1.License_Status__c = 'Licensed';
		acc1.Provider_Status__c = 'Current';
		acc1.Provider_Email__c ='test@incapsulate.com';
		acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
		acc1.Provider_Address_1__c = '50 Milk Street';
		acc1.Provider_City__c = cityId;
		acc1.Provider_Zip_Code__c = '02109';
		acc1.Language__c = 'English';
		acc1.Preferred_Language__c = 'English';

		insert acc1;

		Inspection__c visit = new Inspection__c();
		visit.Provider_No__c = acc1.Id;
		visit.Estimated_Deadline__c = cDate;
		visit.Status__c = 'To be scheduled';
		visit.Type_of_Visit__c = 'Monitoring';
		visit.Address_1__c = acc1.Provider_Address_1__c;
		visit.City__c = cityId;
		visit.Zip_Code__c = acc1.Provider_Zip_Code__c;

		insert visit;

		Test.startTest(); 
			EEC_batchGetVisitCoordinates sfbatchSync = new EEC_batchGetVisitCoordinates();
			ID batchprocessid = Database.executeBatch(sfbatchSync);
		Test.stopTest();
		AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
			                      FROM AsyncApexJob WHERE Id =:batchprocessid];
			  //assert for total number of errors
		System.assertEquals(job.NumberOfErrors, 0);
	}
	
	
}