src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(  Is_Residential__c ,

CONTAINS ( RecordType.Name , &quot;Agency&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Residential__c</fullName>
        <description>Is checked if the provider is a Group Care or Temporary Shelter</description>
        <formula>IF( OR (RecordType.Name = &quot;Group Care&quot;, RecordType.Name = &quot;Temporary Shelter&quot;), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is checked if the provider is a Group Care or Temporary Shelter</inlineHelpText>
        <label>Is Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Need_a_licensing_visit__c</fullName>
        <description>This formula is used to calculate if the Provider needs the creation of an automated visit or not. If yes, the text mention what type of visit is required.</description>
        <formula>IF( TEXT(License_Status__c) = &quot;Licensed&quot;,
/* Renewal visit creation */
IF(First_Issue_Date__c + 365 &lt; TODAY() &amp;&amp; TODAY() &gt;= Renewal_date__c - 125 &amp;&amp; TODAY() &lt;= Renewal_date__c - 120, Next_Renewal_Visit_Reason__c ,
/* Other visit creation */
IF( Record_Type_Name__c = &quot;Family Child Care&quot;,

IF( (First_Issue_Date__c + 305 /* 305 days used as 10 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= First_Issue_Date__c + 310 /* 310 days used as 10 MONTHS +5 DAYS */) || (First_Issue_Date__c + 670 /* 670 days used as 22 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= First_Issue_Date__c + 675 /* 675 days used as 22 MONTHS + 5 DAYS */)||
(License_For_10_Upgrade_Date__c + 150 /* 150 days used as 5 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= License_For_10_Upgrade_Date__c + 155 /* 155 days used as 5 MONTHS + 5 DAYS */)||
(License_For_10_Upgrade_Date__c + 545 /* 545 days used as 18 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= License_For_10_Upgrade_Date__c + 550 /* 550 days used as 18 MONTHS + 5 DAYS */), &quot;Progress&quot;, IF( (LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY() , &quot;Monitoring&quot;, &quot;&quot;)),


IF( Is_GSA__c ,

IF( (First_Issue_Date__c + 180 /* 180 days used as 6 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp;
TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;=First_Issue_Date__c + 185 /* 185 days used as 6 MONTHS + 5 DAYS */), &quot;Provisional License Renewal&quot;,

IF( (LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)
&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY() , IF( Last_Mid_Cycle_Review_Date__c &lt;=TODAY()-1825 /* 1825 days used as 5 YEARS */||(ISBLANK(Last_Mid_Cycle_Review_Date__c) &amp;&amp; NUmber_Monitoring_Visit__c &gt; 1),&quot;Enhanced Monitoring&quot;,&quot;Monitoring&quot;), &quot;&quot;)),


IF( Is_R_P__c ,

IF( (First_Issue_Date__c + 180 /* 180 days used as 6 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp;
TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;=First_Issue_Date__c + 185 /* 185 days used as 6 MONTHS + 5 DAYS */), &quot;Provisional License Renewal&quot;,

IF((LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)
&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY()
,&quot;Monitoring&quot;,&quot;&quot;)

)
,&quot;&quot;))
)),

&quot;&quot;)</formula>
        <label>Need a licensing visit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_2__c</fullName>
        <description>Second line of Provider Address</description>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <inlineHelpText>At creation and if left blank, Address 2 will be populated with Provider address after saving</inlineHelpText>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Deadline__c</fullName>
        <label>Estimated Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Lic_Anniversary_Visit_Estimated_Deadline__c</fullName>
        <inlineHelpText>Number of days used to calculate the visit estimated deadline for visits automatically created by the system for Monitoring Visits / Progress Visits / Mid-Cycle Review Visits / Provisional Visits</inlineHelpText>
        <label>Lic Anniversary Visit Estimated Deadline</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c</fullName>
        <inlineHelpText>Number of days prior to the window start date the system will create a monitoring / mid-cycle / progress visit automatically so that the licensor knows that a visit should be scheduled</inlineHelpText>
        <label>Nb Days Prior to Window to Create Vis</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_BatchProviderVisit.cls
global class EEC_BatchProviderVisit implements Database.Batchable <sObject>{
    String pQuery = '';
    global EEC_BatchProviderVisit(String query)
    {
        this.pQuery =  query;
    }
    global EEC_BatchProviderVisit()
    {
        //Updated query to filter results to only those where need_a_licensing_visit__c field has a value. Qamar Islam
        this.pQuery =  'SELECT Id,Is_Residential__c,Is_R_P__c,Is_GSA__c,Provider_Address_1__c,Provider_Address_2__c,Provider_Zip_Code__c,Config_Record__c,Config_Record__r.Lic_Anniversary_Visit_Estimated_Deadline__c,Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c,Provider_City__r.Name,Need_a_licensing_visit__c,License_Status__c,Renewal_date__c,OwnerId,Provider_Status__c FROM Account WHERE Need_a_licensing_visit__c <> null';
    }
    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator(pQuery);
    }
    global void execute(Database.BatchableContext BC, List <Account> providerList)
    {
        
        List<Inspection__c> providerVisit = new List<Inspection__c>();
        for(Account provider : providerList){
            System.debug('----------> Provider: ' + provider);
            Integer vis = [SELECT Count() FROM Inspection__c WHERE Count_Visit_For_Visit_Creation_Batch__c = true AND Provider_No__c =: provider.Id];
           	//System.debug('Visit Count----->' + vis);
            if(provider.Need_a_licensing_visit__c != null && vis < 1)
            {
                Inspection__c insp = new Inspection__c();
                if(provider.Is_R_P__c){
                    if(provider.Need_a_licensing_visit__c == 'Monitoring')
                        insp.Announcement_Type__c = 'Semi-Announced';
                    else
                        insp.Announcement_Type__c = 'Unannounced';
                    if(provider.Is_Residential__c){
                        insp.RecordTypeId = Schema.SObjectType.Inspection__c.getRecordTypeInfosByName().get('Residential Licensing Visit').getRecordTypeId();
                    }
                    else{
                        insp.RecordTypeId = Schema.SObjectType.Inspection__c.getRecordTypeInfosByName().get('Placement Licensing Visit').getRecordTypeId();
                    }
                }
                else{
                    insp.Announcement_Type__c = 'Unannounced';
                    if(provider.Is_GSA__c)
                        insp.RecordTypeId = Schema.SObjectType.Inspection__c.getRecordTypeInfosByName().get('GSA Licensing Visit').getRecordTypeId();
                    else
                        insp.RecordTypeId = Schema.SObjectType.Inspection__c.getRecordTypeInfosByName().get('FCC Licensing Visit').getRecordTypeId();
                }
                insp.Inspector_del__c = provider.OwnerId; 
                insp.Provider_No__c = provider.Id;
                insp.Address_1__c = provider.Provider_Address_1__c;
                insp.Address_2__c = provider.Provider_Address_2__c;
                insp.City__c = provider.Provider_City__r.Name;
                insp.Zip_Code__c = provider.Provider_Zip_Code__c;
                insp.Status__c = 'To be scheduled';
                insp.Visit_Created_By_Batch__c = true;
                insp.Licensing_Transaction__c = null;
                insp.Type_of_Visit__c = provider.Need_a_licensing_visit__c;
                if(provider.Need_a_licensing_visit__c.containsIgnoreCase('Renewal') ){
                    insp.Estimated_Deadline__c = provider.Renewal_date__c;
                } else {
                    Date pDate = Date.today();
                    insp.Estimated_Deadline__c = pDate.addDays(Integer.valueOf(provider.Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c + provider.Config_Record__r.Lic_Anniversary_Visit_Estimated_Deadline__c));
                }
                
                providerVisit.add(insp);    
            //}
          }
        }
        if(providerVisit <> null && providerVisit.size() > 0)
        	Database.insert(providerVisit);
    }
    global void finish(Database.BatchableContext BC)
    {
        
    }


}