src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(  Is_Residential__c ,

CONTAINS ( RecordType.Name , &quot;Agency&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Visit</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Provider of the associated visit must be the provider of the visit</errorMessage>
            <filterItems>
                <field>$Source.Provider_No__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Provider_No__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Associated Visits (Follow-Ups)</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Category_list__c</fullName>
        <description>Domain(Category) used for list.</description>
        <formula>TEXT( Category_additional__c ) &amp; IF(ISPICKVAL(Category_additional__c,&quot;&quot;) , Category_standard__c , &quot;&quot;)</formula>
        <label>Domain (list)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description_of_inspection__c</fullName>
        <formula>Standard_Inspection_Item__r.Description__c</formula>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_Item_Name_for_list__c</fullName>
        <description>This is used in related list to display the name no matter the record type</description>
        <formula>Inspection_Item_Name__c &amp;  Additional_Inspection_Item_Name__c</formula>
        <label>Visit Item Name for list</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Key_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this visit item is identified as a key indicator = associated to a regulation flagged as high risk</inlineHelpText>
        <label>Key Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Investigation_Type__c</fullName>
        <description>Investigation Type, Due Date and Intervention Type must be filled out when an Investigation is assigned</description>
        <label>Investigation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regulatory Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue Resolved by Licensee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this non compliant item is associated to a high risk regulation</inlineHelpText>
        <label>Key Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_NCInspectionItemsController.cls
public with sharing class EEC_NCInspectionItemsController {

  private final Inspection__c inspectionRecord;

  public String recordTypeName { get; set; }

  public EEC_NCInspectionItemsController(ApexPages.StandardController controller) {
    //this.inspectionRecord = (Inspection__c) controller.getRecord();
    this.inspectionRecord = [
                             SELECT
                             Provider_No__c,
                             Provider_No__r.RecordTypeId,
                             CreatedDate, Date_of_Visit__c,
                             Original_Visit__r.Date_of_Visit__c
                             FROM Inspection__c WHERE Id = :controller.getId()
                            ];
  }

  public List<Inspection_Item__c> getNCInspItemList() {
    List<Inspection_Item__c> iItemList;
    Set<Id> inspectionSet = new Set<Id> ();

    String inspDateQuery = '';
    System.debug('*******1***** ' + inspectionRecord.Provider_No__c);
    String pRecordType = EEC_RecordTypeUtil.findById(inspectionRecord.Provider_No__r.RecordTypeId).DeveloperName;
    DateTime dateHist = (inspectionRecord.Date_of_Visit__c != null) ? inspectionRecord.Date_of_Visit__c : inspectionRecord.CreatedDate;

    if (pRecordType == 'FCC') {
      dateHist = dateHist.addYears(- 6);
    } else {
      dateHist = dateHist.addYears(- 4);
    }

    String whereClause = '';
    if (inspectionRecord.Original_Visit__c != null) {
      if ((inspectionRecord.Date_of_Visit__c != null && inspectionRecord.Original_Visit__r.Date_of_Visit__c != null)) {
        Date tDate = inspectionRecord.Original_Visit__r.Date_of_Visit__c;
        String calenderDate = datetime.newInstance(tDate.year(), tDate.month(), tDate.day()).format('yyyy-MM-dd');
        whereClause = ' and Date_of_Visit__c > ' + calenderDate;
      }
    } else {
      whereClause = ' and Status__c = \'Closed\' and Date_of_Visit__c >= ' + dateHist.format('yyyy-MM-dd') + ' and Date_of_Visit__c < ' + DateTime.now().AddDays(1).format('yyyy-MM-dd');
    }

    String iiQuery = 'select Id from Inspection__c where Provider_No__c != null AND Provider_No__c = \'' + inspectionRecord.Provider_No__c + '\' ' + whereClause;
    System.debug('***********iiQuery** ' + iiQuery);
    List<Inspection__c> inspList = Database.Query(iiQuery);
    // TODO: Switch this to just pull the keys into a map back into the set instead. 
    for (Inspection__c insp : inspList) {
      inspectionSet.add(insp.Id);
    }
    iItemList = [select Id, Inspection_No__c, Inspection_No__r.name, Inspection_No__r.Date_of_Visit__c, Name, Inspection_Item_Name_for_list__c, Category_list__c,
                 Description_of_inspection__c, Correction_Plan__c, Observations__c,Key_Indicator__c from Inspection_Item__c
                 where Inspection_No__c in :inspectionSet AND Inspection_No__c != :inspectionRecord.Id AND Inspection_Result__c = 'Non-Compliant' order by Inspection_No__r.Date_of_Visit__c desc];
    return iItemList;
  }

  public List<Non_Compliant__c> getNonCompliantItemList() {
    String pRecordType = EEC_RecordTypeUtil.findById(inspectionRecord.Provider_No__r.RecordTypeId).DeveloperName;
    Integer numOfYears = 4;

    if (pRecordType == 'FCC') {
      numOfYears = 6;
    }
    Date d1 = Date.today();
    Date d2 = d1.addYears(- numOfYears);
    List<Non_Compliant__c> ncList = new List<Non_Compliant__c>();
    System.debug('----> Date 1: ' + d1);
    System.debug('----> Date 2: ' + d2);  
      
    ncList = [Select Id, Name, CreatedDate, Investigation__r.Name, Correction_Plan__c, 
                                 Investigation__r.Provider_No__r.Is_R_P__c, Investigation__r.Provider_No__r.Is_GSA__c,
                                 Investigation__r.Provider_No__r.Record_Type_Name__c, Observations__c,Key_Indicator__c,
                                 Investigation__r.Investigation_Type__c From Non_Compliant__c Where Investigation__c IN
                                 (Select Id From Investigation__c Where Provider_No__c = :inspectionRecord.Provider_No__c)
                                 AND DAY_ONLY(convertTimezone(CreatedDate)) <= :d1 AND DAY_ONLY(convertTimezone(CreatedDate)) >= :d2 order by CreatedDate desc];
    System.debug('----> ncList: ' + ncList);
    return ncList;
  }

	public List<NCInspectionItemsWrapper> getAllNonCompliantItemsCombined() {
    	List<NCInspectionItemsWrapper> ncCombinedWrapper = new List<NCInspectionItemsWrapper>();
    	List<Inspection_Item__c> inspItems = getNCInspItemList();
    	List<Non_Compliant__c> ncItems = getNonCompliantItemList();
	    for (Inspection_Item__c item : inspItems)
      		ncCombinedWrapper.add(new NCInspectionItemsWrapper(item, null));
	 	for (Non_Compliant__c item : ncItems) 
      		ncCombinedWrapper.add(new NCInspectionItemsWrapper(null, item));
    	ncCombinedWrapper.sort();
    	return ncCombinedWrapper;
  	}

   	public class NCInspectionItemsWrapper implements Comparable {
    	public Inspection_Item__c inspItem{get;set;}
    	public Non_Compliant__c ncItem{get;set;}
    	public Boolean IsInspectionItem{get;set;}
    	public Boolean KeyIndicator{get;set;}
    	public datetime dt{get;set;}
	
    	public Integer compareTo(Object compareTo){
        	NCInspectionItemsWrapper NCWrapCompare = (NCInspectionItemsWrapper)compareTo;
        	if(dt>NCWrapCompare.dt)
                return -1;
           	else if(dt<NCWrapCompare.dt)
                return 1;
            else{
                if(KeyIndicator)
                    return -1;
               	else if(NCWrapCompare.KeyIndicator)
                    return 1;
                else
                	return 0;	
            }
    	}    
		public NCInspectionItemsWrapper(Inspection_Item__c inspItem, Non_Compliant__c ncItem) {
			this.inspItem = inspItem;
      		this.ncItem = ncItem;
      		dt=inspItem!=null?inspItem.Inspection_No__r.Date_of_Visit__c:ncItem.CreatedDate;
      		if(this.inspItem != null) 
     			this.KeyIndicator = inspitem.Key_Indicator__c;
    		else
     			this.KeyIndicator = ncitem.Key_Indicator__c;
    		if(this.inspItem != null)
				this.IsInspectionItem = true;
			else
        		this.IsInspectionItem = false;
    	}
  	}
}