src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Restraint_Method__c</fullName>
        <label>Restraint Method</label>
        <picklist>
            <picklistValues>
                <fullName>ANV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PART</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAPPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonRestraint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Varied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Group_Care</fullName>
        <active>true</active>
        <description>Residential - Group Care</description>
        <label>Group Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_TestProviderTriggerHandler.cls
@isTest
public with sharing class EEC_TestProviderTriggerHandler {

    @isTest static void testUpdateConfigRecordInsert(){
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        Lead_Configuration__c lc = EEC_TestUtil.mockLeadConfig(null, '');
        
        a = [SELECT Config_Record__r.Name, RecordType.Name FROM Account WHERE Id = :a.Id]; 
        User usr = EEC_TestUtil.mockUser();
        a.OwnerId = usr.Id;
        update a;
        
    }

    @isTest static void testUpdateConfigRecordUpdate(){
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        
        Lead_Configuration__c lc = EEC_TestUtil.mockLeadConfig('Group Care', '');
        a.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName='Group_Care' AND sObjectType='Account'].Id;
        a.Restraint_Method__c = 'TCI';
        update a;
        a = [SELECT Config_Record__r.Name, RecordType.Name FROM Account WHERE Id = :a.Id]; 
        
        System.assertEquals(a.Config_Record__r.Name, lc.Name);
    }

    @isTest static void testUpdateConfigRecordUpdateUmbrella(){
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        
        Lead_Configuration__c lc = EEC_TestUtil.mockLeadConfig('Group Care', '');
        a.RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName='Umbrella' AND sObjectType='Account'].Id;
        
        a = [SELECT Config_Record__r.Name, RecordType.Name FROM Account WHERE Id = :a.Id]; 
        
        System.assertEquals(a.Config_Record__r, null);
    }
}