src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Portal_Home_Latest_News__c</fullName>
        <description>The latest and up to date news for portal users.</description>
        <label>Portal Home Latest News</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Portal_Home_Useful_Links__c</fullName>
        <description>Useful links for portal users on the home page.</description>
        <label>Portal Home Useful Links</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Portal_Home_Welcome__c</fullName>
        <description>This is the portal&apos;s home page message.</description>
        <label>Portal Home Welcome</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_PortalLandingController.cls
public without sharing class EEC_PortalLandingController {
   
 //private String loggedInUser;//variable to store the logged in user id.
 private Account acc;
 public User licensor {get;set;}
 public Lead_Configuration__c leadConfig {get;set;}   
 public String profileName {get;set;}  
 
 public Boolean accessProviderFlag {get;set;}
 public Boolean accessUmbrellaFlag {get;set;}
 public void EEC_PortalLandingController(){

   accessProviderFlag=false;
   accessUmbrellaFlag=false;
   actionMethod();
 }
    
 public PageReference gotoPersonalPage() {
   Id uid = Userinfo.getUserId();
   USER u = [Select Id,ContactId from User where Id =: uid limit 1];
   PageReference contactPage = Page.EEC_ContactPage;
   contactPage.getParameters().put('Id',u.ContactId);
   contactPage.getParameters().put('page','home'); 
   contactPage.setRedirect(true);
   return contactPage;       
 }

 public pagereference actionMethod() {
   List<Profile> profiles = [SELECT Name from Profile where Id = :userinfo.getProfileId() LIMIT 1]; 
   if(profiles.size() > 0) 
		profileName = profiles[0].Name;  
     
   acc = [select Id, Name, RecordType.Name, License_Status__c, OwnerId From Account where ID in (select Accountid from user  where id = :Userinfo.getUserId()) limit 1 ]; 
   //where id = '00511000002hRqxAAE') limit 1];
   licensor = [Select Id, Name, Email From User Where Id = :acc.OwnerId Limit 1];
  
   if (acc <> null ){       
     If (acc.Recordtype.Name.contains('Umbrella')){
       accessUmbrellaFlag = true;
     }else{
       accessProviderFlag = true;
     }
   }
     
   // Get the LEAD config.
   Lead_Configuration__c[] leadConfigs = [Select Id,Name, Portal_Home_Useful_Links__c, Portal_Home_Welcome__c, Portal_Home_Latest_News__c From Lead_Configuration__c Where Name = :acc.RecordType.Name];
	if(leadConfigs.size() > 0)
    {
        leadConfig = leadConfigs[0];
    }
   //   return accessProviderFlag;
   return null;  
 }
    
    public Lead_Configuration__c getLeadConfiguration() {
        return leadConfig;
    }
 
    public Account getAccount(){
        return acc;
      }
               
    public PageReference goToProviderPage() {    
        PageReference pPage = page.EEC_PortalProviderPage;
        return pPage;
    }
    public PageReference goToUmbrellaPage() {
        PageReference pPage = page.EEC_Umbrella;
        return pPage;
    }
    
    public PageReference goToSubmitNewTransaction() {
        PageReference pPage = page.EEC_TransactionIntroduction;
        return pPage;
    }
   
   public PageReference noncomp() {
        PageReference pPage = page.EEC_PortalNonCompliancePage;
        return pPage;
   
    } 
   public PageReference investigationPage() {
        PageReference pPage = page.EEC_Interventionpage;
        return pPage;
        
    }
     public PageReference goToSubmitNewIncident() {
        PageReference pPage = page.EEC_CasesIncidentsPage;
        return pPage;
    }
    
    public PageReference goToSubmitNewRestraint() {
        PageReference pPage = Page.EEC_RestraintReport;
        return pPage;
    }
}