src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Config_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This link the provider to the configuration record that will be used to retrieve default values.</description>
        <label>Config Record</label>
        <referenceTo>LEAD_Configuration__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(  Is_Residential__c ,

CONTAINS ( RecordType.Name , &quot;Agency&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Residential__c</fullName>
        <description>Is checked if the provider is a Group Care or Temporary Shelter</description>
        <formula>IF( OR (RecordType.Name = &quot;Group Care&quot;, RecordType.Name = &quot;Temporary Shelter&quot;), TRUE, FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Is checked if the provider is a Group Care or Temporary Shelter</inlineHelpText>
        <label>Is Residential</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Need_a_licensing_visit__c</fullName>
        <description>This formula is used to calculate if the Provider needs the creation of an automated visit or not. If yes, the text mention what type of visit is required.</description>
        <formula>IF( TEXT(License_Status__c) = &quot;Licensed&quot;,
/* Renewal visit creation */
IF(First_Issue_Date__c + 365 &lt; TODAY() &amp;&amp; TODAY() &gt;= Renewal_date__c - 125 &amp;&amp; TODAY() &lt;= Renewal_date__c - 120, Next_Renewal_Visit_Reason__c ,
/* Other visit creation */
IF( Record_Type_Name__c = &quot;Family Child Care&quot;,

IF( (First_Issue_Date__c + 305 /* 305 days used as 10 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= First_Issue_Date__c + 310 /* 310 days used as 10 MONTHS +5 DAYS */) || (First_Issue_Date__c + 670 /* 670 days used as 22 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= First_Issue_Date__c + 675 /* 675 days used as 22 MONTHS + 5 DAYS */)||
(License_For_10_Upgrade_Date__c + 150 /* 150 days used as 5 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= License_For_10_Upgrade_Date__c + 155 /* 155 days used as 5 MONTHS + 5 DAYS */)||
(License_For_10_Upgrade_Date__c + 545 /* 545 days used as 18 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= License_For_10_Upgrade_Date__c + 550 /* 550 days used as 18 MONTHS + 5 DAYS */), &quot;Progress&quot;, IF( (LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY() , &quot;Monitoring&quot;, &quot;&quot;)),


IF( Is_GSA__c ,

IF( (First_Issue_Date__c + 180 /* 180 days used as 6 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp;
TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;=First_Issue_Date__c + 185 /* 185 days used as 6 MONTHS + 5 DAYS */), &quot;Provisional License Renewal&quot;,

IF( (LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)
&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY() , IF( Last_Mid_Cycle_Review_Date__c &lt;=TODAY()-1825 /* 1825 days used as 5 YEARS */||(ISBLANK(Last_Mid_Cycle_Review_Date__c) &amp;&amp; NUmber_Monitoring_Visit__c &gt; 1),&quot;Enhanced Monitoring&quot;,&quot;Monitoring&quot;), &quot;&quot;)),


IF( Is_R_P__c ,

IF( (First_Issue_Date__c + 180 /* 180 days used as 6 MONTHS */ &lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp;
TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;=First_Issue_Date__c + 185 /* 185 days used as 6 MONTHS + 5 DAYS */), &quot;Provisional License Renewal&quot;,

IF((LastCalcDiffVisit__c + 365 /* 365 days used as 12 MONTHS */&lt;= TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &amp;&amp; TODAY() + Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c &lt;= LastCalcDiffVisit__c + 370 /* 370 days used as 12 MONTHS + 5 DAYS */)
&amp;&amp; Renewal_date__c - 180 /* 180 days used as 6 MONTHS */ &gt;= TODAY()
,&quot;Monitoring&quot;,&quot;&quot;)

)
,&quot;&quot;))
)),

&quot;&quot;)</formula>
        <label>Need a licensing visit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_2__c</fullName>
        <description>Second line of Provider Address</description>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Freeze Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Lic_Anniversary_Visit_Estimated_Deadline__c</fullName>
        <inlineHelpText>Number of days used to calculate the visit estimated deadline for visits automatically created by the system for Monitoring Visits / Progress Visits / Mid-Cycle Review Visits / Provisional Visits</inlineHelpText>
        <label>Lic Anniversary Visit Estimated Deadline</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c</fullName>
        <inlineHelpText>Number of days prior to the window start date the system will create a monitoring / mid-cycle / progress visit automatically so that the licensor knows that a visit should be scheduled</inlineHelpText>
        <label>Nb Days Prior to Window to Create Vis</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_BatchProviderVisitTest.cls
/**
 * EEC_BatchProviderVisitTest
 * 
 */

@isTest
public class EEC_BatchProviderVisitTest {

    static testMethod void testscenario1() {
		String query =  'SELECT Id,Is_Residential__c,Is_R_P__c,Is_GSA__c,Provider_Address_1__c,Provider_Address_2__c,Provider_Zip_Code__c,Config_Record__c,Config_Record__r.Lic_Anniversary_Visit_Estimated_Deadline__c,Config_Record__r.Nb_Days_Prior_to_Lic_Anniv_to_Create_Vis__c,Provider_City__r.Name,Need_a_licensing_visit__c,License_Status__c,Renewal_date__c,OwnerId,Provider_Status__c FROM Account';
		
        Account acc1 = new Account();          
          Date cDate =  System.today();  
          // Scenario 1 : Renewal Application Not Submitted - 30 days prior to  expiration notice
          acc1.Name = 'Test account 1 ';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [SELECT Id FROM RecordType WHERE Name = 'Family Child Care' AND SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = EEC_TestUtil.mockCity().Id;
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Restraint_Method__c ='OWN';
          acc1.Use_Physical_Restraints__c = true;
          acc1.Renewal_date__c = cdate + 30;
          //acc1.Need_a_licensing_visit__c = 'Test';
          //acclist.add(acc1);
          insert acc1; 
        
          Regulation__c reg = EEC_testUtil.mockRegulation();
          List<Inspection__c> lstInsp = new List<Inspection__c>();
          Inspection__c insp1 = new Inspection__c(Provider_No__c = acc1.Id, Status__c = 'Scheduled', Date_of_Visit__c = System.Today() - 5, Inspector_del__c = Userinfo.getUserId(), Visit_Created_By_Batch__c  = true);
          Inspection__c insp2 = new Inspection__c(Provider_No__c = acc1.Id, Status__c = 'Scheduled', Date_of_Visit__c = System.Today() - 5, Inspector_del__c = Userinfo.getUserId(), Visit_Created_By_Batch__c  = true);
        
          lstInsp.add(insp1);
          lstInsp.add(insp2);
          
          insert lstInsp;
          
          Test.startTest(); 
             EEC_BatchProviderVisit sfbatchSync = new EEC_BatchProviderVisit(query);
             ID batchprocessid = Database.executeBatch(sfbatchSync);
          Test.stopTest();
        
          AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                    FROM AsyncApexJob WHERE Id =:batchprocessid];
                //assert for total number of errors
          System.assertEquals(job.NumberOfErrors, 0);  
        
    }
}