src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Can_be_Edited__c</fullName>
        <formula>!AND(OR(ISPICKVAL(Status__c,&apos;Cancelled&apos;), ISPICKVAL(Status__c,&apos;Closed&apos;)),!ISBLANK($UserRole.Name),$UserRole.Name !=&apos;Executive_and_Directors&apos;,$UserRole.Name!=&apos;Regional_Director&apos;,OR(NOT(OR(CONTAINS($UserRole.DeveloperName,&apos;Director&apos;),CONTAINS($UserRole.DeveloperName,&apos;Supervisor&apos;))),AND($UserRole.DeveloperName==&apos;FCC_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Family Child Care&apos;), AND($UserRole.DeveloperName==&apos;SLGSA_Supervisor&apos;,Provider_No__r.RecordType.Name != &apos;Large Group&apos;,Provider_No__r.RecordType.Name != &apos;Small Group&apos;), AND($UserRole.DeveloperName==&apos;R_P_Supervisor&apos;, Provider_No__r.RecordType.Name != &apos;Group Care&apos;,Provider_No__r.RecordType.Name != &apos;Temporary Shelter&apos;,Provider_No__r.RecordType.Name != &apos;Adoption Agency&apos;,Provider_No__r.RecordType.Name != &apos;Foster Care Agency&apos;)))</formula>
        <label>Can be Edited</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Tool_Used__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Visit tool that is used for this visit</inlineHelpText>
        <label>Current Visit Tool Used</label>
        <referenceTo>Standard_Checklist_Reference__c</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Standard_Item</fullName>
        <active>true</active>
        <description>Check list items that are coming from the standard list of inspection items</description>
        <label>Standard Visit Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Junction_ChklInsp__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Checklist Reference and Standard Visit Items objects</description>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Checklist_Reference__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Tool Reference object and the detail JunctionChklInsp object</description>
        <label>Tool</label>
        <referenceTo>Standard_Checklist_Reference__c</referenceTo>
        <relationshipLabel>Associated Visit Items</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionChklInsp object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Tool Assignments</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tools Visit Items</label>
    <nameField>
        <displayFormat>JunctCI# {000000}</displayFormat>
        <label>JunctCINo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/License__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>License_Status__c</fullName>
        <description>License.License Status</description>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Licenses are linked to Providers via Provider No</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Application</label>
    <nameField>
        <displayFormat>Lic# {000000}</displayFormat>
        <label>License No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>License Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this checklist is active and can be used.</description>
        <inlineHelpText>If checked, this checklist is active and can be used. If not checked, it will not be available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this checklist applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of how and when this checklist should be used.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_CopyInspectionsItemsController.cls
public with sharing class EEC_CopyInspectionsItemsController {
	
	private final Inspection__c inspectionRecord;
	//public List<Standard_Inspection_Item__c> siiList {get;set;}
	public List<SCRWrapper> scrWrapperList {get;set;}
  public Boolean disableButton {get; set;}
  public Boolean allowCopyItems {get; set;}
	
	public EEC_CopyInspectionsItemsController(ApexPages.StandardController controller) {
		this.inspectionRecord = (Inspection__c) controller.getRecord();
    Inspection__c i = [SELECT Id, Visit_Tool_Used__c, Mater_Visit_for_Res_Cluster_of_Visits__c FROM Inspection__c WHERE id =: inspectionRecord.Id];
    if(i.Mater_Visit_for_Res_Cluster_of_Visits__c != null){
      disableButton = true;
      allowCopyItems = false;
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'This visit has a master, please use the master to set the checklist to be used.'));
    } else if(i.Visit_Tool_Used__c != null){
      disableButton = true;
      allowCopyItems = false;
      ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'A Visit Tool has already been used for this visit.'));
    } else {
      disableButton = false;
      allowCopyItems = true;
    }

	}
	
	public void populateLists() {
	 if(!allowCopyItems){
    System.debug('******* Copy items not allowed.');
    return;
   }
	 scrWrapperList = new List<SCRWrapper>();
	 if(inspectionRecord.Can_be_edited__c){
		/*List<License__c> licenseList = [select Id,RecordType.Name from License__c where Provider_No__c = :inspectionRecord.Provider_No__c and License_Status__c = 'Active'];
	 	if(licenseList != null && licenseList.size() > 0){
	 		License__c license = licenseList.get(0);*/
	 		String scrIds = '';
	 		String scrQuery = 'select Id,Name from Standard_Checklist_Reference__c where Active__c = true and Applicable_To__c includes (\''+inspectionRecord.Provider_No__r.RecordType.Name+'\')';
	 		List<Standard_Checklist_Reference__c> scrList = Database.Query(scrQuery);
	 		if(scrList != null && scrList.size() > 0){
	 			for(Standard_Checklist_Reference__c scr : scrList){
	 				scrIds = scrIds + '\''+ scr.Id + '\',';
	 			}
	 			
	 			scrIds = scrIds.subString(0,scrIds.length()-1);
	 			String jiQuery = 'Select Standard_Inspection_Item__c,Standard_Inspection_Item__r.name, Standard_Checklist_Reference__c, Non_Assessed_Item__c '+
	 							 'From Junction_ChklInsp__c  where Standard_Checklist_Reference__c in  ('+scrIds+') order by Name asc';
	 			/*String siiQuery = 'select Id,name,Applicable_To__c,Description__c from Standard_Inspection_Item__c where Id in '+
	 			                    '(select Standard_Inspection_Item__c from Junction_ChklInsp__c where Standard_Checklist_Reference__c in ('+scrIds+')) order by Name asc';
	 			*/
	 			List<Junction_ChklInsp__c> jciList = Database.Query(jiQuery);
	 			
	 			Map<Id, List<SIIWrapper>> siiMap = new Map<Id, List<SIIWrapper>>();
	 			List<SIIWrapper> siiMapList = null;
	 			if(jciList != null && jciList.size() > 0){
	 				for(Junction_ChklInsp__c jci : jciList){
	 					//siiWrapperList.add(new SIIWrapper(sii));
	 					if(siiMap.containsKey(jci.Standard_Checklist_Reference__c)){
	 						siiMap.get(jci.Standard_Checklist_Reference__c).add(new SIIWrapper(jci));
	 					}
	 					else{
	 						siiMapList = new List<SIIWrapper>();
	 						siiMapList.add(new SIIWrapper(jci));
	 						siiMap.put(jci.Standard_Checklist_Reference__c,siiMapList);
	 					}
	 				}
	 					 				
	 				for(Standard_Checklist_Reference__c scr : scrList){
	 					scrWrapperList.add(new SCRWrapper(scr,siiMap.get(scr.Id)));
	 				}
	 				System.debug('*********scrWrapperList*********'+scrWrapperList);
	 			}
	 			else{
	 				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There are no Standard Inspection items to copy.'));
	 			}
	 			
	 		}
	 		else{
	 			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There are no \'Active\' Standard check list for this Inspection.'));
	 		}
	 		
	 	/*}
	 	else{
	 		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There is no \'Active\' License for the Provider.'));
	 	}*/
	 }
	 else{
	 	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'This functionality is not available for a Closed or Cancelled Visit, Visit must first be re-opened by a Supervisor or Director.'));
	 }
	}
	
	public Boolean isSIISelected {
        get {
            isSIISelected = false;
            if (scrWrapperList != null && scrWrapperList.size() > 0) {
                for (SCRWrapper scr : scrWrapperList) {
                    if (scr.selected) {
                        isSIISelected = true;
                        break;
                    }
                }
            }
            return isSIISelected;
        }
        private set;
    }
    
    public PageReference copyInspectionItems(){
    	if(!allowCopyItems){
        System.debug('******* Copy items not allowed.');
        return null;
       }
    	PageReference resultPage = null;
        List<Inspection__c> childVisits = new List<Inspection__c>();
        
        if (inspectionRecord.Mater_Visit_for_Res_Cluster_of_Visits__c == null) {
          childVisits = [Select Id From Inspection__c Where Mater_Visit_for_Res_Cluster_of_Visits__c = :inspectionRecord.Id];                    
        }
    	
    	if(isSIISelected){
    		List<Inspection_Item__c> iiList = new List<Inspection_Item__c>();
    		Inspection_Item__c ii;
            for (SCRWrapper scr : scrWrapperList) {
            	if(scr.selected){
            		for(SIIWrapper sii : scr.stiList){
		            	ii = new Inspection_Item__c();
		            	ii.Inspection_No__c = inspectionRecord.Id;
		            	ii.Standard_Inspection_Item__c = sii.Id;
		            	ii.Non_Assessed_Item__c = sii.nonAccessedItem;
		            	ii.RecordTypeId = EEC_RecordTypeUtil.findByName('Inspection_Item__c.Standard_Item').Id;
		            	iiList.add(ii);
                        // If there are child visits to this portential master.
                        if (childVisits != null && childVisits.size() > 0) {
                          // Loop through the children.
                          for (Inspection__c child : childVisits) {
                            // Create a new item for the child entry.
                            ii = new Inspection_Item__c();
		            	    ii.Inspection_No__c = child.Id; 
		            	    ii.Standard_Inspection_Item__c = sii.Id;
		            	    ii.Non_Assessed_Item__c = sii.nonAccessedItem;
		            	    ii.RecordTypeId = EEC_RecordTypeUtil.findByName('Inspection_Item__c.Standard_Item').Id;
                            iiList.add(ii);
                          }  
                        }
            		}
            	}
                inspectionRecord.Visit_Tool_Used__c = scr.Id;
            }
            
            if(iiList != null && iiList.size() > 0){
            	insert iiList;
            }
            
            update inspectionRecord;
    		return (new PageReference('/'+inspectionRecord.Id));
    	}
    	else{
    		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Atleast one item should be selected.'));
    	}
    	
    	return resultPage;
    	
    }
    
     public class SIIWrapper{
     	
     	public Id Id {get;set;}
     	public String name {get; private set;}
     	public Boolean nonAccessedItem {get;set;}
     	public SIIWrapper(Junction_ChklInsp__c jci) {
     		this.Id = jci.Standard_Inspection_Item__c;
            this.name = jci.Standard_Inspection_Item__r.name;
            this.nonAccessedItem = jci.Non_Assessed_Item__c;
        }
        
     }
     
     public class SCRWrapper{
     	
     	public Id Id {get;set;}
     	public String name {get; private set;}
     	public Boolean selected {get; set;}
     	public List<SIIWrapper> stiList {get;set;}
     	
     	
     	public SCRWrapper(Standard_Checklist_Reference__c scr, List<SIIWrapper> stList) {
     		this.Id = scr.Id;
            this.name = scr.name;
            this.selected = false;
            this.stiList = stList;
        }
        
     }

}