src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Freeze Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Restraint_Method__c</fullName>
        <label>Restraint Method</label>
        <picklist>
            <picklistValues>
                <fullName>ANV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PART</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CALM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DYS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAPPI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonRestraint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NVSD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OWN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Varied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Use_Physical_Restraints__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Physical Restraints</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <description>Copies the email id from the Provider record so it can be used as a Recipient in workflows on the Investigation object</description>
        <label>Provider Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Non_Compliant_Item_Regulation__c.object
<CustomObject>
    <description>Junction between non compliant items and regulations so multiple regulations can be added to one non-compliant item.</description>
    <fields>
        <fullName>Non_Compliant_Item__c</fullName>
        <label>Non Compliant Item</label>
        <referenceTo>Non_Compliant__c</referenceTo>
        <relationshipLabel>Associated Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Non Compliant Item Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non Compliant Item Regulation</label>
    <nameField>
        <displayFormat>NC-R-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Date_Active__c</fullName>
        <description>Date this regulation must be applied</description>
        <inlineHelpText>Date this regulation must be applied by Provider</inlineHelpText>
        <label>Date Active</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FCC_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>FCC High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reg_key__c</fullName>
        <description>Regulation key from external system (EECRS)</description>
        <externalId>true</externalId>
        <label>Reg_key</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_NCItemRegulationTgrHandlerTest.cls
@istest 

public with sharing class EEC_NCItemRegulationTgrHandlerTest {
	
	@istest static void EEC_NCIR(){
		
	Account acc1 = new Account();          
          Date cDate =  System.today();  
          // Scenario 1 : Renewal Application Not Submitted - 30 days prior to  expiration notice
          acc1.Name = 'Test account 1 ';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = EEC_TestUtil.mockCity().Id;
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Restraint_Method__c = 'OWN';
          acc1.Use_Physical_Restraints__c = true;
          acc1.Renewal_date__c = cdate +30; 
          acc1.Provider_No__c = '603735';
          insert acc1;
        
        Regulation__c reg = new Regulation__c();
        reg.Applicable_To__c = 'Family Child Care';
        reg.Name = '14.14';
        reg.Date_Active__c = system.today();
        reg.Reg_key__c = 'FGS-18';
        reg.FCC_High_Risk_Reg__c=true;
        insert reg;
        
        Regulation__c reg1 = new Regulation__c();
        reg1.Applicable_To__c = 'Family Child Care';
        reg1.Name = '14.15';
        reg1.Date_Active__c = system.today();
        reg1.Reg_key__c = 'FGS-19';
        reg1.FCC_High_Risk_Reg__c=true;
        insert reg1;
        
        Investigation__c Inv = new Investigation__c();
        Inv.Provider_No__c= acc1.id;
        insert Inv;
        
        Non_Compliant__c NC = new Non_Compliant__c();
        NC.Observations__c ='test';
        NC.Investigation__c = Inv.id;
        insert NC; 
        
        Non_Compliant__c NC1 = new Non_Compliant__c();
        NC1.Observations__c ='test';
        NC1.Investigation__c = Inv.id;
        insert NC1;  
        
        Non_Compliant_Item_Regulation__c NCIR = new Non_Compliant_Item_Regulation__c();
        NCIR.Non_Compliant_Item__c = NC.id;
        NCIR.Regulation__c = reg.id;
        
        Non_Compliant_Item_Regulation__c NCIR1 = new Non_Compliant_Item_Regulation__c();
        NCIR1.Non_Compliant_Item__c = NC1.id;
        NCIR1.Regulation__c = reg1.id;
        insert NCIR1;
        
        
        Test.startTest();
        insert NCIR;
        delete NCIR1;
        EEC_NonComplaintItemRegulationTgrHandler hdlr = new EEC_NonComplaintItemRegulationTgrHandler();
        
	    /* map<id,Non_Compliant_Item_Regulation__c> newmap = new map<id,Non_Compliant_Item_Regulation__c>([select id,name,Non_Compliant_Item__c,Non_Compliant_Item__r.Key_Indicator__c,Non_Compliant_Item__r.Investigation__r.id,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.name,Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c,Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c,
	                                                Regulation__c,Regulation__r.FCC_High_Risk_Reg__c,Regulation__r.R_P_High_Risk_Reg__c,Regulation__r.GSA_High_Risk_Reg__c 
	                                                from Non_Compliant_Item_Regulation__c where id =: NCIR.Id]);
	    map<id,Non_Compliant_Item_Regulation__c> oldmap = new map<id,Non_Compliant_Item_Regulation__c>([select id,name,Non_Compliant_Item__c,Non_Compliant_Item__r.Key_Indicator__c,Non_Compliant_Item__r.Investigation__r.id,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.name,Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c,Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c,
	                                                Regulation__c,Regulation__r.FCC_High_Risk_Reg__c,Regulation__r.R_P_High_Risk_Reg__c,Regulation__r.GSA_High_Risk_Reg__c 
	                                                from Non_Compliant_Item_Regulation__c where id =: NCIR.Id]);*/
        //EEC_NonComplaintItemRegulationTgrHandler.UpdateKeyIndicator(newmap,oldmap);
        //EEC_NonComplaintItemRegulationTgrHandler.UpdateKeyOnDelete(newmap,oldmap);
        Test.stopTest();
        
	}
    
}