src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Provider State</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Announced__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Announced</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Deadline__c</fullName>
        <label>Estimated Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>&quot;MA&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Visit__c</fullName>
        <description>Reason of Visit</description>
        <label>Reason of Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLatitude__c</fullName>
        <description>Latitude part of geo-coordinates of the visit address</description>
        <label>visitLatitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLongitude__c</fullName>
        <description>Longitude part of geo-coordinates of the visit address</description>
        <label>visitLongitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_ShowMapsController.cls
public with sharing class EEC_ShowMapsController {
        
        public list<InspectionWrapper> inspWrapperList {get;set;}
        public String userId {get;set;}
        public EEC_ShowMapsController(){
            try{ Set<Id> accountSet = new Set<Id>();
                inspWrapperList = new List<InspectionWrapper>();
                Set<Id> userSet = getUserSet(); 
                List<Inspection__c> inspList =  [SELECT Id,name,Provider_no__c,Status__c,Inspector_del__r.name,Estimated_Deadline__c
                                                                , Date_of_Visit__c,Announced__c,Provider_no__r.name, Address_1__c, State__c, Zip_Code__c,City__c
                                                                , Type_of_Visit__c, visitLongitude__c, visitLatitude__c
                                                            FROM Inspection__c WHERE provider_no__c != null and Status__c in ('Scheduled','To be scheduled') 
                                                                and City__c != null 
                                                                and (Provider_no__r.OwnerId in :userSet or Inspector_del__c in :userSet)];
                    
                for(Inspection__c insp : inspList){
                    System.debug('-------> Inspection: ' + insp);
                    if(insp.visitLongitude__c != null){
                        inspWrapperList.add(new InspectionWrapper(insp));
                        System.debug('-------> Inspection: ' + insp);
                    }
                    //accountSet.add(insp.provider_no__c);                                                  
                }
                
                System.debug('*******inspWrapperList** ' + inspWrapperList.size() + ' -- ' + inspWrapperList);
            } catch(Exception ex){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error:' +ex.getMessage()));
            }
            
            userId = UserInfo.getUserId();
        }
        
    public class InspectionWrapper{ 
        public Id Id {get;set;}
        public String content {get;set;}
        //public String announced {get;set;}
        public String providerAddress {get;set;}
        public String visitLink {get;set;}
        public String status {get;set;}
        public Decimal longitude {get; set;}
        public Decimal latitude {get; set;}
        public Date deadline {get; set;}
        
        public InspectionWrapper(Inspection__c insp){
            this.Id = insp.Id;
            
            this.providerAddress = insp.Address_1__c + ', ' + insp.city__c +', '+insp.State__c+', USA';
            //this.announced = (insp.Announced__c?'Announced':'Un-Announced');

            this.longitude = Decimal.valueOf(insp.visitLongitude__c);
            this.latitude = Decimal.valueOf(insp.visitLatitude__c);
            this.deadline = insp.Estimated_Deadline__c;
            
            System.debug('longitude: ' + longitude);
            
            this.visitLink = ' - <a target=\'_blank\' href=\'/' + insp.Id + '\'><b>Open Visit</b></a>';
            this.status = insp.Status__c;
            String deadlineEstimated = insp.Estimated_Deadline__c != null ? (' - <b>Deadline</b> - '+insp.Estimated_Deadline__c.format() ):'';
            String visitDate = insp.Date_of_Visit__c != null ? (' - <b>Visit Date</b> - '+insp.Date_of_Visit__c.format() ):'';
            String assignedTo = insp.Inspector_del__c != null ? (' - <b>Assigned to</b> - '+insp.Inspector_del__r.name):'';
            String typeOfVisit = insp.Type_of_Visit__c != null ? (' - <b>Reason of Visit</b> - ' + insp.Type_of_Visit__c ):'';
            this.content = '<b>'+insp.Provider_no__r.name + '</b> -- ' +insp.Status__c +' -- ' + deadlineEstimated + visitDate + assignedTo + typeOfVisit + visitLink;
        }
    }

        public Set<Id> getUserSet(){
            Set<Id> userSet = new Set<Id>();
            List<User> userList;
            Map<Id,User> innerMap;
            Set<Id> innerSet;
            userSet.add(UserInfo.getUserId());
            
            Map<Id,User> userMap = new Map<Id,User>([select Id,ManagerId from User where ManagerId != null and ManagerId = :UserInfo.getUserId()]);
            
            if(userMap != null && userMap.size() > 0){
                userSet.addAll(userMap.keyset());
                innerSet = userMap.keyset();
                for(integer i=0;i<6;i++){
                    innerMap = new Map<Id,User>([select Id from User where ManagerId in :innerSet]);
                    if(innerMap != null && innerMap.size() > 0){
                        userSet.addAll(innerMap.keySet());
                        innerSet = innerMap.keySet();
                    }
                    else{
                        break;
                    }
                    
                }
            }
            System.debug('********userSet -- '+userSet);
            return userSet;
        }

}