src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <recordTypes>
        <fullName>Additional_Inspection_Item</fullName>
        <active>true</active>
        <description>Visit item that is not defined in LEAD Configuration, and most likely will reference a regulation article that needs to be or has been reviewed during the visit</description>
        <label>Non Standard Visit Item</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Non_Compliant_Item_Regulation__c.object
<CustomObject>
    <description>Junction between non compliant items and regulations so multiple regulations can be added to one non-compliant item.</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Non Compliant Item Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non Compliant Item Regulation</label>
    <nameField>
        <displayFormat>NC-R-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_PortalNonCompliancePageTest.cls
@isTest
public class EEC_PortalNonCompliancePageTest {
    
  public static testMethod void testEEC_PortalNonCompliancePageController() {
    PageReference pr = Page.EEC_PortalNonCompliancePage;
    Test.setCurrentPage(pr);
    ID accountid;  
    
    Inspection__c insp = EEC_TestUtil.loadInspectionSetup(); 
    
    RecordType rType = [select Id from RecordType where SobjectType = 'Inspection_Item__c' and DeveloperName = 'Additional_Inspection_Item'];
    List<Inspection_Item__c> iItemList = [select Id,Inspection_No__r.Provider_No__c from Inspection_Item__c where Inspection_no__c = :insp.Id and RecordTypeId = :rType.Id];
    Inspection_Item__c iItem = iItemList.get(0);     
    accountid=insp.Provider_No__c;
    ApexPages.currentPage().getParameters().put('accountid',accountid);    
    EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();    
    ncomp = new EEC_PortalNonCompliancePageController();    
    Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
    Regulation__c reg =  EEC_TestUtil.mockRegulation();
    Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
    Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
    accountid=inv.Provider_No__c;
    ApexPages.currentPage().getParameters().put('accountid',accountid);    
    EEC_PortalNonCompliancePageController ncomp2 = new EEC_PortalNonCompliancePageController();    
    ncomp2 = new EEC_PortalNonCompliancePageController();
    
  }           
  
   static testMethod void testSaveInspectionItems() {
        //Account prov = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        //ApexPages.currentPage().getParameters().put('accountid',prov.Id);
        EEC_PortalNonCompliancePageController ncomp = new EEC_PortalNonCompliancePageController();
        //Inspection__c ins = EEC_TestUtil.mockInspection(prov);
        //Inspection_Item__c insItem = EEC_TestUtil.mockInspectionItem(ins, EEC_TestUtil.mockStdInspectionItem(), '', true, '');       
       
        
        Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
        Inspection_Item__c inspItem = EEC_TestUtil.mockInspectionItem(insp, EEC_TestUtil.mockStdInspectionItem(), '', true, '');       
        Investigation__c inv = EEC_TestUtil.loadInvestigationSetup(); 
        Regulation__c reg =  EEC_TestUtil.mockRegulation();
        Non_Compliant__c nc = EEC_TestUtil.mockNonCompliant(inv);
        Non_Compliant_Item_Regulation__c ncr = EEC_TestUtil.mockNonCompliantItemRegulation(nc,reg);
       

        List<EEC_PortalNonCompliancePageController.InspectionListWrapper> iiWrapperList = new List<EEC_PortalNonCompliancePageController.InspectionListWrapper>();
        List<EEC_PortalNonCompliancePageController.ComplainceListWrapper> ncWrapperList = new List<EEC_PortalNonCompliancePageController.ComplainceListWrapper>();       
        
        // Create a new wrapper list for the controller.
        iiWrapperList = new List<EEC_PortalNonCompliancePageController.InspectionListWrapper>();
        ncWrapperList = new List<EEC_PortalNonCompliancePageController.ComplainceListWrapper>();
        
        // Create and add a new InspectionListWrapper.
        EEC_PortalNonCompliancePageController.InspectionListWrapper ilw = new EEC_PortalNonCompliancePageController.InspectionListWrapper(0, inspItem, null);
        iiWrapperList.add(ilw);
        EEC_PortalNonCompliancePageController.ComplainceListWrapper clw = new EEC_PortalNonCompliancePageController.ComplainceListWrapper(0, nc, null);
        ncWrapperList.add(clw);
       
        
 
        ncomp.iiWrapperList =iiWrapperList;
        ncomp.ncWrapperList =ncWrapperList;
        ncomp.Save();   
        ncomp.Cancel();  
       
  }
    
  static testMethod void testInspectionListWrapper() {
        new EEC_PortalNonCompliancePageController.InspectionListWrapper(0, new Inspection_Item__c(), null);
  } 
  
  
 
}