src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Current_License_Number__c</fullName>
        <label>Current License Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_Address_2__c</fullName>
        <description>Second line of Provider Address</description>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Provider_Number__c</fullName>
        <displayFormat>P-{00000}</displayFormat>
        <label>Provider Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Provider State</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Use_Legacy_Prov_Number__c</fullName>
        <description>This field returns true if the legacy provider number must be used (used in report)</description>
        <formula>IF ( ISBLANK ( Provider_No__c ), FALSE, IF (  Licensing_Transaction_Closed__c &gt; 0, FALSE, TRUE))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Use Legacy Prov Number</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <inlineHelpText>At creation and if left blank, Address 2 will be populated with Provider address after saving</inlineHelpText>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>&quot;MA&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_GeneratePDFNCController.cls
public with sharing class EEC_GeneratePDFNCController {
    
    //private ApexPages.StandardController controller;
    public Inspection__c inspection {get;set;}
    public List<InspectionListWrapper> iiWrapperList {get;set;}
    public Id inspectionId {get;set;}
    
    
    public EEC_GeneratePDFNCController(){
        inspectionId = ApexPages.currentPage().getParameters().get('id');
        generateData();
    }

    public void generateData(){
        iiWrapperList = new List<InspectionListWrapper>();
        
        System.debug('********-- '+inspectionId);
        inspection = [SELECT Id,name,Date_of_Visit__c,Provider_No__c,Provider_No__r.name,Provider_No__r.Provider_Number__c,Provider_No__r.Provider_no__c,Provider_No__r.BillingStreet, 
                             Provider_No__r.BillingState,Provider_No__r.BillingPostalCode, Provider_No__r.BillingCountry, Provider_No__r.BillingCity,
                             Provider_No__r.Phone, Provider_No__r.Umbrella_Members__r.name, Provider_No__r.Umbrella_Members__r.Provider_no__c, Provider_No__r.Umbrella_Members__r.Current_License_Number__c,
                      		 Provider_No__r.Umbrella_Members__r.Use_Legacy_Prov_Number__c,Provider_No__r.Umbrella_Members__r.Provider_Number__c,
                             Address_1__c , Address_2__c, City__c, State__c, Zip_Code__c, Provider_No__r.Provider_Address_1__c, Provider_No__r.Provider_Address_2__c, Provider_No__r.Provider_City__r.Name,
                             Provider_No__r.State__c, Provider_No__r.Provider_Zip_Code__c,
                             Provider_No__r.Umbrella_Members__r.Phone,Provider_No__r.Umbrella_Members__r.BillingStreet, Provider_No__r.Umbrella_Members__r.BillingState, 
                             Provider_No__r.Umbrella_Members__r.BillingPostalCode, Provider_No__r.Umbrella_Members__r.BillingCountry, Provider_No__r.Umbrella_Members__r.BillingCity,
                             Provider_No__r.Owner.Name,Provider_No__r.Owner.Title, Provider_No__r.Current_License_Number__c,Provider_No__r.Use_Legacy_Prov_Number__c from Inspection__c where Id = :inspectionId];
        System.debug('********--****'+inspection);
        List<Inspection_Item__c> iiList = [select Id, name,RecordType.Name,Observations__c,Correction_Plan__c,Visit_Mode_Ranking__c,Date_Implemented__c,Standard_Inspection_Item__c,Associated_regulation__c,
                                                  Associated_regulation__r.name,Inspection_Result__c
                                           from Inspection_Item__c where Inspection_No__c = :inspection.Id and Inspection_Result__c = 'Non-Compliant' order by Visit_Mode_Ranking__c asc nulls last];
        
        Set<Id> siSet = new Set<Id>();
        if(iiList != null && iiList.size() > 0){
            for(Inspection_Item__c ii : iiList){
                if(ii.RecordType.Name == 'Standard Visit Item'){
                    siSet.add(ii.Standard_Inspection_Item__c);
                }
            }
            
            Map<Id,List<String>> iregulationMap = new Map<Id,List<String>>();
            List<String> jiList;
            for(Junction_InspReg__c jir : [select Id,Regulation__c,Regulation__r.name, Regulation__r.article__c,Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c in :siSet]){
                if(iregulationMap.containsKey(jir.Standard_Inspection_Item__c)){
                    iregulationMap.get(jir.Standard_Inspection_Item__c).add(', ' + jir.Regulation__r.name);
                }
                else{
                    jiList = new List<String>();
                    jiList.add(jir.Regulation__r.name);
                    iregulationMap.put(jir.Standard_Inspection_Item__c,jiList);
                }
            }
            Boolean showII = false;
            
            for(Inspection_Item__c ii : iiList){
                System.debug('*****Record Type*** '+ii.RecordType.Name + ' **** '+ii.Standard_Inspection_Item__c + ' ** '+ii.Associated_regulation__c);
                showII = false;
                if(ii.RecordType.Name == 'Standard Visit Item' && String.isNotBlank(ii.Standard_Inspection_Item__c) && iregulationMap.get(ii.Standard_Inspection_Item__c) != null){
                    showII = true;
                }
                else if(ii.RecordType.Name == 'Additional Inspection Item' && String.isNotBlank(ii.Associated_regulation__c)){
                    showII = true;
                }
                
                if(showII || String.isNotBlank(ii.observations__c) || String.isNotBlank(ii.Correction_Plan__c) || ii.Date_Implemented__c != null){
                    iiWrapperList.add(new InspectionListWrapper(ii,iregulationMap));
                }
            }
        }
        
    }
    
    public class InspectionListWrapper{
        
        public Id Id {get;set;}
        public String name {get;set;}
        public String Type {get; private set;}
        public List<String> regulationList {get; set;}
        public String result {get;set;}
        public String observations {get;set;}
        public String correctionPlan {get;set;}
        public Date dateImplemented {get;set;}
        public Boolean showII {get;set;}
        
        public InspectionListWrapper(Inspection_Item__c insp,Map<Id, List<String>> iRegMap) {
            this.Id = insp.Id;
            this.name = insp.name;
            this.Type = insp.RecordType.Name;
            this.regulationList = null;
            
            if(this.Type == 'Standard Visit Item' && insp.Standard_Inspection_Item__c != null){
                this.regulationList = iRegMap.get(insp.Standard_Inspection_Item__c);
                this.showII = true;
            }
            else{
                this.regulationList = new List<String>();
                if(insp.Associated_regulation__c != null){
                    this.regulationList.add(insp.Associated_regulation__r.name);
                    this.showII = true;
                }
            }
            
            this.result = insp.Inspection_Result__c;
            this.observations = insp.observations__c;
            this.correctionPlan = insp.Correction_Plan__c;
            this.dateImplemented = insp.Date_Implemented__c;
         }
        
     }
    
    
    /*public pagereference GeneratePDF(){
        
        PageReference pagePdf = new PageReference('/apex/AttachPDFTerryTest');
          pagePdf.getParameters().put('id', idVal);
          pagePdf.getParameters().put('doSave', 'No');
          Blob pdfPageBlob;
          pdfPageBlob = pagePdf.getContentAsPDF();
                 
          Attachment a = new Attachment();
          a.Body = pdfPageBlob;
          a.ParentID = idVal;
          a.Name = 'TerryTestAttach1.pdf';
          a.Description = 'TestDescription1';
          insert a;
      return new PageReference('/' + idVal);
      
      
        Attachment att = new Attachment(name ='NonCompliant-'+inspection.name+'.pdf');
        PageReference invoicePage = Page.EEC_GeneratePDFNC;
        att.OwnerId = UserInfo.getUserId();
        att.body = invoicePage.getContent();
        //System.debug('***** '+invoicePage.getContent());
        att.parentid = inspection.id;
        //insert att;
        
        return new PageReference('/'+inspection.Id);
    }*/
}