src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Region this provider is assigned to</description>
        <label>Licensing Region</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Region__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Licensing Region</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Closing_Reasons__c</fullName>
        <label>Closing Reasons</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Cancellation__c</fullName>
        <description>If status is changed to Cancel, then Cancellation reason must be provided.</description>
        <label>Closed / Cancellation Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Closed_Cancellation_Date__c</fullName>
        <description>Save the date when the visit was closed or cancelled</description>
        <label>Closed / Cancellation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Provider_No__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Correction_Plan_Status__c</fullName>
        <label>Correction Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Collect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider Submitted, EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Non-compliance</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND(
ISPICKVAL(Inspection_Result__c, &quot;Non-Compliant&quot;),
ISBLANK( Date_Implemented__c )
)</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Approval_Task_Creation__c</fullName>
        <label>Approval Task Creation</label>
        <picklist>
            <picklistValues>
                <fullName>NonEscalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonEscalated Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Investigation.Closed Date</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Leader_Deputy_Commisioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalated Inv - First Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leader_Investigation_Director</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Director_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalated Inv - Second Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leader_Director_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Leader_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Leader Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leader_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND( ISBLANK( Date_Implemented__c ),  NOT(Investigation__r.isLegacyInvestigation__c) )</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <fields>
        <fullName>Deputy_Commissioner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. This user is the 1st reviewer / approver.</inlineHelpText>
        <label>Investigation Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Regional_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This information is used by the system during the approval process of escalated Investigation. For FCC / GSA, this user is the 2nd reviewer / approver.</inlineHelpText>
        <label>Regional Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Regions3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EEC_InvestigationTriggerHandler.cls
public with sharing class EEC_InvestigationTriggerHandler {

    private Map<Id, Investigation__c> newMap;
    private Map<Id, Investigation__c> oldMap;
    private Map<Id,User> userMap;
    private Map<Id,Account> providerMap;
    private List<Case> cases;
    private List<Inspection__c> inspections;
    private List<Task> tasks;
    private Boolean gotRelatedObjects = false;
    private Set<Id> leaderSet;
    private Set<Id> providerSet;
    public static boolean FirstRun = true;

    public EEC_InvestigationTriggerHandler(Map<Id, Investigation__c> newMap, Map<Id, Investigation__c> oldMap){
        this.newMap = newMap;
        this.oldMap = oldMap; 
    }
    
   
    public void updateClosedInvestigationsBefore(){
        
        leaderSet = new Set<Id>();
        providerSet = new Set<Id>();
        for(Investigation__c inv : newMap.values()){
            
            Investigation__c old = oldMap.get(inv.Id);
            System.debug(inv.Investigation_Status__c);
            System.debug(old);
            
            providerSet.add(inv.Provider_no__c);
            if(String.isNotBlank(inv.Assigned_to__c)){
                leaderSet.add(inv.Assigned_to__c);
            }   
            if((old == NULL || old.Investigation_Status__c != 'Closed') && inv.Investigation_Status__c == 'Closed'){
                inv.Closed_date__c = System.Today();
                inv.Created_on_the_Web__c = true;
            }
        }
        
    }
    
    private void getRelatedObjects(){ 
        
        this.cases = [
            SELECT ID, Investigation__c
            FROM Case 
            WHERE Investigation__c IN :newMap.keySet()
        ];
        
        this.inspections = [
            SELECT ID, Investigation__c
            From Inspection__c 
            WHERE Investigation__c IN :newMap.keySet()
            AND (Status__c = 'Visit Completed')
        ];
        
        this.tasks = [
            SELECT ID, WhatId
            FROM Task 
            WHERE WhatId IN :newMap.keySet() 
            AND IsRecurrence = false AND Status != 'Completed'
        ];

        this.gotRelatedObjects = true;
    }
    
    public void updateClosedInvestigationsAfter() {
    
        for(Investigation__c inv : newMap.values()){
            
            Investigation__c old = oldMap.get(inv.Id);
            
            if((old == NULL || old.Investigation_Status__c != 'Closed') && inv.Investigation_Status__c == 'Closed'){
                
                if(!this.gotRelatedObjects){
                    getRelatedObjects();
                }
                
                List<Case> cases = casesForInvestigation(inv); 
                
                for(Case c : cases){ 
                    c.Status = 'Closed';
                    c.Closing_reasons__c = 'Investigation Closed';
                } 
                
                if(cases.size() != 0){
                    update cases;
                }
                
                System.debug('Inspection ----->' + inspections);
                for(Inspection__c insp : inspectionsForInvestigation(inv)){
                    insp.Status__c = 'Closed';
                    insp.Closed_Cancellation_Date__c = System.Today();
                    insp.Cancellation__c = 'Investigation Closed';
                }
                
                if(inspections.size() != 0){
                    update inspections;
                }
                
               /* List<Task> tasks = tasksForInvestigation(inv);
                
                for(Task t : tasks){
                    t.Status = 'Completed'; 
                }
                
                if(tasks.size() != 0){
                    update tasks;
                }*/
                
            }
        }
    }
    
    public void updateLeaderHeirarchy(){
        
        List<Task> approvalTaskList = new List<Task>();
        Account provider;
        providerMap = new Map<Id,Account>([select Id,Region__c, Region__r.Deputy_Commissioner__c,Region__r.Regional_Director__c,RecordType.Name from Account where Id in :providerSet]);
        if(leaderSet != null && leaderSet.size()>0){
            this.userMap  = new Map<Id,User>([select Id, ManagerId from User where Id in :leaderSet and ManagerId != null]);
        }
        
        for(Investigation__c inv : newMap.values()){
            provider = providerMap.get(inv.Provider_no__c);
            if(String.isNotBlank(provider.Region__c) && String.isNotBlank(provider.Region__r.Deputy_Commissioner__c)){
                inv.Leader_Deputy_Commisioner__c = provider.Region__r.Deputy_Commissioner__c;
            }
            if(userMap != null && String.isNotBlank(inv.Assigned_To__c) && userMap.containsKey(inv.Assigned_To__c)){
                inv.Leader_Manager__c = userMap.get(inv.Assigned_To__c).ManagerId;
            }
            if(provider.RecordType.Name == 'Family Child Care' || provider.RecordType.Name == 'Small Group' || provider.RecordType.Name == 'Large Group'){
                inv.Leader_Director_Supervisor__c = provider.Region__r.Regional_Director__c;
            }
            else{
                inv.Leader_Director_Supervisor__c = inv.Leader_Manager__c;
            }
            
            String newATC = inv.Approval_Task_Creation__c;
            String oldATC;
            Task approvalTask;
            if(String.isNotBlank(newATC)){
                if(oldMap != null){
                    Investigation__c old = oldMap.get(inv.Id);
                    oldATC = (old != null && String.isNotBlank(old.Approval_Task_Creation__c))?old.Approval_Task_Creation__c:'';
                    if(newATC != oldATC){
                        if(newATC == 'NonEscalated Approved' || newATC == 'Escalated Approved'){
                            approvalTask = new Task();
                            approvalTask.Subject = 'Prepare and send investigation report to Provider';
                            approvalTask.Status = 'Not Started';
                            approvalTask.Priority = 'High';
                            approvalTask.WhatId = inv.Id;
                            approvalTask.OwnerId = String.isNotBlank(inv.Assigned_To__c)?inv.Assigned_To__c:UserInfo.getUserId();
                            approvalTask.ActivityDate = Date.today().addDays(3);
                            approvalTaskList.add(approvalTask);
                            
                        }
                        else if(newATC == 'NonEscalated Rejected' || newATC == 'Escalated Rejected'){
                            approvalTask = new Task();
                            approvalTask.Subject = 'Re-work required on investigation following review and rejection';
                            approvalTask.Status = 'Not Started';
                            approvalTask.Priority = 'High';
                            approvalTask.WhatId = inv.Id;
                            approvalTask.OwnerId = String.isNotBlank(inv.Assigned_To__c)?inv.Assigned_To__c:UserInfo.getUserId();
                            approvalTask.ActivityDate = Date.today().addDays(3);
                            approvalTaskList.add(approvalTask);
                        }
                        
                    }
                }
            }
        }
        if(approvalTaskList != null && approvalTaskList.size()>0){
            insert approvalTaskList;
        }
        
    }
    
    
    
    public List<Case> casesForInvestigation(Investigation__c i){ 
        List<Case> l = new List<Case>();
        
        for(Case c : cases){
            if(c.Investigation__c == i.Id){
                l.add(c);
            }
        }
        
        return l;
    }
    
    public List<Task> tasksForInvestigation(Investigation__c i){ 
        List<Task> l = new List<Task>();
        
        for(Task t : tasks){
            if(t.WhatId == i.Id){
                l.add(t);
            }
        }
        
        return l;
    }
    
    public List<Inspection__c> inspectionsForInvestigation(Investigation__c i){ 
        List<Inspection__c> l = new List<Inspection__c>();
        
        for(Inspection__c insp : inspections){
            if(insp.Investigation__c == i.Id){
                l.add(insp);
            }
        }
        
        return l;
    }
    
    /**
     * checkVisitsForPublishedToWeb
     * 
     * This function will verify all visits and non compliants for published to web. 
     * @author Darkis
     */
    public void checkVisitsForPublishedToWeb() {
      for(Investigation__c inv : newMap.values()){
        Investigation__c old = oldMap.get(inv.Id); System.debug('-----> Investigation: ' + inv.Id);
        // If the old record was not published to web and the new one is then continue.  
        if (!old.Created_on_the_Web__c && inv.Created_on_the_Web__c) {
          // Get all the related visits who are not closed or cancelled.
          List<Id> visitIds = new List<Id>();
          List<Inspection__c> visits = [Select Id, Name, Status__c, Created_on_the_Web__c From Inspection__c Where Investigation__c = :inv.Id AND Status__c NOT IN('Cancelled')];  System.debug('-----> Visits: ' + visits);
          // If there are any visits meeting the criteria.
          if (visits != null && visits.size() > 0) {
            // Loop through the results.
            for (Inspection__c visit : visits) {
              visitIds.add(visit.Id);
              visit.Created_on_the_Web__c = true;
            }    
            // Update the visits. The visits will be modified by the Visits trigger to set Visit Items to Review on Portal = true and the Visit to "Report Sent to Provider, Awaiting Feedback".
            update visits;
          }
          //Get all non-compliant items.
          List<Non_Compliant__c> nonCompliantItems = [Select Id, Name, Feedback_Requested__c,Correction_Plan_Status__c, To_Review_on_Portal__c From Non_Compliant__c Where Investigation__c = :inv.Id AND Feedback_Requested__c = true]; System.debug('-----> NonCompliants: ' + nonCompliantItems);
          // If there are non compliant items with feedback requested. 
          List<Non_Compliant__c> updateNonComp = new List<Non_Compliant__c>();
          if (nonCompliantItems != null && nonCompliantItems.size() > 0) {
            // Loop through non compliant items and update To_Review_on_Portal__c to True.
            for (Non_Compliant__c ncItem : nonCompliantItems) {
                Non_Compliant__c ncItem2 = ncItem;
                ncItem2.To_Review_on_Portal__c = true;
                ncItem2.Correction_Plan_Status__c ='Provider To Submit';
                updateNonComp.add(ncItem2);
            }
            update updateNonComp;
          }
          // Get a count of the Visit Items that have Feedback_Requested__c = true.
          Integer visitItemsCount = [Select Count() From Inspection_Item__c Where Feedback_Requested__c = true AND Inspection_No__c IN :visitIds]; System.debug('-----> visitItemsCount: ' + visitItemsCount);
          // If there are any NonCompliant Items OR Visit Items with Feedback_Requested__c = true then update the Investigation.   
          if ((nonCompliantItems != null && nonCompliantItems.size() > 0) || (visitItemsCount != null && visitItemsCount > 0)) {
            // Update Investigation fields.
            Investigation__c newInvest = [Select Id, Name, Require_Portal_Feedback__c,lock_investigation__c From Investigation__c Where Id = :inv.Id];
            system.debug('****locked Investigation ****'+ newInvest.lock_investigation__c);
            newInvest.Require_Portal_Feedback__c = true;
            update newInvest;     
          } 
        }
      }
    }
}