src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_FCC__c</fullName>
        <description>Used for Validating with regulation (Key indicator)</description>
        <formula>IF(RecordType.Name == &apos;Family Child Care&apos;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is FCC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_GSA__c</fullName>
        <description>Will be true if this provider is a Large Group or Small Group</description>
        <formula>OR ( Record_Type_Name__c  = &apos;Large Group&apos;, Record_Type_Name__c   = &apos;Small Group&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is GSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_R_P__c</fullName>
        <description>Return True if this is an R&amp;P provider</description>
        <formula>OR(  Is_Residential__c ,

CONTAINS ( RecordType.Name , &quot;Agency&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is R&amp;P</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Correction_Plan_Status__c</fullName>
        <label>Correction Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Collect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider Submitted, EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Non-compliance</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <inlineHelpText>User who added the corrective actions</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Correction_Plan_Accepted__c</fullName>
        <label>Date Correction Plan Accepted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Key_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this visit item is identified as a key indicator = associated to a regulation flagged as high risk</inlineHelpText>
        <label>Key Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Junction_InspReg__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Visit Items and Regulations objects</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <description>This field implements the master-detail relationship between the master Regulation object and the detail JunctionInspReg object</description>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Associated Standard Visit Items</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionInspReg object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items Regulation</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Items Regulation</label>
    <nameField>
        <displayFormat>VIR# {000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items Regulation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>FCC_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>FCC High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GSA_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>GSA High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_P_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>R&amp;P High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_InspectionItemTriggerHelper.cls
public class EEC_InspectionItemTriggerHelper{
    public static Map<Id,Inspection__c> insAccMap;
    public static Boolean flag=false;
    public static void callVisitItems(List<Inspection_Item__c> triggerNewList,Map<id,Inspection_Item__c> oldMap){
        Id stdRecordTypeId = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('Standard Visit Item').getRecordTypeId();
        Id nonRecordTypeId = Schema.SObjectType.Inspection_Item__c.getRecordTypeInfosByName().get('Non Standard Visit Item').getRecordTypeId();
        List<Inspection_Item__c> stdItems = new List<Inspection_Item__c>();
        List<Inspection_Item__c> nonItems = new List<Inspection_Item__c>();
        List<Id> insId = new List<Id>();
        
        Set<String> userNameSet = new Set<String>();
        for(Inspection_Item__c insItem : triggerNewList){
            if(insItem.Corrective_Actions_Submitter__c!=''&&insItem.Corrective_Actions_Submitter__c!=null){
                userNameSet.add(insItem.Corrective_Actions_Submitter__c);
            }
        }
        List<User> portalUsers = new List<User>();
        Set<String> portalUserNames = new Set<String>();
        portalUsers = [select id,Name,IsPortalEnabled from User where Name IN :userNameSet and IsPortalEnabled=true ];
        for(User us : portalUsers){
            portalUserNames.add(us.Name);
        }
        
        for(Inspection_Item__c  items : triggerNewList){
            if(items.Inspection_Result__c=='Non-Compliant' && (items.Correction_Plan__c==''||items.Correction_Plan__c==null)&&(items.Date_Corrective_Actions_Received__c==null)){
                items.Correction_Plan_Status__c='To Collect';
            }else if(items.Inspection_Result__c!='Non-Compliant' && items.Correction_Plan_Status__c!=null && items.Correction_Plan_Status__c!='' ){
                items.Correction_Plan_Status__c='';
            }else if(items.Inspection_Result__c=='Non-Compliant' && (items.Correction_Plan__c!=''&&items.Correction_Plan__c!=null)&&(items.Correction_Plan_Status__c!='EEC Accepted')&&(portalUserNames.contains(items.Corrective_Actions_Submitter__c))){
                items.Correction_Plan_Status__c='Provider Submitted, EEC to Review';
            }
            if(trigger.isUpdate){
                if((oldMap.get(items.id).Correction_Plan_Status__c)!='EEC Accepted'&&items.Correction_Plan_Status__c=='EEC Accepted'){
                    items.Date_Correction_Plan_Accepted__c = date.Today();
                }else if(items.Correction_Plan_Status__c!='EEC Accepted' && oldMap.get(items.id).Correction_Plan_Status__c=='EEC Accepted'){
                    items.Date_Correction_Plan_Accepted__c = null;
                }
            }
            insId.add(items.Inspection_No__c);
            if(items.RecordTypeId==stdRecordTypeId){
                stdItems.add(items);
            }
            if(items.RecordTypeId==nonRecordTypeId){
                nonItems.add(items);
            }
        
        }
        insAccMap = new Map<Id,Inspection__c>([select id,Provider_No__c,Provider_No__r.Is_FCC__c,Provider_No__r.Is_GSA__c,Provider_No__r.Is_R_P__c from Inspection__c where ID IN:insId]);
        if(!stdItems.isEmpty()){
            standardVisitItemCheckbox(stdItems);
        }
        if(!nonItems.isEmpty()){
            nonStandardVisitItemCheckbox(nonItems);
        }
    }
    public static void standardVisitItemCheckbox(List<Inspection_Item__c> triggerNewList){
        List<Id> regulation_Id = new List<Id>();
        List<Id> insItemId = new List<Id>();
        List<Id> accId = new List<Id>();
        for(Inspection_Item__c  items : triggerNewList){
            insItemId.add(items.Standard_Inspection_Item__c);
        }
        Map<Id,Standard_Inspection_Item__c> standardMap = new Map<Id,Standard_Inspection_Item__c>([select id,(select id,Regulation__c,Standard_Inspection_Item__c, Regulation__r.FCC_High_Risk_Reg__c,Regulation__r.GSA_High_Risk_Reg__c,Regulation__r.R_P_High_Risk_Reg__c  from Junction_InspRegs__r) from Standard_Inspection_Item__c where ID IN:insItemId]);
        Map<Id,Boolean> comparisonMap = new Map<Id,Boolean>();
        for(Inspection_Item__c item : triggerNewList){  
            Inspection__c ins = insAccMap.get(item.Inspection_No__c);
            for(Junction_InspReg__c reg : standardMap.get(item.Standard_Inspection_Item__c).Junction_InspRegs__r){
                if((reg.Regulation__r.FCC_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_FCC__c)){
                    item.Key_Indicator__c = true;
                }else if((reg.Regulation__r.GSA_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_GSA__c)){
                    item.Key_Indicator__c = true;
                }else if((reg.Regulation__r.R_P_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_R_P__c)){
                    item.Key_Indicator__c = true;
                }else{
                    item.Key_Indicator__c = false;
                }
            }
        }
    }
    
    public static void nonStandardVisitItemCheckbox(List<Inspection_Item__c> triggerNewList){
        List<Id> inspectionId = new List<Id>();
        List<Id> regulationId = new List<Id>();
        for(Inspection_Item__c item : triggerNewList){
            regulationId.add(item.Associated_regulation__c);
         }
        Map<Id,Regulation__c> regulationMap = new Map<Id,Regulation__c>([select id,FCC_High_Risk_Reg__c,GSA_High_Risk_Reg__c,R_P_High_Risk_Reg__c from Regulation__c where Id IN:regulationId]);
        for(Inspection_Item__c item : triggerNewList){
           Inspection__c ins = insAccMap.get(item.Inspection_No__c);
           Regulation__c reg = regulationMap.get(item.Associated_regulation__c);
            if(reg!=null && ins!=null){
                if((reg.FCC_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_FCC__c)){
                    item.Key_Indicator__c = true;
                }else if((reg.GSA_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_GSA__c)){
                    item.Key_Indicator__c = true;
                }else if((reg.R_P_High_Risk_Reg__c)&&(ins.Provider_No__r.Is_R_P__c)){
                    item.Key_Indicator__c = true;
                }else{
                    item.Key_Indicator__c = false;
                }
           }
        }
        
    }
}