src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Electronic_Communication__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, emails and documents will be sent electronically. Also, electronic signature will be required. If unchecked, all communication will be paper and the email address is not mandatory.</description>
        <inlineHelpText>If checked, emails and documents will be sent electronically. Also, electronic signature will be required.</inlineHelpText>
        <label>Electronic Communication</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>FCC</fullName>
        <active>true</active>
        <description>Family Child Care</description>
        <label>Family Child Care</label>
    </recordTypes>
    <recordTypes>
        <fullName>Umbrella</fullName>
        <active>true</active>
        <description>Umbrella</description>
        <label>Umbrella</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Checklist_Summary_issue_date__c</fullName>
        <inlineHelpText>Date the checklist summary was issued last.</inlineHelpText>
        <label>Tool Summary issue date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Narrative_Issue_Date__c</fullName>
        <inlineHelpText>Date the Visit Narrative was last issued</inlineHelpText>
        <label>Visit Narrative Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_ReportGeneration_OneExtensionTest.cls
@isTest
public class EEC_ReportGeneration_OneExtensionTest { 
  public static testmethod void testProcessNaraitiveDefault() {
    Test.startTest();
    Account provider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
      
    Inspection__c i = EEC_TestUtil.mockInspection(provider);
    //Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
	System.debug('Test Provider Id' + i.Provider_No__c);
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    //ext.processNaraitiveDefault();
    //System.assertEquals('This functionality is only available if the visit is in status "Visit Completed" or "Report to be sent to Provider"', ext.toastMsg);

    i.Status__c = 'Visit Completed';
    i.Inspector_del__c = UserInfo.getUserId();  
    update i;

    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.processNaraitiveDefault();

    Test.stopTest();
  } 
  public static testmethod void testProcessNaraitiveDefaultWithUmbrella() {
    Test.startTest();
    Account provider = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
    Account umbrella = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC');
      
    Contact director = EEC_TestUtil.mockContact(provider, 'firstName', 'lastName', 'Director');
    //Contact mainContact = EEC_TestUtil.mockContact(provider, 'firstName', 'lastName', 'Main Contact / Licensee');  
      
    umbrella.Umbrella_Members__c = provider.Id;
    update provider;  
      
    Inspection__c i = EEC_TestUtil.mockInspection(umbrella);
    //Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
	System.debug('Test Provider Id' + i.Provider_No__c);
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    //ext.processNaraitiveDefault();
    //System.assertEquals('This functionality is only available if the visit is in status "Visit Completed" or "Report to be sent to Provider"', ext.toastMsg);

    i.Status__c = 'Visit Completed';
    i.Inspector_del__c = UserInfo.getUserId();  
    update i;

    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.processNaraitiveDefault();

    Test.stopTest();
  }   
 
  public static testmethod void testGenerateAllReports() {
    Test.startTest();

    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 

    Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
    System.currentPageReference().getParameters().put('reportType', 'nc');

    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.generateAllReports();
    System.assertEquals('Report Narrative can only be generated if the Visit is Completed, and not Closed', ext.toastMsg);

    i.Status__c = 'Visit Completed';
    update i;
    
    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.generateAllReports();
    System.assertEquals('This functionality is not available for a Closed or Cancelled Visit, Visit must first be re-opened by a Supervisor or Director', ext.toastMsg);

    Test.stopTest();  
  } 
  public static testmethod void testGenerateChecklistReports() {
    Test.startTest();

    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 

    i.Status__c = 'Visit Completed';
    update i;
      
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
      
    Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
    System.currentPageReference().getParameters().put('reportType', 'checklist');
    ext.generateAllReports();
    System.assertEquals('Visit Summary generated. See Notes and Attachments to view the report.', ext.toastMsg);
  
      
    Test.stopTest();    
  }
  
  public static testmethod void testGenerateNarrativeReports() {
    Test.startTest();

    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 

    i.Status__c = 'Visit Completed';
    update i;
      
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
      
    Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
    System.currentPageReference().getParameters().put('reportType', 'narrative');
    ext.generateAllReports();
    System.assertEquals('Visit Narrative generated. See Notes and Attachments to view the report.', ext.toastMsg);
  
      
    Test.stopTest(); 
  }
    
  public static testmethod void testGenerateCoverLetterReports() {
      
    Test.startTest();

    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 

    i.Status__c = 'Visit Completed';
    update i;
      
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));  
      
    Test.setCurrentPageReference(new PageReference('EEC_ReportGeneration_One')); 
    System.currentPageReference().getParameters().put('reportType', 'coverletter');
    ext.generateAllReports();
    System.assertEquals('Cover Letter generated. See Notes and Attachments to view the report.', ext.toastMsg);
  
      
    Test.stopTest();  
      
  }  

  public static testmethod void testPublishReportOnPortal() {
    Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(),'Test User','Fake Adres 123','FCC'));
    EEC_ReportGeneration_OneExtension ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));

    Test.startTest();
    ext.publishReportOnPortal();
    System.assertEquals('This provider does not use electronic communication', ext.toastMsg);

    /*
    Account acc = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
    acc.Electronic_Communication__c = true;
    update acc;
    acc = [Select Id, Electronic_Communication__c From Account Where Id = :acc.Id];
    i = EEC_TestUtil.mockInspection(acc);
    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.publishReportOnPortal();    
    System.assertEquals('Checklist Summary or Visit Narrative has not been issued.Please generate one of these reports before publishing.', ext.toastMsg);

    i.Checklist_Summary_issue_date__c = Date.today();
    i.Visit_Narrative_Issue_Date__c = Date.today();
    update i;
    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.publishReportOnPortal();
    System.assertEquals('Visit has been published to the web.', ext.toastMsg);

    ext = new EEC_ReportGeneration_OneExtension(new ApexPages.StandardController(i));
    ext.publishReportOnPortal();
    System.assertEquals('This visit has already been published.', ext.toastMsg);
    */
  } 
}