src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <label>Preferred Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chinese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>German</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Italian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japanese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portuguese</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Non-English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arabic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Address_1__c</fullName>
        <description>Provider Address Line 1</description>
        <label>Street Address 1</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Provider_City__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Provider City</description>
        <inlineHelpText>Select a valid town / city from Massachusetts</inlineHelpText>
        <label>City</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <filterItems>
                <field>City__c.State__c</field>
                <operation>equals</operation>
                <value>MA</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>City__c</referenceTo>
        <relationshipLabel>Providers</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Provider_Status__c</fullName>
        <description>Provider.Status</description>
        <label>Provider Status</label>
        <picklist>
            <controllingField>License_Status__c</controllingField>
            <picklistValues>
                <fullName>Attended to PPM Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New application in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal in progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Region Freeze Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary Closure</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Withdrawn / Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-open in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Provider_Zip_Code__c</fullName>
        <description>Provider Address Zip Code</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Renewal_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is check by the daily Renewal batch if Expiration Date of the license is in 120 days. When checked, it&apos;ll trigger a workflow that sends emails / reminders</description>
        <label>Start Renewal Workflow</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/EEC_BatchFCCLicenseRenewalTest.cls
/**
 * EEC_CorrectionActionSchedulerTest
 * 
 * This class will contain all the test methods for the EEC_BatchFCCLicenseRenewal class.
 * @author Madhav Kuchimanchi
 */

@isTest
private class EEC_BatchFCCLicenseRenewalTest {   
   
   
  static testMethod void testscenario1() {
         String query ='Select Id,Start_Renewal_Workflow__c,Renewal_date__c,License_Status__c,OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                        ' and Recordtype.Name = \'Family Child Care\'  ';                       

          Account acc1 = new Account();          
          Date cDate =  System.today();  
          // Scenario 1 : Renewal Application Not Submitted - 30 days prior to  expiration notice
          acc1.Name = 'Test account 1 ';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = 'a0Ej0000002fMa2';
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Start_Renewal_Workflow__c = false;
          acc1.Renewal_date__c = cdate +30; 
          //acclist.add(acc1);
          insert acc1;       
          Account acc = new Account();
          acc = [Select Id,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where id = :acc1.id];
                                
          Test.startTest(); 
             EEC_BatchFCCLicenseRenewal sfbatchSync = new EEC_BatchFCCLicenseRenewal(query);
             ID batchprocessid = Database.executeBatch(sfbatchSync);
          Test.stopTest();
             AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                    FROM AsyncApexJob WHERE Id =:batchprocessid];
                //assert for total number of errors
            System.assertEquals(job.NumberOfErrors, 0);            
            Task task1 = new Task();
            Date tdate = Date.today().addDays(5);
            task1 = [select id ,Subject,ActivityDate from Task where WhatId = :acc.id limit 1];
            System.assertEquals(task1.Subject,'Renewal Application Not Submitted - 30 days prior expiration notice');
            System.assertEquals(task1.ActivityDate,tdate);                   
            
         }   
       
       //Scenario 2:Renewal Application Not Submitted - On expiration date notice
         static testMethod void testscenario2() {
         String query ='Select Id,Start_Renewal_Workflow__c,License_Status__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                        ' and Recordtype.Name = \'Family Child Care\'  ';
          Account acc1 = new Account();          
          Date cDate =  System.today();  
          
          
          acc1.Name = 'Test account 2 ';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = 'a0Ej0000002fMa2';
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Start_Renewal_Workflow__c = false;
          acc1.Renewal_date__c = cdate;
          insert acc1;       
          Account acc = new Account();
          acc = [Select Id,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where id = :acc1.id];
          Test.startTest(); 
             EEC_BatchFCCLicenseRenewal sfbatchSync = new EEC_BatchFCCLicenseRenewal(query);
             ID batchprocessid = Database.executeBatch(sfbatchSync);
          Test.stopTest();
             AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                    FROM AsyncApexJob WHERE Id =:batchprocessid];
                //assert for total number of errors
            System.assertEquals(job.NumberOfErrors, 0);            
            Task task = new Task();
            Date tdate = Date.today().addDays(2);
            task = [select id ,Subject,ActivityDate from Task where WhatId = :acc.id limit 1];
            System.assertEquals(task.Subject,'Renewal Application Not Submitted - On expiration date notice');
            System.assertEquals(task.ActivityDate,tdate);                   
       }
        
          //Scenario 3:Renewal Application Not Submitted - 30 days after expiration notice
       static testMethod void testscenario3() {
         String query ='Select Id,Start_Renewal_Workflow__c,License_Status__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                        ' and Recordtype.Name = \'Family Child Care\'  ';
          Account acc1 = new Account();          
          Date cDate =  System.today();  
       
          acc1.Name = 'Test account 3';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = 'a0Ej0000002fMa2';
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Start_Renewal_Workflow__c = false;
          acc1.Provider_Status__c = 'Region Freeze Enrollment';
          acc1.Renewal_date__c = cdate -30; 
          insert acc1;       
          Account acc = new Account();
          acc = [Select Id,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where id = :acc1.id];
          Test.startTest(); 
             EEC_BatchFCCLicenseRenewal sfbatchSync = new EEC_BatchFCCLicenseRenewal(query);
             ID batchprocessid = Database.executeBatch(sfbatchSync);
          Test.stopTest();
          AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                               FROM AsyncApexJob WHERE Id =:batchprocessid];
                //assert for total number of errors
          System.assertEquals(job.NumberOfErrors, 0);            
          Task task = new Task();
          Date tdate = Date.today().addDays(2);
          task = [select id ,Subject,ActivityDate from Task where WhatId = :acc.id limit 1];
          System.assertEquals(task.Subject,'Renewal Application Not Submitted - 30 days after expiration notice');
          System.assertEquals(task.ActivityDate,tdate);                   
      }
          
          
          
     
      //Scenario 3:Renewal Application Not Submitted - 30 days after expiration notice
       static testMethod void testscenario4() {
         String query ='Select Id,License_Status__c,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where License_Status__c = \'Licensed\' ' +
                        ' and Recordtype.Name = \'Family Child Care\'  ';
          Account acc1 = new Account();          
          Date cDate =  System.today();  
       
          acc1.Name = 'Test account 4';
          acc1.License_Status__c = 'Licensed';
          acc1.Provider_Status__c = 'Current';
          acc1.Provider_Email__c ='test@incapsulate.com';
          acc1.RecordTypeId = [select Id from RecordType where Name = 'Family Child Care' and SobjectType = 'Account'].Id;
          acc1.Provider_Address_1__c = 'Test address';
          acc1.Provider_City__c = 'a0Ej0000002fMa2';
          acc1.Provider_Zip_Code__c = '99999';
          acc1.Language__c = 'English';
          acc1.Preferred_Language__c = 'English';
          acc1.Start_Renewal_Workflow__c = false;
          acc1.Provider_Status__c = 'Current';
          acc1.Renewal_date__c = cdate +10; 
          insert acc1;
          Test.startTest(); 
             EEC_BatchFCCLicenseRenewal sfbatchSync = new EEC_BatchFCCLicenseRenewal(query);
             ID batchprocessid = Database.executeBatch(sfbatchSync);
          Test.stopTest();         
          
          Account acc = new Account();
          acc = [Select Id,Start_Renewal_Workflow__c,Renewal_date__c,OwnerId,Provider_Status__c from Account  where id = :acc1.id];          
          AsyncApexJob job  = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                    FROM AsyncApexJob WHERE Id =:batchprocessid];
                //assert for total number of errors
            System.assertEquals(job.NumberOfErrors, 0);            
                                 
      
    }
}