src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider Number.  Begins with &quot;8&quot; for licensed Providers and &quot;5&quot; for unlicensed Providers</description>
        <externalId>true</externalId>
        <label>Legacy System Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Umbrella_Members__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field implements a Look Up relationship to create a self relationship in order for the Umbrella record type to display an Umbrella Members related list to display all Providers within the Umbrella</description>
        <label>Umbrella</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected umbrella must be an umbrella record type</errorMessage>
            <filterItems>
                <field>Account.Record_Type_Name__c</field>
                <operation>contains</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Umbrella Members</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_TestGenerateVisitNarrativeExtension.cls
@isTest
public with sharing class EEC_TestGenerateVisitNarrativeExtension {

    @isTest static void testGetCompliantWithObservations(){
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null, 'My observation'); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null, null); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null, 'test'); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null, 'test 2'); 
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getCompliantWithObservations();
        
        System.assertEquals(2, l.size());
    }

    @isTest static void testGetProgramDirectorContactValid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()); 
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        Contact c = EEC_TestUtil.mockDirectorContact(pa);
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, pa);
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getDirectorContact();
        
        System.assertEquals(c.FirstName, result.FirstName);
        System.assertEquals(c.Id, result.Id);
    }

    @isTest static void testGetProgramDirectorContactInvalid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());  
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c,Mater_Visit_for_Res_Cluster_of_Visits__c FROM Inspection__c WHERE Id = :i.Id];
         
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getDirectorContact();
        
        List<Inspection__c> insp = ext.getChildVisits();
        
        System.assertEquals(null, result ); 
    }


    @isTest static void testGetExecutiveDirectorContactValid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        Account ca = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity(), pa);
         
        Inspection__c i = EEC_TestUtil.mockInspection(ca);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        System.debug('-----Inspection__c: ' + i);
        
        Contact c = EEC_TestUtil.mockContact();
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, pa);
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        System.debug('Ext: ' + ext);
        Contact result = ext.getExecutiveDirectorContact();
        
        //System.assertEquals(c.FirstName, result.FirstName);
        //System.assertEquals(c.Id, result.Id);
    }

    @isTest static void testGetExecutiveDirectorContactInvalid(){ 
        Account pa = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()); 
         
        Inspection__c i = EEC_TestUtil.mockInspection(pa);
        
        i = [SELECT Provider_No__r.Umbrella_Members__c FROM Inspection__c WHERE Id = :i.Id];
        
        Contact c = EEC_TestUtil.mockContact();
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, pa);
        EEC_GenerateVisitNarrativePDFExtension ext = new EEC_GenerateVisitNarrativePDFExtension(new ApexPages.StandardController(i));
        Contact result = ext.getExecutiveDirectorContact();
        
        System.assertEquals(null, result);
    }
}