src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Licensee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Main Contact / Assistant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_additional__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Outdoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review of Written Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sleep, Rest, Quiet Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff and Educators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toileting / Diapering / Handwashing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Safety</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_standard__c</fullName>
        <description>Category of the inspection items</description>
        <formula>text(Standard_Inspection_Item__r.Category__c)</formula>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_Item_Name__c</fullName>
        <formula>Standard_Inspection_Item__r.Name</formula>
        <label>Visit Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Assistance__c</fullName>
        <label>Technical Assistance</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Visit_Mode_Ranking__c</fullName>
        <inlineHelpText>Allows you to sort visit items as they will be displayed in visit mode and on visit summary. Lowest ranking will be displayed first. Ranking should be set for each item. Items with empty rank will be displayed last.</inlineHelpText>
        <label>Visit Mode Ranking</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Junction_InspReg__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Visit Items and Regulations objects</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <description>This field implements the master-detail relationship between the master Regulation object and the detail JunctionInspReg object</description>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Associated Standard Visit Items</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionInspReg object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items Regulation</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Items Regulation</label>
    <nameField>
        <displayFormat>VIR# {000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items Regulation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_GeneratePDFBase.cls
public abstract with sharing class EEC_GeneratePDFBase {
    
    protected final Inspection__c visit;

    public EEC_GeneratePDFBase(ApexPages.StandardController stdController) {
        this.visit = (Inspection__c) stdController.getRecord();
    }  
    
    public class VisitChecklistItemWrapper {
        public Inspection_Item__c inspectionItem { get; set; }
        public String standardRegulations { get; set; }
        
        public VisitChecklistItemWrapper(Inspection_Item__c inspItem, String regs) {
            this.inspectionItem = inspItem;
            this.standardRegulations = regs;
        }
    } 
    
    private static Map<ID, Standard_Inspection_Item__c> standardInspectionItems = new Map<ID, Standard_Inspection_Item__c>([
            SELECT Id, (SELECT Regulation__r.Name FROM Junction_InspRegs__r) 
            FROM Standard_Inspection_Item__c]);
            
    public static List<VisitChecklistItemWrapper> augmentStandardInspectionItems(List<Inspection_Item__c> rows) { 
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper > items = new List<EEC_GeneratePDFBase.VisitChecklistItemWrapper>();
        
        for(Inspection_Item__c row : rows){ 
            String regs = '';
            
            if(row.Standard_Inspection_Item__c != null){
                Standard_Inspection_Item__c sii = standardInspectionItems.get(row.Standard_Inspection_Item__c); 
                    
                for(Junction_InspReg__c jir : sii.Junction_InspRegs__r){
                    if(regs != ''){
                        regs += ', ';
                    }
                
                    regs += jir.Regulation__r.Name;
                }
            }
            
            items.add(new VisitChecklistItemWrapper (row, regs));
        }
            
        return items;
    } 

    public Boolean getHasNonCompliant(){
        List<Inspection_Item__c> rows = [
            SELECT Associated_regulation__r.Name, Standard_Inspection_Item__c, Inspection_Item_Name__c, Standard_Inspection_Item__r.Description__c, 
            Additional_Inspection_Item_Name__c , Category_standard__c, Observations__c, Category_additional__c 
            FROM Inspection_Item__c
            WHERE Inspection_No__c = :visit.Id AND Inspection_Result__c = 'Non-Compliant'];
        
        return rows.size() > 0;    
    }
    
    
    public Contact getDirectorContact() {
        List<Contact> acrs = [
            SELECT Salutation, FirstName, LastName 
            FROM Contact 
            WHERE AccountID = :visit.Provider_No__c AND Role__c = 'Director' 
            ORDER BY CreatedDate DESC 
            LIMIT 1
        ];
        
        if(acrs.size() > 0) {
            return acrs.get(0);
        }
        else{
        	List<Contact> acrs1 = [
            SELECT Salutation, FirstName, Contact.LastName 
            FROM Contact 
            WHERE AccountID = :visit.Provider_No__c AND Role__c like 'Main Contact%' 
            ORDER BY CreatedDate DESC 
            LIMIT 1];
            if(acrs1.size() > 0) {
            	return acrs1.get(0);
            }
        }
        return null;
    }
    
    public List<VisitChecklistItemWrapper > getAdditionalInspectionItems(){
      List<Inspection_Item__c> rows = new List<Inspection_Item__c>();
      // Get the Master objects records.
      for(Inspection_Item__c ii : [SELECT Associated_regulation__r.Name, Standard_Inspection_Item__c, Inspection_Item_Name__c, Standard_Inspection_Item__r.Description__c, 
        Additional_Inspection_Item_Name__c , Technical_Assistance__c,Visit_Mode_Ranking__c,  Category_additional__c 
        FROM Inspection_Item__c
        WHERE Inspection_No__c = :visit.Id order by Visit_Mode_Ranking__c asc nulls last]){
        if(String.isNotBlank(ii.Technical_Assistance__c)){
      	  rows.add(ii);
       	}
      }
      // Check for a child and retrieve all the records if they exist.
      if (visit.Mater_Visit_for_Res_Cluster_of_Visits__c == null) {
        // Get all the children ids.
        List<Inspection__c> lstInsp = [Select Id From Inspection__c Where Mater_Visit_for_Res_Cluster_of_Visits__c = :visit.Id];
        Set<Id> childIds = new Set<Id>();
        for(Inspection__c insp : lstInsp){
              childIds.add(insp.Id);
        }  
        //Set<Id> childIds = new Map<Id, Inspection__c>([Select Id From Inspection__c Where Mater_Visit_for_Res_Cluster_of_Visits__c = :visit.Id]).keySet();
        for(Inspection_Item__c ii : [SELECT Associated_regulation__r.Name, Standard_Inspection_Item__c, Inspection_Item_Name__c, Standard_Inspection_Item__r.Description__c, 
          Additional_Inspection_Item_Name__c , Technical_Assistance__c,  Category_additional__c 
          FROM Inspection_Item__c
          WHERE Inspection_No__c IN :childIds]){
                
          if(String.isNotBlank(ii.Technical_Assistance__c)){
            rows.add(ii);
          }
        }      
      }
      return augmentStandardInspectionItems(rows);
    }
 
}