src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Additional_EEC_Staff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Additional EEC Licensor or staff that will be present or was present during the visit. This information will appear in Visit Summary</inlineHelpText>
        <label>Additional EEC Staff</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Additional_Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assigned_To_Id__c</fullName>
        <formula>Inspector_del__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned To Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offline_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag checked when the visit has been downloaded to be used on the offline app. Edits to such visit are not authorized</inlineHelpText>
        <label>Offline Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Inspection record</description>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Mode_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag checked when the visit mode is accessed by a user and remains locked for other users until its released or unlocked by the user.</description>
        <inlineHelpText>This flag checked when the visit mode is accessed by a user and remains locked for other users until its released or unlocked by the user.</inlineHelpText>
        <label>Visit Mode Lock</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_MassTransferVisitsExtension.cls
public with sharing class EEC_MassTransferVisitsExtension {
	public List<User> transferToUserList { get; set;}
	public List<Inspection__c> visitsSelected { get; set;}
	public User transferToUserSelected { get; set;}
	public List<SelectOption> transferToOptionsDisplay {get; set;}
	public String selectedUserId {get; set;}
	public String selectedAdditionalStaff {get; set;}
	public Boolean transferAllowed {get; set;}
	public String visitObjectId {get; set;}
	ApexPages.StandardSetController setCon;

	public EEC_MassTransferVisitsExtension(ApexPages.StandardSetController controller) {
		setCon = controller;
		selectedUserId = null;
		selectedAdditionalStaff = null;
		transferAllowed = true;
		//Get 3 digit object key to navaigate back to visits tab.
		Schema.DescribeSObjectResult dsr = Inspection__c.sObjectType.getDescribe();
		visitObjectId = dsr.getKeyPrefix();
		//Verify if user has appropriate role to proceed with mass transfer.
		List<String> allowedRoles = new List<String>{'Executive and Directors', 'Program Supervisor', 'Regional Director'};
		Set<ID> allowedRoleIdSet = (new Map<Id, UserRole>([Select id, Name From UserRole Where Name IN :allowedRoles])).keySet();
		if(!allowedRoleIdSet.contains(UserInfo.getUserRoleId())){
			transferAllowed = false;
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'You are not authorized to use this feeature. Please contact your supervisor.'));
			return;
		}
		//Get the list of visits selected from the list view
		Set<id> visitsSelectedIds = (new Map<Id, Inspection__c>((Inspection__c[])setCon.getSelected())).keySet();
		//Excluding visits that are locked by offline app or visit mode as it means they are in progress.
		visitsSelected = [SELECT ID, Name, Assigned_To_Id__c, Additional_EEC_Staff__c, Provider_No__c
												, Status__c,  Offline_Lock__c, Visit_Mode_Lock__c
											FROM Inspection__c 
											WHERE ID IN :visitsSelectedIds];
		//Build list of user id's that need to be excluded from the list of transfer to user options
		Set<Id> transferFromUserIds = new Set<Id>();
		for(Inspection__c v : visitsSelected){
			if( (v.Status__c != 'Scheduled' && v.Status__c != 'To be scheduled') || v.Offline_Lock__c || v.Visit_Mode_Lock__c){
				transferAllowed = false;
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Visits that are completed or locked can not be transferred. Please update your selection.'));
				break;
			}
			transferFromUserIds.add(v.Assigned_To_Id__c);
		}

		transferToUserList = [SELECT ID, Name, UserRole.Name, UserType, Username 
													FROM User 
													WHERE UserType = 'Standard' AND isActive = true 
														AND ID NOT IN :transferFromUserIds
														AND UserRole.Name NOT IN ('Admin', 'Executive and Directors', ''
														, 'Program Supervisor', 'Regional Director')];
		transferToOptionsDisplay = new List<SelectOption>();
		transferToOptionsDisplay.add(new SelectOption('select', 'Select...'));
		for(User u : transferToUserList){
			transferToOptionsDisplay.add(new SelectOption(u.id, u.Name));
		}
	}
	public pageReference massTransferVisits(){
		List<Inspection__c> visitToBeUpdate = new List<Inspection__c>();
		if(selectedUserId == 'select' && selectedAdditionalStaff == 'select'){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please make a selection.'));
			return null;
		}
		for(Inspection__c visit : visitsSelected){
			if(selectedUserId != 'select'){
				visit.Inspector_del__c = selectedUserId;
			}
			if(selectedAdditionalStaff != 'select'){
				visit.Additional_EEC_Staff__c = selectedAdditionalStaff;
			}
			visitToBeUpdate.Add(visit);
		}
		Update visitToBeUpdate;
		//Update open activities if "Assign To" field is updated
		if(selectedUserId != 'select'){
			Set<Id> visitIdSet = (new Map<Id, Inspection__c>(visitToBeUpdate)).keySet();
			List<Task> tasksOpen = [SELECT ID, Status, OwnerId, WhatID 
																			FROM Task 
																			WHERE WhatId IN :visitIdSet AND Status != 'Completed'];
			List<Task> tasksToBeUpdated = new List<Task>();
			for(Task t : tasksOpen){
				t.OwnerId = selectedUserId;
				tasksToBeUpdated.add(t);
			}
			Update tasksToBeUpdated;
		}
		PageReference pageRef = new PageReference('/' + visitObjectId);
		return pageRef;
	}
	public pageReference goBackToVisitsTab(){
		PageReference pageRef = new PageReference('/' + visitObjectId);
		return pageRef;
	}
}