src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/EEC_HistoryOfNonComplianceStaging__c.object
<CustomObject>
    <description>Staging object used to load historic Non Compliance Data into target objects Visits/Visit Items  or Investigation/Additional non-compliance</description>
    <fields>
        <fullName>Citation__c</fullName>
        <label>Citation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CorrectionPlan__c</fullName>
        <label>CorrectionPlan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DuplicateRule1__c</fullName>
        <description>ProgramId + InteractionId + InteractionTypeDesc</description>
        <formula>ProgramId__c + &apos;|&apos; + InteractionId__c + &apos;|&apos; + InteractionTypeDesc__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DuplicateRule1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ErrorText2__c</fullName>
        <description>Error text for VisitItem failure</description>
        <label>ErrorText2</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InteractionDate__c</fullName>
        <label>Interaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InteractionId__c</fullName>
        <label>InteractionId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InteractionTypeDesc__c</fullName>
        <label>InteractionTypeDesc</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <label>InvestigationType</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LicensorOfInteraction__c</fullName>
        <label>LicensorOfInteraction</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProgramId__c</fullName>
        <label>ProgramId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisitItem_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VisitItem Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Visit_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visit Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>HistoryOfNonComplianceStaging</label>
    <nameField>
        <displayFormat>NC-{000000}</displayFormat>
        <label>HistoryOfNonComplianceNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoryOfNonComplianceStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_Batch_ProcessLegacyNonCompVisitItems.cls
//Author - Latha Davuluri
//Batch job to process Legacy Non-Compliance Visit Items for the Visits created PART2 - LEAD-4299
	
global class EEC_Batch_ProcessLegacyNonCompVisitItems implements Database.Batchable<sObject>{

    global List<EEC_HistoryOfNonComplianceStaging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, Name, ProgramId__c,VisitItem_Processed__c, ErrorText2__c, InvestigationType__c, Observations__c, LicensorOfInteraction__c, InteractionTypeDesc__c,InteractionDate__c, InteractionId__c, CorrectionPlan__c, Citation__c, DuplicateRule1__c FROM EEC_HistoryOfNonComplianceStaging__c WHERE VisitItem_Processed__c = false and Visit_Processed__c = true]);
        
    }

    global void execute(Database.BatchableContext BC,List<EEC_HistoryOfNonComplianceStaging__c> scope){
    	
        dataListSize = scope;
        
        for(EEC_HistoryOfNonComplianceStaging__c v : scope){
        	try{
        		if(String.isNotBlank(v.InvestigationType__c)){
        			EEC_ProcessLegacyVisitData.processLegacyInvestigationAddionalNonComplianceItems(v);
        		} else {
        			EEC_ProcessLegacyVisitData.processLegacyNonComplianceVisitItems(v);
        		}
            v.VisitItem_Processed__c = true;  
      		}
        	catch(exception ex){
        		string errText = ex.getMessage();
        		v.ErrorText2__c = ex.getMessage();      		
          }
        }
        update scope; 
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyNonCompVisitItems'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyNonCompVisitItems batchLegacyNonCompVisitItems = new EEC_Batch_ProcessLegacyNonCompVisitItems();   
			        Id batchProcessId = Database.executeBatch(batchLegacyNonCompVisitItems,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyNonCompVisitItems batchLegacyNonCompVisitItems = new EEC_Batch_ProcessLegacyNonCompVisitItems();   
			             Id batchProcessId = Database.executeBatch(batchLegacyNonCompVisitItems,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyNonCompVisitItems'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyNonCompVisitItems job: ' + ex.getMessage());
    	}
    }

}