src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/EEC_HistoricalVisitItemStaging__c.object
<CustomObject>
    <description>Staging table used to load historic Visit Item Data into target object &apos;visit Items&apos;</description>
    <fields>
        <fullName>EEC_Comment__c</fullName>
        <label>Comment</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EEC_ComplianceStatusDesc__c</fullName>
        <label>ComplianceStatusDesc</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_ErrorText__c</fullName>
        <label>ErrorText</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_HeaderVisitItem__c</fullName>
        <formula>EEC_VisitHeaderId__c + &apos;|&apos; + EEC_Hostname__c + &apos;|&apos; +  EEC_VisitDetailId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HeaderVisitItem</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_HeaderVisit__c</fullName>
        <formula>EEC_VisitHeaderId__c + &apos;|&apos; + EEC_Hostname__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HeaderVisit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_RegGroupItemDesc__c</fullName>
        <label>RegGroupItemDesc</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_RegGroupItem__c</fullName>
        <label>RegGroupItem</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_VisitDetailId__c</fullName>
        <label>VisitDetailId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EEC_VisitItem_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visit Item Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>HistoricalVisitItemStaging</label>
    <nameField>
        <displayFormat>LVI-{0000}</displayFormat>
        <label>VisitItemStagingId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricalVisitItemStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_Batch_ProcessLegacyVisitItems.cls
//Author - Latha Davuluri
//Batch job to process Legacy Visits - LEAD-4231 & LEAD-4298

global class EEC_Batch_ProcessLegacyVisitItems implements Database.Batchable<sObject>{

    global List<EEC_HistoricalVisitItemStaging__c> dataListSize = null;
      
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([SELECT Id, EEC_HeaderVisit__c, EEC_HeaderVisitItem__c, EEC_Comment__c, EEC_VisitDetailId__c, EEC_RegGroupItem__c, EEC_RegGroupItemDesc__c, EEC_ComplianceStatusDesc__c, EEC_VisitItem_Processed__c  FROM EEC_HistoricalVisitItemStaging__c WHERE EEC_VisitItem_Processed__c = false]);
        
    }

    global void execute(Database.BatchableContext BC,List<EEC_HistoricalVisitItemStaging__c> scope){
    	
        dataListSize = scope;
        
        for(EEC_HistoricalVisitItemStaging__c vi : scope){
        	try{
        	   EEC_ProcessLegacyVisitData.processLegacyVisitItems(vi);
               vi.EEC_VisitItem_Processed__c = true;  
             }
        	catch(exception ex){
        		string errText = ex.getMessage();
        		if (errText.contains('List has no rows for assignment to SObject')){
        	        vi.EEC_ErrorText__c = 'Visit Not Found in LEAD';
        		}
        		else{
        			vi.EEC_ErrorText__c = ex.getMessage();
        		}
        		
        	}
        	           
        }
       
        update scope; 
        
    }

    global void finish(Database.BatchableContext BC){
    	
    	try{
	    	if(dataListSize != null){
		    	AsyncApexJob batchJob = [Select Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email from AsyncApexJob where Id =:BC.getJobId()];
	       
		        Integer jobs = [Select count() From AsyncApexJob Where JobType = 'BatchApex' and ( Status = 'Queued' or Status = 'Processing' or Status = 'Preparing' )];   
		        
		        if(jobs <= 1){
		            EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyVisitItems'); 
		        }
		
		        //If NumberOfErrors is "0" - if the execute method processed all records without errors - then call next contact batch.
			    if (batchJob.NumberOfErrors == 0)
			    {     
			        EEC_Batch_ProcessLegacyVisitItems batchLegacyVisitItems = new EEC_Batch_ProcessLegacyVisitItems();   
			        Id batchProcessId = Database.executeBatch(batchLegacyVisitItems,1);    //finish method logic here
			    }
			    else
			    {
			        //process other code
			        if ((batchJob.NumberOfErrors == 0) && (jobs < 5)){
		
		        		 EEC_Batch_ProcessLegacyVisitItems batchLegacyVisitItems = new EEC_Batch_ProcessLegacyVisitItems();   
			             Id batchProcessId = Database.executeBatch(batchLegacyVisitItems,1);    //finish method logic here
		         		}
		        	else{
		         		//wait for 1 hour
		          	}
			    }
	         }
	         else{
	         	EEC_Util.batchEmailSuccess(bc, 'EEC_Batch_ProcessLegacyVisitItems'); 
	         }
    	}
    	catch(exception ex){
    		System.debug('----> Error Processing the EEC_Batch_ProcessLegacyVisitItems job: ' + ex.getMessage());
    	}
    }

}