src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Region__c</fullName>
        <formula>Provider_No__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLatitude__c</fullName>
        <description>Latitude part of geo-coordinates of the visit address</description>
        <label>visitLatitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLongitude__c</fullName>
        <description>Longitude part of geo-coordinates of the visit address</description>
        <label>visitLongitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <description>This object is used to define EEC Region</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the user is attached to</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metro Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast and Cape</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_ShowMapsControllerTest.cls
@isTest
private class EEC_ShowMapsControllerTest {

    static testMethod void testEEC_ShowMapsController() {
        
        Profile p = [SELECT ID FROM Profile WHERE Name = 'System Administrator'];
        User u = new User(
            Email = 'test@test.com',
            LastName = 'TestF',
            FirstName = 'TestL',
            Username = 'test123@test91.com',
            Alias = 'tst',
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            ProfileID = p.Id,
            LanguageLocaleKey = 'en_US',
            ManagerId = Userinfo.getUserId(),
            Region__c = 'Central'
        );
        insert u;
        	
        	Inspection__c insp = EEC_TestUtil.loadInspectionSetup();
            insp.visitLatitude__c = '14.7788888';
            insp.visitLongitude__c = '-3.766676757575';
	        EEC_ShowMapsController controller = new EEC_ShowMapsController();
	        // Assert that values have been set by the constructor.
	        System.assertNotEquals(null, controller.userId);
	        System.assertNotEquals(null, controller.inspWrapperList);
	        // Instantiate the inner class.
	        EEC_ShowMapsController.InspectionWrapper inspWrap = new EEC_ShowMapsController.InspectionWrapper(insp);
	        System.assertNotEquals(null, inspWrap.Id);
	        System.assertNotEquals(null, inspWrap.content);
	        //System.assertNotEquals(null, inspWrap.announced);
	        System.assertNotEquals(null, inspWrap.providerAddress);
	        System.assertNotEquals(null, inspWrap.visitLink);
	        System.assertNotEquals(null, inspWrap.status);
    }
}