src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Items_with_Corrective_Actions__c</fullName>
        <label>Number of Items with Corrective Actions</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Inspection_Item__c.Date_Implemented__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_non_compliant_items__c</fullName>
        <description>Provide the number of non-compliant items from an inspection</description>
        <label>Number of Non-Compliant items</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Require_Portal_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for Licensor/Investigator to specify if a feedback is to be sent to the Provider via email to request a review of non-compliance items</description>
        <inlineHelpText>Check this field if an email is required to be sent to the Provider to request a review of non-compliant items</inlineHelpText>
        <label>Require Portal Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan_Status__c</fullName>
        <label>Correction Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Collect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Provider To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider Submitted, EEC to Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EEC Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy Non-compliance</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <description>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</description>
        <inlineHelpText>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_History_Record_flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create History Record flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Correction_Plan_Accepted__c</fullName>
        <label>Date Correction Plan Accepted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND( ISBLANK( Date_Implemented__c ),  NOT(Investigation__r.isLegacyInvestigation__c) )</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Date of the last update of corrective action feedback</inlineHelpText>
        <label>Last Corrective Action EEC Feedback</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Require_Portal_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, it means that the report was published on the web and the investigation has non-compliance items that needs to be filled by the provider</inlineHelpText>
        <label>Require Portal Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_History__c.object
<CustomObject>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Corrective_Action_EEC_Feedback__c</fullName>
        <label>Last Corrective Action EEC Feedback</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Non_Compliant_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Non Compliant Item</label>
        <referenceTo>Non_Compliant__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit Item</label>
        <referenceTo>Inspection_Item__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission History</label>
    <nameField>
        <displayFormat>SH# {00000}</displayFormat>
        <label>Submission History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_NonComplaintItemTriggerHandler.cls
public with sharing class EEC_NonComplaintItemTriggerHandler {
    private List<Non_Compliant__c> noncompitems = new List<Non_Compliant__c>();
    private Map<Id,Non_Compliant__c> oldnoncompMap = new Map<Id,Non_Compliant__c>();
    public EEC_NonComplaintItemTriggerHandler(List<Non_Compliant__c> newList,Map<Id,Non_Compliant__c> oldMap){
        this.noncompitems = newlist;
        this.oldnoncompMap = oldMap;
    } 
    
    
    public void updateRequireFeedback(){        
        Set<id> invids = new Set<Id>();
        Non_Compliant__c oldnc;
        for(Non_Compliant__c i : noncompitems){ 
            oldnc = oldnoncompMap.get(i.Id); 
            if (oldnc.Feedback_Requested__c != i.Feedback_Requested__c){  
                invids.add(i.Investigation__c);        
            }
        }

       
 //      Map<Id, Investigation__c> invsMap = new Map<Id,Investigation__c>([select Id from Investigation__c where Id in :invids and Created_on_the_Web__c = true]);
         List<Investigation__c> invglist = new List<Investigation__c>([select Id,(select Id from Non_Compliant_Item__r where Feedback_Requested__c = true) from Investigation__c where Id in :invids and Created_on_the_Web__c = true]);
         Set<id> invid2 = new Set<Id>();
         for(Investigation__c inv: invglist){
            if((inv.Non_Compliant_Item__r == null) || (inv.Non_Compliant_Item__r != null && inv.Non_Compliant_Item__r.size() == 0)){
                invid2.add(inv.Id);
            }
         }     
         if(invid2 !=null && invids.size() > 0){
           List<Inspection__c> visitlist = new List<Inspection__c>([ select Investigation__c,Number_of_Items_with_Corrective_Actions__c,Number_of_non_compliant_items__c from Inspection__c where Investigation__c in :invid2]);
           Set<Id> invid3 = new Set<Id>();
           System.debug('visitlist ' + visitlist);
           if (visitlist != null && visitlist.size() > 0){
               
              for(Inspection__c insp : visitlist){
                 System.debug('Final update -->' + insp.Number_of_Items_with_Corrective_Actions__c);
                 System.debug('Final update -->' + insp.Number_of_non_compliant_items__c);
                 if (insp.Number_of_Items_with_Corrective_Actions__c >= insp.Number_of_non_compliant_items__c){
                     invid3.add(insp.Investigation__c);
                 }
              }
           }              
            List<Investigation__c> invslist = new List<Investigation__c>([select Require_Portal_Feedback__c from Investigation__c where Id in :invid3 and Require_Portal_Feedback__c = true]);
            List<Investigation__c> updatelist = new List<Investigation__c>();
            if (invslist.size() > 0){
            
               for (Investigation__c inv : invslist){
                   System.debug('Final update -->' + inv.Require_Portal_Feedback__c);
                   if(inv.Require_Portal_Feedback__c){ //Mod by LD - Fix for BMMS-227
                      inv.Require_Portal_Feedback__c = false;
                      updatelist.add(inv);
                   }
               }
            
               if (updatelist != null && updatelist.size() > 0){
                  System.debug('Final update -->');
                  update updatelist;
               }
            }
        } 
        
    }
    public void Submissionhistory(){
        list<Submission_History__c> SHlist = new list<Submission_History__c>();
        list<Non_Compliant__c> NClist = new list<Non_Compliant__c>();
        for(Non_Compliant__c NC : noncompitems){
            if(NC.Create_History_Record_flag__c == true && oldnoncompMap.get(NC.id).Create_History_Record_flag__c==false){
                Submission_History__c SH = new Submission_History__c();
                //SH.Visit_Item__c = NC.id;
                SH.Non_Compliant_Item__c=NC.id;
                SH.RecordTypeId = [select Id from RecordType where Name = 'NC Item Corrective Action Plan Submission History' and SobjectType = 'Submission_History__c'].Id;
                system.debug('MMM'+SH.Visit_Item__c);
                //SH.Visit__c = NC.Inspection_No__c;
                SH.Investigation__c=NC.Investigation__c;
                SH.Correction_Plan__c = NC.Correction_Plan__c;
                SH.Corrective_Actions_Submitter__c = NC.Corrective_Actions_Submitter__c;
                SH.Date_Implemented__c= NC.Date_Implemented__c;
                SH.Date_Corrective_Actions_Received__c= NC.Date_Corrective_Actions_Received__c;
                SH.Corrective_Action_EEC_Feedback__c= NC.Corrective_Action_EEC_Feedback__c;
                SH.Last_Corrective_Action_EEC_Feedback__c=NC.Last_Corrective_Action_EEC_Feedback__c;
                SHlist.add(SH);
                Non_Compliant__c Nonc = new Non_Compliant__c(ID=NC.id);
                NonC.Create_History_Record_flag__c=false;
                NCList.add(NonC);
            }
        }
    if(SHlist.size()>0){
        insert SHlist;
        Update NCList;
    }   
    }
    
    public void updateStatus(){
        Set<String> userNameSet = new Set<String>();
        for(Non_Compliant__c nonComp : noncompitems){
            if(nonComp.Corrective_Actions_Submitter__c!=''&&nonComp.Corrective_Actions_Submitter__c!=null){
                userNameSet.add(nonComp.Corrective_Actions_Submitter__c);
            }
        }
        List<User> portalUsers = new List<User>();
        Set<String> portalUserNames = new Set<String>();
        portalUsers = [select id,Name,IsPortalEnabled from User where Name IN :userNameSet and IsPortalEnabled=true];
        for(User us : portalUsers){
            portalUserNames.add(us.Name);
        }
        for(Non_Compliant__c nonComp : noncompitems){
            if((nonComp.Correction_Plan__c==''||nonComp.Correction_Plan__c==null)&&nonComp.Date_Corrective_Actions_Received__c==null){
                nonComp.Correction_Plan_Status__c='To Collect';
            }else if((nonComp.Correction_Plan__c!=''&&nonComp.Correction_Plan__c!=null)&&nonComp.Date_Corrective_Actions_Received__c!=null&&(!portalUserNames.contains(nonComp.Corrective_Actions_Submitter__c))&&nonComp.Correction_Plan_Status__c!='EEC Accepted'){
                nonComp.Correction_Plan_Status__c='Provider Submitted, EEC to Review';
            }
        
          if(trigger.isUpdate){
                if((oldnoncompMap.get(nonComp.id).Correction_Plan_Status__c)!='EEC Accepted'&&nonComp.Correction_Plan_Status__c=='EEC Accepted'){
                    nonComp.Date_Correction_Plan_Accepted__c = date.Today();
                }else if(nonComp.Correction_Plan_Status__c!='EEC Accepted' && oldnoncompMap.get(nonComp.id).Correction_Plan_Status__c=='EEC Accepted'){
                    nonComp.Date_Correction_Plan_Accepted__c = null;
                }
            }
        }
    }
    
  
   
}