src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Items_with_Corrective_Actions__c</fullName>
        <label>Number of Items with Corrective Actions</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Inspection_Item__c.Date_Implemented__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_of_non_compliant_items__c</fullName>
        <description>Provide the number of non-compliant items from an inspection</description>
        <label>Number of Non-Compliant items</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <recordTypes>
        <fullName>Investigation_Visits</fullName>
        <active>true</active>
        <description>Visits done in the scope of an investigation, these visits will not generate a specific report as the visit report will be included in the investigation report</description>
        <label>Investigation Visits</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal.</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <inlineHelpText>User who added the corrective actions</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_History_Record_flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create History Record flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND(
ISPICKVAL(Inspection_Result__c, &quot;Non-Compliant&quot;),
ISBLANK( Date_Implemented__c )
)</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Date of the last update of corrective action feedback.</inlineHelpText>
        <label>Last Corrective Action EEC Feedback</label>
        <type>Date</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Require_Portal_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Allows for Licensor/Investigator to specify if a feedback is to be sent to the Provider via email to request a review of non-compliance items</description>
        <inlineHelpText>Check this field if an email is required to be sent to the Provider to request a review of non-compliant items</inlineHelpText>
        <label>Require Portal Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Fill this field if the corrective action submitted by the provider is not appropriate. By updating this field, Providers using electronic communication will be informed by email and will be able to update the correction plan on the portal</inlineHelpText>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <description>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</description>
        <inlineHelpText>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Create_History_Record_flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create History Record flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feedback_Requested__c</fullName>
        <formula>AND( ISBLANK( Date_Implemented__c ),  NOT(Investigation__r.isLegacyInvestigation__c) )</formula>
        <label>Feedback Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Corrective_Action_EEC_Feedback__c</fullName>
        <inlineHelpText>Date of the last update of corrective action feedback</inlineHelpText>
        <label>Last Corrective Action EEC Feedback</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Require_Portal_Feedback__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, it means that the report was published on the web and the investigation has non-compliance items that needs to be filled by the provider</inlineHelpText>
        <label>Require Portal Feedback</label>
        <type>Checkbox</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submission_History__c.object
<CustomObject>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Action_EEC_Feedback__c</fullName>
        <label>Corrective Action EEC Feedback</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Corrective_Action_EEC_Feedback__c</fullName>
        <label>Last Corrective Action EEC Feedback</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Visit_Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit Item</label>
        <referenceTo>Inspection_Item__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Submission History</relationshipLabel>
        <relationshipName>Submission_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission History</label>
    <nameField>
        <displayFormat>SH# {00000}</displayFormat>
        <label>Submission History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submission History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_InspectionItemTriggerHandler.cls
public class EEC_InspectionItemTriggerHandler {
    private List<Inspection_Item__c> visititems = new List<Inspection_Item__c>();
    private Map<Id,Inspection_Item__c> oldVisitMap = new Map<Id,Inspection_Item__c>();
    RecordType rType = [select Id from RecordType where SobjectType = 'Inspection__c' and DeveloperName = 'Investigation_Visits'];
    //private Map<Id, RecordType> recordTypes = new Map<Id, RecordType>([SELECT Id, Name FROM RecordType WHERE sObjectType = 'Inspection__c']);
    
    public EEC_InspectionItemTriggerHandler(List<Inspection_Item__c> newList,Map<Id,Inspection_Item__c> oldMap){
        this.visititems = newlist;
        this.oldVisitMap = oldMap;
    } 
     
    
    public void updateRequireFeedback(){        
        Set<id> insids = new Set<Id>();
        Set<Id> invids = new Set<Id>();
        String cname;
        Inspection_Item__c oldII;
        System.debug('List size' + visititems.size());
        for(Inspection_Item__c i : visititems){ 
            oldII = oldVisitMap.get(i.Id); 
            if (i.Inspection_Result__c == 'Non-Compliant' && i.Feedback_Requested__c == false){    
                insids.add(i.Inspection_No__c);        
            }
       }
       if(insids != null){ 
           System.debug('insids-->'+insids);
           Map<Id,Inspection__c> inspMap = new Map<Id,Inspection__c>(
               [SELECT id,Investigation__c,
                (SELECT Id,Date_Implemented__c 
                 FROM Inspection_Items__r 
                 WHERE Inspection_Result__c = 'Non-Compliant' 
                 AND Feedback_Requested__c = true),
                Number_of_Items_with_Corrective_Actions__c,
                Number_of_non_compliant_items__c 
                FROM Inspection__c 
                WHERE id in :insids AND RecordTypeId = :rType.Id]);
            
           System.debug('inspMap.values()'+ inspMap.values());
           for(Inspection__c insp: inspMap.values()){
               if (insp.Investigation__c != null){
                  if((insp.Inspection_Items__r == null) || (insp.Inspection_Items__r != null && insp.Inspection_Items__r.size() == 0)){
                        invids.add(insp.Investigation__c);
                  }    
               }
           }
       }
       if(invids !=null && invids.size() > 0){
           System.debug('invids' + invids);
           Map<Id, Investigation__c> invsMap = new Map<Id,Investigation__c>(
               [SELECT Id,Created_on_the_Web__c,Require_Portal_Feedback__c 
                FROM Investigation__c where Id in :invids ]);
           List<Non_Compliant__c> nonList = new List<Non_Compliant__c>([
               SELECT id FROM Non_Compliant__c 
               WHERE Investigation__c in :invids AND 
               Feedback_Requested__c = true LIMIT 1]);
           //Non_Compliant__c noncomp;
           List<Investigation__c> invlist = new List<Investigation__c>();
           for(Investigation__c inv : invsMap.values()){
              if (inv != null){
                 System.debug('Madhav test 1');
                 if (inv.Created_on_the_Web__c == true){
                     System.debug('Madhav test 2');
                    if (nonList.size()> 0 )             
                    {
                      System.debug('Madhav test 3');
                      break;
                    }
                    else{
                      if (inv.Require_Portal_Feedback__c){ //Mod by LD - Fix for BMMS-227
                          inv.Require_Portal_Feedback__c = false;
                          System.debug('Madhav test 4');
                          invlist.add(inv);
                      }
                    }
                }
             }
           }
           if (invlist != null && invlist.size() > 0 ){
               System.debug('Madhav test 5');
               System.debug('Investigation List' + invlist);
               update invlist;
           }  
       }    
    }
    
    public void SubmissionHistory(){
        list<Submission_History__c> SHlist = new list<Submission_History__c>();
        list<Inspection_Item__c> VIlist = new list<Inspection_Item__c>();
        for(Inspection_Item__c VI : visititems){
            if(VI.Create_History_Record_flag__c == true && oldvisitmap.get(VI.id).Create_History_Record_flag__c==false){
                Submission_History__c SH = new Submission_History__c();
                SH.Visit_Item__c = VI.id;
                SH.RecordTypeId = [select Id from RecordType where Name = 'Visit Corrective Action Plan Submission History' and SobjectType = 'Submission_History__c'].Id;
                system.debug('MMM'+SH.Visit_Item__c);
                SH.Visit__c = VI.Inspection_No__c;
                SH.Correction_Plan__c = VI.Correction_Plan__c;
                SH.Corrective_Actions_Submitter__c = VI.Corrective_Actions_Submitter__c;
                SH.Date_Implemented__c= VI.Date_Implemented__c;
                SH.Date_Corrective_Actions_Received__c= VI.Date_Corrective_Actions_Received__c;
                SH.Corrective_Action_EEC_Feedback__c= VI.Corrective_Action_EEC_Feedback__c;
                SH.Last_Corrective_Action_EEC_Feedback__c=VI.Last_Corrective_Action_EEC_Feedback__c;
                SHlist.add(SH);
                Inspection_Item__c II = new Inspection_Item__c(ID=VI.id);
                II.Create_History_Record_flag__c=false;
                VIlist.add(II);
                
            
            }
         
        }
    if(SHlist.size()>0){
        insert SHlist;
        update VIList;
    
    }   
    
    }
}