src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspector_del__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Licensor or investigator who performs the inspection</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_non_compliant_items__c</fullName>
        <description>Provide the number of non-compliant items from an inspection</description>
        <label>Number of Non-Compliant items</label>
        <summaryFilterItems>
            <field>Inspection_Item__c.Inspection_Result__c</field>
            <operation>equals</operation>
            <value>Non-Compliant</value>
        </summaryFilterItems>
        <summaryForeignKey>Inspection_Item__c.Inspection_No__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_of_visit__c</fullName>
        <label>Time of visit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <description>Will be filled by the corrective actions taken by the provider in case of non-compliance</description>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <inlineHelpText>User who added the corrective actions</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <description>Date the corrective actions were or will be implemented. This information should be provided by the provider when filling the answer of statement of non-compliance.</description>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Investigation.Closed Date</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Determinations__c</fullName>
        <label>Determinations</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Facility_Description__c</fullName>
        <label>Provider Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Investigation_Activities__c</fullName>
        <label>Investigation Activities</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Investigation_Findings__c</fullName>
        <label>Investigation Findings</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Non_compliances__c</fullName>
        <label>Non-compliances</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reason_for_Investigation__c</fullName>
        <label>Reason for Investigation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Correction_Plan__c</fullName>
        <inlineHelpText>Describe here the corrective actives that have been taken or will be taken to resolve this non-compliance</inlineHelpText>
        <label>Correction Plan</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corrective_Actions_Submitter__c</fullName>
        <description>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</description>
        <inlineHelpText>Update &quot;Corrective Actions Submitter&quot; with First / Last name of the user who did the update</inlineHelpText>
        <label>Corrective Actions Submitter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Corrective_Actions_Received__c</fullName>
        <label>Date Corrective Actions Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Implemented__c</fullName>
        <inlineHelpText>Mention here the date the corrective actions were implemented or the expected date of completion</inlineHelpText>
        <label>Date Implemented</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <inlineHelpText>Describe here the non-compliance</inlineHelpText>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_PortalInvestigationController.cls
public with sharing class EEC_PortalInvestigationController {
    
  public Investigation__c invest {get;set;}
  public List<Inspection__c> visits {get;set;}
  public List<NoteAndAttachment> notesAndAttachments {get;set;}
  public List<Non_Compliant__c> nonCompliants {get;set;} 
  public List<Inspection_Item__c> iitems {get; set;} 
  public List<Inspection__c> lstVisits {get;set;}    
  public Map<String, String> attachmentMap {get;set;}
  public Account acc{get;set;}  
  public String invId{get;set;}  
  public String memberId{ get; set; }   
    
  public EEC_PortalInvestigationController() {
    memberId = ApexPages.currentPage().getParameters().get('member');
    if(String.isNotBlank(memberId)){
	  List<Account> accList = [SELECT Id FROM Account WHERE ID =: memberId LIMIT 1];  	
      if(accList != null && accList.size() > 0){
          acc = accList.get(0);
      }
    }else{  
        List<Account> accList = [SELECT Id FROM Account WHERE ID in (SELECT Accountid FROM user WHERE Id = :Userinfo.getUserId()) LIMIT 1 ];  
        if(accList != null && accList.size() > 0){
            acc = accList.get(0);
        }
    }
    invId = ApexPages.currentPage().getParameters().get('id');
    attachmentMap = new Map<String, String>{'CoverLetter' => 'null','NonCompliance' => 'null','Narrative' => 'null'};   
     
    if ( invId != NULL) {
      invest = [
        Select  
          Id, 
          Name, 
          Investigation_Status__c, 
          Closed_Date__c, 
          Facility_Description__c,
          Reason_for_Investigation__c,
          Investigation_Activities__c,
          Determinations__c,
          Investigation_Findings__c,
          Non_compliances__c,
          (Select Id, IsNote, Title From NotesAndAttachments ORDER BY LastModifiedDate DESC)
        From Investigation__c 
        Where Id = :invId
      ];
      notesAndAttachments = invest.NotesAndAttachments;
      if (notesAndAttachments != null) {  
        
        for (NoteAndAttachment attachment : notesAndAttachments) {
         System.debug('-----> notesAndAttachments: ' + notesAndAttachments);
          try {
            if (attachmentMap.get('CoverLetter') == 'null' || attachmentMap.get('NonCompliance') == 'null' || attachmentMap.get('Narrative') == 'null') {  
              String[] titleSplit = attachment.Title.split('-');
              String type = '';
             
              if(titleSplit != null && titleSplit.size() > 0) {
                type = titleSplit[0];          
              } 
              if (attachmentMap.containsKey(type) && attachmentMap.get(type) == 'null') {  
                attachmentMap.put(type, attachment.Id);
              }
            } else {
              break;
            }
          } catch(Exception e) {
            System.debug('Error: ' + e.getMessage());        
          }
        }
      }
    } else {
      invest = null;
    }
   
    lstVisits = [SELECT Id, Name, Status__c, Date_of_Visit__c, Time_of_Visit__c, Inspector_del__r.Name, Number_of_non_compliant_items__c From Inspection__c Where Investigation__c = :invId AND Status__c = 'Closed'];  
  	nonCompliants = [SELECT Id, Name, Observations__c, Correction_Plan__c, Date_Implemented__c, Corrective_Actions_Submitter__c, Date_Corrective_Actions_Received__c From Non_Compliant__c Where Investigation__c = :invId]; 
	iitems = [SELECT Id, Name,Observations__c,Correction_Plan__c,Date_Implemented__c,Corrective_Actions_Submitter__c,Date_Corrective_Actions_Received__c FROM Inspection_Item__c WHERE Inspection_No__r.Investigation__c =: invId AND Inspection_Result__c = 'Non-Compliant'];
      
  }
  public PageReference returnProvider() {
    PageReference pPage = page.EEC_PortalProviderPage;
    if(memberId != null)  
       pPage.getParameters().put('member',EEC_Util.encryptGetParam(memberId));
    return pPage;
  }  
    
  public List<Inspection__c> getVisits(String Id) {
    // TODO: Status must be closed.
  	return [Select Id, Name, Status__c, Date_of_Visit__c, Time_of_Visit__c, Inspector_del__r.Name, Number_of_non_compliant_items__c From Inspection__c Where Investigation__c = :Id AND Status__c = 'Closed'];
  }
    
  public List<Non_Compliant__c> getNonCompliants(String Id) {
  	return [Select Id, Name, Observations__c, Correction_Plan__c, Date_Implemented__c, Corrective_Actions_Submitter__c, Date_Corrective_Actions_Received__c From Non_Compliant__c Where Investigation__c = :Id];   
  }
}