src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Activity_Summary__c</fullName>
        <description>Describe the activity summary that will be used in the visit narrative</description>
        <inlineHelpText>Describe the activity summary that will be used in the visit narrative</inlineHelpText>
        <label>Activity Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Note that all licensing visits with the following statuses will be available on portal:  &quot;Scheduled&quot; (if Announced flag is checked)  / &quot;Closed&quot; / &quot;Report Sent to Provider, Awaiting Feedback&quot; / &quot;Feedback received, to review&quot;</description>
        <inlineHelpText>If checked, non compliant items associated to this visit have been published on portal and are ready to be reviewed.</inlineHelpText>
        <label>Published on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Visit__c</fullName>
        <description>Date of site inspection visit</description>
        <label>Date of Visit</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Visit__c</fullName>
        <description>Reason of Visit</description>
        <label>Reason of Visit</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Licensing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Increase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legacy System Import</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provisional License Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Activate Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Enhanced Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Full Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Assistance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_TestVisitTriggerHandler.cls
@isTest
public with sharing class EEC_TestVisitTriggerHandler {

    @isTest static void testVisitySummaryDefualtTriggerToBe() {
        
        LEAD_COnfiguration__c conf = EEC_TestUtil.mockLeadConfig('#Visit_Reason# #Visit_Date#');
        
        Account a = EEC_TestUtil.mockProviderConfig(
            EEC_TestUtil.mockCity(),
            conf 
        );
         
        Inspection__c i = EEC_TestUtil.mockInspection(a); 
        
        i.Status__c = 'To be scheduled';
        i.Activity_Summary__c = null;
        i.Date_of_visit__c = null;
        i.Type_of_visit__c = 'Capacity Increase';
        update i;
        
        
        i.Status__c = 'Visit Completed';
        update i;
        
        i = [SELECT Activity_Summary__c, Type_of_Visit__c, Date_of_visit__c  FROM Inspection__C WHERE ID = :i.Id];
        
        System.debug('-----Inspection Type of Visit: ' + i.Type_of_visit__c);
        System.debug('-----Inspection: ' + i);
        
        System.assertNotEquals(null, i.Type_of_visit__c);
    }


    @isTest static void testVisitySummaryDefualtTriggerScheduled() {
     
        LEAD_COnfiguration__c conf = EEC_TestUtil.mockLeadConfig('#Visit_Reason# #Visit_Date#');
    
        Account a = EEC_TestUtil.mockProviderConfig(
            EEC_TestUtil.mockCity(),
            conf 
        ); 
        
        Inspection__c i = EEC_TestUtil.mockInspection(a);
         
        
        i.Status__c = 'Scheduled';
        i.Activity_Summary__c = null;
        i.Date_of_visit__c = System.Today();
        i.Type_of_visit__c = 'Capacity Increase';
        update i;
        
        i.Status__c = 'Visit Completed';
        //i.Created_on_the_Web__c = true;
        update i;
        
        i = [SELECT Activity_Summary__c, Type_of_Visit__c, Date_of_visit__c, Status__c  FROM Inspection__C WHERE ID = :i.Id];
        
        //System.assertEquals('Visit Completed', i.Status__c);
        //System.assert(i.Activity_Summary__c.contains(i.Type_of_visit__c));
        //System.assert(i.Activity_Summary__c.contains(EEC_DateUtil.formatDate('MM/dd/yyyy', i.Date_of_visit__c)));
    }
}