src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_TestGenerateVisitChecklistExtension.cls
@isTest 
public with sharing class EEC_TestGenerateVisitChecklistExtension  {
  
    @isTest static void testVisitChecklistItemWrapperConstruct(){
        Inspection_Item__c i = new Inspection_Item__c();
        String s = 'test';
        
        EEC_GeneratePDFBase.VisitChecklistItemWrapper vciwc = new 
        EEC_GeneratePDFBase.VisitChecklistItemWrapper (i, s);
        
        System.assertEquals(vciwc.inspectionItem, i);
        System.assertEquals(vciwc.standardRegulations, s);
    }
    
    
    @isTest static void testAugmentStandardInspectionItems(){  
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c sii1 = EEC_TestUtil.mockStdInspectionItem();
        
        Regulation__c reg1 = EEC_TestUtil.mockRegulation();
        Regulation__c reg2 = EEC_TestUtil.mockRegulation();
        EEC_TestUtil.mockRegStdInsp(reg1, sii1);
        EEC_TestUtil.mockRegStdInsp(reg2, sii1);
        
        Inspection_Item__c ii1 = EEC_TestUtil.mockInspectionItem(i, sii1 , 'Non-Compliant', false, null);
        Inspection_Item__c ii2 = EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation() , 'Non-Compliant', false, null);
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = EEC_GeneratePDFBase.augmentStandardInspectionItems(new List<Inspection_Item__c>{ii1, ii2});
        
        System.assertEquals(2, l.size());
        System.assertEquals(reg1.Name + ', ' + reg2.Name, l.get(0).standardRegulations);
        System.assertEquals('', l.get(1).standardRegulations);

    
    }

    @isTest static void testGetAssessedStandardInspectionItems(){ 
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
        EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));
        
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getAssessedStandardInspectionItems();
        System.assertEquals(1, l.size());
    }


    @isTest static void testGetUnassessedStandardInspectionItems(){
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), null, true, null);
        EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));
        
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getUnassessedStandardInspectionItems();
        System.assertEquals(1, l.size());
        
    }

    @isTest static void testGetAdditionalInspectionItems() {
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        Regulation__c reg = EEC_TestUtil.mockRegulation(); 
        //EEC_TestUtil.mockInspectionItem(i, reg, 'Non-Compliant', false, null);
        //EEC_TestUtil.mockInspectionItem(i, reg, 'Non-Compliant', false, 'HJelp');
        //EEC_TestUtil.mockInspectionItem(i, reg, null, true, null);
        EEC_TestUtil.mockInspectionItem(i, stdIi, 'Non-Compliant', false, null);
        EEC_TestUtil.mockInspectionItem(i, stdIi, 'Non-Compliant', false, 'Helo');
        EEC_TestUtil.mockInspectionItem(i, stdIi, null, true, null);
        EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));
        
        List<EEC_GeneratePDFBase.VisitChecklistItemWrapper> l = ext.getAdditionalInspectionItems();
        
        System.assertEquals(1, l.size(), 1);
    }
    
    @isTest static void testGetHasNonCompliantTrue() {
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null); 
        EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));
         
        System.assertEquals(true, ext.getHasNonCompliant());
    }
    @isTest static void testGetHasNonCompliantFalse() {
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Compliant', false, null); 
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Not Applicable', false, null); 
        EEC_GenerateVisitChecklistExtension ext = new EEC_GenerateVisitChecklistExtension(new ApexPages.StandardController(i));
         
        System.assertEquals(false, ext.getHasNonCompliant());
    }

}