src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_BaseAttachPDF.cls
public abstract with sharing class EEC_BaseAttachPDF {

    protected PageReference pageReference { get; set; }
    protected String id { get; set; }
    protected Inspection__c obj { get; set; }
    protected List<Inspection__c> childVisits {get;set;}
    private List<Attachment> attachmentsToInsert {get;set;}
    
    public EEC_BaseAttachPDF(ApexPages.StandardController stdController){
        this.id = stdController.getId();
        this.obj = [SELECT Name, Mater_Visit_for_Res_Cluster_of_Visits__c FROM Inspection__c WHERE Id = :id];
        this.childVisits = [Select Id, Mater_Visit_for_Res_Cluster_of_Visits__c, Name From Inspection__c Where Mater_Visit_for_Res_Cluster_of_Visits__c = :id];
        this.attachmentsToInsert = new List<Attachment>();
    }
    
    public pageReference savePDF(){
        // Create and insert the master attachment.
        createAndInsertAttachment(obj);
        // If there are child visits then generate and 
        if (childVisits != null && childVisits.size() > 0) {
            for (Inspection__c child : childVisits) {
                createAndInsertAttachment(child);
            }
        }
        insert attachmentsToInsert;
        // Update the object issue dates.
        updateObject(obj);
        // Update the object list issue dates. 
        updateChildObjects(childVisits);
        // Return the page reference.
        return new PageReference('/' + id);
    }
    
    private void createAndInsertAttachment(Inspection__c refObj) {
        PageReference pagePdf = pdfPageReference();
        Blob pdfPageBlob;
        Boolean isNarrativeChild = refObj.Mater_Visit_for_Res_Cluster_of_Visits__c != null && pdfName().contains('Narrative') ? true : false;
        
        pagePdf.getParameters().put('id', isNarrativeChild ? obj.Id : refObj.Id);
        pdfPageBlob = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : pagePdf.getContentAsPDF();
             
        Attachment a = new Attachment();
        a.Body = pdfPageBlob;
        a.ParentID = refObj.Id;
        a.Name = pdfName() + refObj.Name + '.pdf';
        //insert a;
        attachmentsToInsert.add(a);
    }
    
    protected abstract PageReference pdfPageReference();
    protected abstract String pdfName();
    protected abstract void updateObject(Inspection__c obj);
    protected abstract void updateChildObjects(List<Inspection__c> childVisits);

}