src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Cover_Letter_Issue_Date__c</fullName>
        <inlineHelpText>Date the cover letter was issued last.</inlineHelpText>
        <label>Cover Letter Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sent_date__c</fullName>
        <description>Date the report was sent to the provider</description>
        <inlineHelpText>Date the report was sent to the provider.</inlineHelpText>
        <label>Sent date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_AttachGeneratedCoverLetterPDF.cls
public with sharing class EEC_AttachGeneratedCoverLetterPDF extends EEC_BaseAttachPDF {

    public EEC_AttachGeneratedCoverLetterPDF (ApexPages.StandardController stdController){
        super(stdController);
    }
       
    public override void updateObject(Inspection__c obj){
      obj.Cover_letter_issue_date__c = System.Today();
      obj.Status__c = 'Report Sent to Provider, Awaiting feedback';
      update obj;
    }
    
    public void updateObjectAfterCoverLetter(Inspection__c obj){
      obj.Cover_letter_issue_date__c = System.Today();
      obj.Sent_date__c = System.Today();  
      obj.Status__c = 'Report Sent to Provider, Awaiting feedback';
      update obj;
    }
    
    public override void updateChildObjects(List<Inspection__c> childVisits){
      for (Inspection__c obj : childVisits) {
        obj.Cover_letter_issue_date__c = System.Today();
        obj.Status__c = 'Report Sent to Provider, Awaiting feedback';
      }
      update childVisits;
    }
    
    public override String pdfName(){
        return 'CoverLetter-';
    }
    
    public override PageReference pdfPageReference(){
        return Page.EEC_GenerateVisitCoverLetter;
    }
       
}