src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Offline_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag checked when the visit has been downloaded to be used on the offline app. Edits to such visit are not authorized</inlineHelpText>
        <label>Offline Lock</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_UseWithOfflineVisitAppController.cls
public class EEC_UseWithOfflineVisitAppController {
    
    private final Inspection__c inspectionRecord;
    public boolean useOnOfflineVisitMode {get;set;}
    public EEC_UseWithOfflineVisitAppController(ApexPages.StandardController controller){
        useOnOfflineVisitMode = false;
        this.inspectionRecord = (Inspection__c) controller.getRecord();
    }
    public void updateOfflineVisitLock(){
        if(!inspectionRecord.Offline_Lock__c){
            useOnOfflineVisitMode = true;
            inspectionRecord.Offline_Lock__c = true;
            upsert inspectionRecord;
        }
        //return null;
    }
}