src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Mater_Visit_for_Res_Cluster_of_Visits__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select here the visit that will serve as Primary Visit. Being defined as a &apos;dependent associated&apos; visit, this visit will follow the same process than the Primary for the following steps: visit scheduling, selection of visit checklist, and report creation.</inlineHelpText>
        <label>Primary Visit (for Cluster of Visit)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Inspector_del__c</field>
                <operation>equals</operation>
                <valueField>Inspection__c.Inspector_del__c</valueField>
            </filterItems>
            <filterItems>
                <field>Inspection__c.RecordType.Name</field>
                <operation>contains</operation>
                <value>Licensing</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Is_Residential__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Mater_Visit_for_Res_Cluster_of_Visits__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>Inspection__c.Provider_No__r.Umbrella_Members__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Dependent Associated Visits (for Res. Cluster of Visits)</relationshipLabel>
        <relationshipName>Slave_Visits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Statement_of_non_compliance__c</fullName>
        <inlineHelpText>Date the statement of non-compliance was last generated</inlineHelpText>
        <label>Statement of non-compliance Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_GenerateNonCompPDFController.cls
public with sharing class EEC_GenerateNonCompPDFController {
    
    private final Inspection__c inspectionRecord;
    private List<Inspection__c> childVisits {get;set;}
    private List<Attachment> attachmentsToInsert {get;set;}
    
    public EEC_GenerateNonCompPDFController(ApexPages.StandardController controller) {
        this.inspectionRecord = (Inspection__c) controller.getRecord();
        this.attachmentsToInsert = new List<Attachment>();
        this.childVisits = [Select Id, Name From Inspection__c Where Mater_Visit_for_Res_Cluster_of_Visits__c = :inspectionRecord.Id];
    }
    
    public pagereference GeneratePDF(){
        createAndInsertAttachment(inspectionRecord);
        // Update the date on the exisiting object.  
        Inspection__c insp = new Inspection__c(id=inspectionRecord.Id,Statement_of_non_compliance__c=Date.today());
        update insp;
        // Loop through all child visits if they exist.
        if (childVisits != null && childVisits.size() > 0) {
            for (Inspection__c child : childVisits) {
                createAndInsertAttachment(child);
                // Update the issue date on the child dates. 
                child.Statement_of_non_compliance__c = Date.today();
            }
            update childVisits;
        }
        insert attachmentsToInsert;
        // Return the page reference.  
        return new PageReference('/' + inspectionRecord.Id);
    }
    
    private void createAndInsertAttachment(Inspection__c refObj) {
        PageReference pagePdf = new PageReference('/apex/EEC_GeneratePDFNC');
        pagePdf.getParameters().put('id', refObj.Id);
        Blob pdfPageBlob;
        pdfPageBlob = Test.isRunningTest() ? Blob.valueOf('UNIT.TEST') : pagePdf.getContentAsPDF();
             
        Attachment a = new Attachment();
        a.Body = pdfPageBlob;
        a.ParentID = refObj.Id;
        Boolean cB = false; 
        if(ApexPages.currentPage().getParameters().get('Corrective_Action_Plan_Report')!=null){
        cB = Boolean.valueof(ApexPages.currentPage().getParameters().get('Corrective_Action_Plan_Report'));
        }
        if(cB){
            a.Name = 'CorrectiveActionPlanReport-'+refObj.name+'.pdf';
        }else{
            a.Name = 'StatementNonCompliance-'+refObj.name+'.pdf';
        }
        a.Description = 'Statement of Non Compliance';
        //insert a;
        attachmentsToInsert.add(a);
    }
}