src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Visit_Narrative_Issue_Date__c</fullName>
        <inlineHelpText>Date the Visit Narrative was last issued</inlineHelpText>
        <label>Visit Narrative Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_AttachGeneratedNarrativePDF.cls
public with sharing class EEC_AttachGeneratedNarrativePDF extends EEC_BaseAttachPDF {

    public EEC_AttachGeneratedNarrativePDF(ApexPages.StandardController stdController){
        super(stdController);
    }
      
    public override void updateObject(Inspection__c obj){
      obj.Visit_Narrative_Issue_Date__c = System.Today();
      update obj;
    }
    
    public override void updateChildObjects(List<Inspection__c> childVisits){
      for (Inspection__c obj : childVisits) {
        obj.Visit_Narrative_Issue_Date__c = System.Today();
      }
      System.debug('----> ChildVisits: ' + childVisits);
      update childVisits;
    }
    
    public override String pdfName(){
        return 'Narrative-';
    }
    
    public override PageReference pdfPageReference(){
        return Page.EEC_GenerateVisitNarrativePDF;
    }
       
}