src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_UpdateInterventionControllerTest.cls
@isTest
public class EEC_UpdateInterventionControllerTest {
    
  public static testMethod void testEEC_UpdateInterventionController() {
    PageReference pr = Page.EEC_PortalProviderPage;
    Test.setCurrentPage(pr);
    ID accountid;
    Investigation__c  invest = EEC_TestUtil.loadInvestigationSetup();  
    Intervention__c inter = EEC_TestUtil.mockIntervention(invest); 
    ApexPages.currentPage().getParameters().put('id', inter.Id);
    EEC_UpdateInterventionController pinter = new EEC_UpdateInterventionController();   
    pinter = new EEC_UpdateInterventionController();   
    Attachment attachment = pinter.Attachment;    
    attachment.Name = 'Narrative-Investigation 123';
    Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    attachment.Body = bodyblob;
//    attachment.ParentId = inter.id;    
    pinter.upload();
    pinter.save();
    pinter.cancel();
    pinter.done();
     
    
  }  
  
}