src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Cancel_Reason__c</fullName>
        <inlineHelpText>Reason this intervention was not done and cancelled</inlineHelpText>
        <label>Cancel Reason</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Do</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit via Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Approval_Task_Creation__c</fullName>
        <label>Approval Task Creation</label>
        <picklist>
            <picklistValues>
                <fullName>NonEscalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NonEscalated Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Investigation can be assigned to a Licensor, Supervisor or Inspector</description>
        <inlineHelpText>User who will take the lead on the investigation.</inlineHelpText>
        <label>Leader</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Investigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Date__c</fullName>
        <description>Investigation.Closed Date</description>
        <label>Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cover_Letter_Issue_Date__c</fullName>
        <inlineHelpText>Date the cover letter was created in the system</inlineHelpText>
        <label>Cover Letter Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_on_the_Web__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine if a report has been deployed/shown to the portal community.</description>
        <inlineHelpText>Check this box if you wish to deploy this Investigation to the Web Portal.</inlineHelpText>
        <label>Publish Report on Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Investigation_Status__c</fullName>
        <description>Investigation Status</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned - In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved - Report to send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Publish/Send to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Legacy Investigation)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_TestInvestigationTrigger.cls
@isTest
public with sharing class EEC_TestInvestigationTrigger {

    @isTest static void testUpdateClosedInvestigationsBefore() {
        test.startTest();
        
        User u = EEC_TestUtil.mockUser();
        
        System.runAs(u) {
            Investigation__c i = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
            i.Investigation_Status__c = 'Approved - Report to send';
            i.Assigned_To__c = u.id;
            i.Approval_Task_Creation__c = 'NonEscalated Approved';
            update i;
            i.Investigation_Status__c = 'Report Sent to Provider';    
            update i;    
            //i.Investigation_Status__c = 'Closed'; 
            //i.Cover_Letter_Issue_Date__c = System.Today();
            //Intervention__c inv = EEC_TestUtil.mockIntervention(i);
            //inv.Status__c = 'Cancelled';
            //inv.Cancel_Reason__c = 'Testing';
            
            //update inv;
            //update i;
            
            //i = [SELECT Closed_date__c FROM Investigation__c WHERE ID = :i.Id];
             
            //System.assertEquals(System.today(), i.Closed_Date__c); 
        }
        
        test.stopTest();
    }
    
    @isTest static void testUpdateClosedInvestigationsAfter() {
     test.startTest();
        
        User u = EEC_TestUtil.mockUser();
        
        System.runAs(u) {
            Investigation__c i = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
            i.Investigation_Status__c = 'Approved - Report to send';
            i.Assigned_To__c = u.id;
            i.Approval_Task_Creation__c = 'NonEscalated Rejected';
            update i;
            i.Investigation_Status__c = 'Ready to Publish/Send to Provider';
			i.Created_on_the_Web__c = true;   
            update i; 
        }
    }

}