src/objects/Intervention__c.object
<CustomObject>
    <description>List the intervention needed for a given investigation</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Interventions</relationshipLabel>
        <relationshipName>Interventions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portal_User_Instructions__c</fullName>
        <inlineHelpText>Instructions to be given to the portal user in order to complete internal investigation.</inlineHelpText>
        <label>Portal User Instructions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Do</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To Submit via Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <inlineHelpText>Date the internal investigation was submitted.</inlineHelpText>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Be_Provided_By__c</fullName>
        <inlineHelpText>Deadline to fill internal investigation</inlineHelpText>
        <label>To Be Provided By</label>
        <type>Date</type>
    </fields>
    <label>Intervention</label>
    <nameField>
        <displayFormat>INT-{000000}</displayFormat>
        <label>Intervention ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interventions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Leader_Email__c</fullName>
        <formula>Assigned_To__r.Email</formula>
        <label>Leader Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leader_Name_Text__c</fullName>
        <formula>Assigned_To__r.FirstName + &apos; &apos; + Assigned_To__r.LastName</formula>
        <label>Leader_Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leader_Phone__c</fullName>
        <formula>Assigned_To__r.Phone</formula>
        <label>Leader Phone</label>
        <type>Text</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_UpdateInterventionController.cls
/**
 * An apex class that views and updates Intervention information.
 */
public without sharing class EEC_UpdateInterventionController {

    public void done() {
        attached=false;
        
    }


   public Boolean attached { get; set; }
   public String attachmentMessage {get;set;}
   public String memberId{ get; set; }    
   
   //public Investigation__c investrec{get;set;}
   public Id interventionId{get;set;}
   public List<Attachment> attachlist{get;set;}
   public PageReference cancel() {
        PageReference pPage = Page.EEC_PortalProviderPage;
        if(memberId != null)  
       		pPage.getParameters().put('member',EEC_Util.encryptGetParam(memberId));
        return pPage;
   }


    public PageReference save() {
    
        if (interventionTrans != Null){
                
                interventionTrans.Status__c ='Submitted';
                interventionTrans.Submission_Date__c = Date.Today();
                update interventionTrans;
                
        }
        PageReference pr = Page.EEC_PortalProviderPage;
        if(memberId != null)  
       		pr.getParameters().put('member',EEC_Util.encryptGetParam(memberId));
        return pr;
    
    }
    
    public Intervention__c  interventionTrans {get;set;}
    
    public EEC_UpdateInterventionController() {
    memberId = ApexPages.currentPage().getParameters().get('member');
    attachmentMessage = '';
    attached=false;
    interventionId = ApexPages.currentPage().getParameters().get('Id');
        
    interventionTrans = [select id,Status__c,Submission_Date__c,Portal_User_Instructions__c,To_Be_Provided_By__c,Investigation__r.Name,Investigation__r.Leader_Name_Text__c,Investigation__r.Leader_Email__c,Investigation__r.Leader_Phone__c
                         from Intervention__c where Id = :interventionId ]; 

	attachlist = [select Id,name,CreatedDate from Attachment where attachment.OwnerId = :UserInfo.getUserId() and attachment.ParentId = :interventionTrans.Id
                       and LastModifiedById = :UserInfo.getUserId() order by LastModifiedDate Desc];
         
    }
    
    public Attachment attachment {
      get {
          if (attachment == null)
            attachment = new Attachment();
            return attachment;
        }
      set;
    }
    
    public void upload() {
      attached = true;   
      if(attachment != null && attachment.name != null){
         attachment.OwnerId = UserInfo.getUserId();
         attachment.ParentId = interventionTrans.Id; // the record the file is attached to
         //attachment.ParentId = investrec.Id; // the record the file is attached to
         attachment.IsPrivate = false;
         attachmentMessage = attachmentMessage + attachment.name + ', ';
         try {
             insert attachment;
             attached = true;
             attachlist = [select Id,name,CreatedDate from Attachment where attachment.OwnerId = :UserInfo.getUserId() and attachment.ParentId = :interventionTrans.Id
                       and LastModifiedById = :UserInfo.getUserId() order by LastModifiedDate Desc];
         } catch (DMLException e) {
           ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Error uploading attachment'));
         } finally {
           attachment = new Attachment(); 
         }
  
         ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Attachment uploaded successfully'));

     }
     else{
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select a file to be uploaded'));
     }
  

    
    }
    
}