src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Provider_No__c</fullName>
        <description>Provider.Provider No links the parent Provider (Account) record to the child Investigation record</description>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investigations</relationshipLabel>
        <relationshipName>Investigations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if this non compliant item is associated to a high risk regulation</inlineHelpText>
        <label>Key Indicator</label>
        <type>Checkbox</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Non_Compliant_Item_Regulation__c.object
<CustomObject>
    <description>Junction between non compliant items and regulations so multiple regulations can be added to one non-compliant item.</description>
    <fields>
        <fullName>Non_Compliant_Item__c</fullName>
        <label>Non Compliant Item</label>
        <referenceTo>Non_Compliant__c</referenceTo>
        <relationshipLabel>Associated Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Non Compliant Item Regulations</relationshipLabel>
        <relationshipName>Non_Compliant_Item_Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Non Compliant Item Regulation</label>
    <nameField>
        <displayFormat>NC-R-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item Regulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>FCC_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>FCC High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GSA_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>GSA High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_P_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>R&amp;P High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_NonComplaintItemRegulationTgrHandler.cls
public class EEC_NonComplaintItemRegulationTgrHandler {
	private static list<Non_Compliant__c> updatelist = new list <Non_Compliant__c>();
	 private static set<id> NCIRid = new set<id>();
	 private static set<id> Invid = new set<id>();
	 private static set<id> NCid = new set<id>();
	 private static map<id,Non_Compliant__c> NCMap = new map <id,Non_Compliant__c>();
	 private static boolean flag = false ;
	public static void UpdateKeyIndicator(Map<Id,Non_Compliant_Item_Regulation__c> NewMap, Map<Id,Non_Compliant_Item_Regulation__c> OldMap){
	
	for(Non_Compliant_Item_Regulation__c NCIR : NewMap.values()){
			NCIRid.add(NCIR.id);
			NCid.add(NCIR.Non_Compliant_Item__c);
	   }
	list<Non_Compliant_Item_Regulation__c> NCIRlist = new list <Non_Compliant_Item_Regulation__c>([select id,name,Non_Compliant_Item__c,Non_Compliant_Item__r.Key_Indicator__c,Non_Compliant_Item__r.Investigation__r.id,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.name,Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c,Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name,
	                                                Regulation__c,Regulation__r.FCC_High_Risk_Reg__c,Regulation__r.R_P_High_Risk_Reg__c,Regulation__r.GSA_High_Risk_Reg__c
	                                                from Non_Compliant_Item_Regulation__c where Non_Compliant_Item__c IN: NCid]);
	
	list<Non_Compliant__c> NClist = new list<Non_Compliant__c>([select id,name,Key_Indicator__c from Non_Compliant__c where id IN: NCid]);
	for(Non_Compliant__c NC : NClist){
	     NCMap.put(NC.id,NC);
	}
	for(Non_Compliant_Item_Regulation__c NC : NCIRlist){
		system.debug('Record Type of Provider'+NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name);
		if(NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name == 'Family Child Care' && NC.Regulation__r.FCC_High_Risk_Reg__c ==true && flag==false){
		    NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		    flag = true;
		}else if (NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c == true && NC.Regulation__r.R_P_High_Risk_Reg__c==true){
	        NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		    flag = true;
		}else if(NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c == true && NC.Regulation__r.GSA_High_Risk_Reg__c==true){
		    NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		    flag = true;
		}
		else{
		if(flag == false)
		    NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = false;
		}
		
	}
	system.debug('Update Map'+NCMap.size());
	if(NCMap.size()>0){
	 update NCMap.values();
	}
  
	}
	
	public static void UpdateKeyOnDelete(Map<Id,Non_Compliant_Item_Regulation__c> NewMap, Map<Id,Non_Compliant_Item_Regulation__c> OldMap){
	
  for(Non_Compliant_Item_Regulation__c NCIR : OldMap.values()){
			NCIRid.add(NCIR.id);
			NCid.add(NCIR.Non_Compliant_Item__c);
    }
	list<Non_Compliant_Item_Regulation__c> NCIRlist = new list <Non_Compliant_Item_Regulation__c>([select id,name,Non_Compliant_Item__c,Non_Compliant_Item__r.Key_Indicator__c,Non_Compliant_Item__r.Investigation__r.id,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.name,Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name,
	                                                Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c,Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c,
	                                                Regulation__c,Regulation__r.FCC_High_Risk_Reg__c,Regulation__r.R_P_High_Risk_Reg__c,Regulation__r.GSA_High_Risk_Reg__c 
	                                                from Non_Compliant_Item_Regulation__c where Non_Compliant_Item__c IN: NCid]);
	
	list<Non_Compliant__c> NClist = new list<Non_Compliant__c>([select id,name,Key_Indicator__c from Non_Compliant__c where id IN: NCid]);
	for(Non_Compliant__c NC : NClist){
	        NCMap.put(NC.id,NC);
	}
	for(Non_Compliant_Item_Regulation__c NC : NCIRlist){
		system.debug('Record Type of the Provider'+NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name);
	  if(NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.recordtype.name == 'Family Child Care' && NC.Regulation__r.FCC_High_Risk_Reg__c ==true && flag==false){
		      NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		      flag = true;
		}else if (NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_R_P__c == true && NC.Regulation__r.R_P_High_Risk_Reg__c==true){
	          NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		       flag = true;
		}else if(NC.Non_Compliant_Item__r.Investigation__r.Provider_No__r.Is_GSA__c == true && NC.Regulation__r.GSA_High_Risk_Reg__c==true){
		      NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = true;
		      flag = true;
		}
		else{
		 if(flag == false){
		      NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c = false;
		      system.debug('Key Indicator'+NCMap.get(NC.Non_Compliant_Item__c).Key_Indicator__c);
		 }
		}
		
	}
	system.debug('Update Map'+NCMap.size());
	if(NCMap.size()>0){
	     update NCMap.values();
	}
  
	
	}
    
}