src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Report_Narrative_Issue_Date__c</fullName>
        <inlineHelpText>Date the report narrative was issued last</inlineHelpText>
        <label>Report Narrative Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_AttachInvNarrative.cls
public with sharing class EEC_AttachInvNarrative extends EEC_BaseInvAttachPDF {

    public EEC_AttachInvNarrative (ApexPages.StandardController stdController){
        super(stdController);
    }

    public override String pdfName(){
        return 'Narrative-';
    }
    
    public override PageReference pdfPageReference(){
        return Page.EEC_GenerateInvNarrative;
    }
    
    public override void updateObject(Investigation__c i){
        i.Report_Narrative_Issue_Date__c = System.Today(); 
        update i;
    }
}