src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>Statement_of_non_compliance_Issue_Date__c</fullName>
        <inlineHelpText>Date the statement of non-compliance was last generated</inlineHelpText>
        <label>Statement of non-compliance Issue Date</label>
        <type>Date</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_AttachInvNonCompliance.cls
public with sharing class EEC_AttachInvNonCompliance extends EEC_BaseInvAttachPDF {

    public EEC_AttachInvNonCompliance(ApexPages.StandardController stdController){
        super(stdController);
    }

    public override String pdfName(){
        Boolean cB = false; 
        if(ApexPages.currentPage().getParameters().get('Corrective_Action_Plan_Report')!=null){
        cB = Boolean.valueof(ApexPages.currentPage().getParameters().get('Corrective_Action_Plan_Report'));
        }
        if(cB){
            return 'CorrectiveActionPlanReport-';
        }else{
            return 'NonCompliance-';    
        }
        
    }
    
    public override PageReference pdfPageReference(){
        return Page.EEC_GenerateInvestigationNCLetter;
    }
    
    public override void updateObject(Investigation__c i){
        i.Statement_of_non_compliance_Issue_Date__c = System.today();
        update i;
    }
}