src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Messages_Alerts_Known_Issues__c</fullName>
        <description>Messages &amp; Alerts - Known Issues text for home page layouts.</description>
        <inlineHelpText>This field is only used on the &quot;Home Page Message &amp; Alerts&quot; record. If you are attempting to edit this field on a different record type (i.e. Family Child Care, Small Group, etc.) there will be no impact on the homepage.</inlineHelpText>
        <label>Messages &amp; Alerts - Known Issues</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MessagesAndAlertsHomeCtrl.cls
public class MessagesAndAlertsHomeCtrl {
    
  public String alertMsg { get; set; }
  
  public MessagesAndAlertsHomeCtrl() {
    this.alertMsg = '';
    List<LEAD_Configuration__c> availableMsgConfigs = [Select Id, Messages_Alerts_Known_Issues__c, RecordType.Name, CreatedDate From LEAD_Configuration__c Where RecordType.Name = 'Messages and Alerts' Order By CreatedDate DESC];  
    
    if (availableMsgConfigs.size() > 0) {
      this.alertMsg = availableMsgConfigs.get(0).Messages_Alerts_Known_Issues__c;            
    }  
  }
}