EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Complaint</fullName>
        <active>true</active>
        <businessProcess>Complaint</businessProcess>
        <description>Complaint - select this record type when capturing an complaint from a parent or a neighbor</description>
        <label>Complaint</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LEAD_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for LEAD per type of provider.</description>
    <fields>
        <fullName>Complaint_Form_Redirect__c</fullName>
        <inlineHelpText>Web page to redirect the user once the complaint is submitted or abandoned.</inlineHelpText>
        <label>Complaint Form Redirect</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Complaints_Confirmation__c</fullName>
        <inlineHelpText>Text that will be used on the Complaints Web Form confirmation page.</inlineHelpText>
        <label>Complaints Confirmation</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Complaints_Introduction__c</fullName>
        <inlineHelpText>Text that will be used on the Complaints Web Form introduction page.</inlineHelpText>
        <label>Complaints Introduction</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>LEAD Configuration</label>
    <nameField>
        <label>LEAD Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LEAD Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_BaseComplaintsController.cls
public without sharing abstract class EEC_BaseComplaintsController {
 
    private String GLOBAL_CONFIG_NAME = 'Global';
    private Set<String> INVALID_PROVIDER_TYPES = new Set<String>{ 'Umbrella', 'Unlicensed Provider', 'FCC Assistant' };
    public EEC_Complaint complaint { get; set; }

    public EEC_BaseComplaintsController() { 
        complaint = EEC_Complaint.fromCase(ApexPages.currentPage().getParameters().get('id'));
    } 
    public List<EEC_Question> getQuestions() {
        return EEC_QuestionService.unlicensedComplaintQuestions;
    }

    public LEAD_Configuration__c conf = [
        SELECT 
            Complaints_Introduction__c, Complaint_Form_Redirect__c, Complaints_Confirmation__c 
        FROM 
            LEAD_Configuration__c 
        WHERE 
            Name = :GLOBAL_CONFIG_NAME
    ];
 

    public Date getOneMonthAgo() {
        return Date.today().addMonths(-1);
    }

    public LEAD_Configuration__c getConf() {
        return conf;
    }

    public PageReference noComplaintRedirect() {
        if(ApexPages.currentPage().getParameters().get('id') == NULL && requireComplaint()) {
            return redirectTo(Page.EEC_ComplaintsProviderInfo);
        }
        
        return NULL;
    }

    public virtual Boolean requireComplaint() {
        return true;
    }

    public PageReference back() {
        if(complaint.Id != NULL) {
            upsertComplaint();
        }
        
        return redirectWithId(backPage());
    }
    
    public virtual PageReference backPage() {
        return Page.EEC_ComplaintsIntro;
    }
    
    public PageReference cancel() {
        if(complaint.Id != null) {
            delete complaint.toCase();
        }
        
        return homeRedirect();
    }
    
    public PageReference homeRedirect() { 
        return new PageReference(conf.Complaint_Form_Redirect__c);
    }

    protected void upsertComplaint() {
        Case c = complaint.toCase();
        upsert c;
        complaint = EEC_Complaint.fromCase(c.Id);
    }

    protected PageReference redirectWithId(PageReference pr) {  
        pr.getParameters().put('id', complaint.Id);
        return redirectTo(pr);
    } 

    protected PageReference redirectTo(PageReference pr) {
        pr.setRedirect(true);
        return pr;
    }

}