EEC_InitBackup/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Cases</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Associated Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Required for FCC, LG and SG license applications</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Non_Compliant__c.object
<CustomObject>
    <description>This object is used for non-compliant items outside a visit</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <description>In case of non-compliant item associated to an investigation, this field must be filled.</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipLabel>Non Compliant Item (additional to visit)</relationshipLabel>
        <relationshipName>Non_Compliant_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Non Compliant Item</label>
    <nameField>
        <displayFormat>NC-{00000}</displayFormat>
        <label>Non Compliant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Non Compliant Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_TestInvestigationExtension.cls
@isTest
public with sharing class EEC_TestInvestigationExtension {

    @isTest static void testGetDirectorContact(){
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        Contact c = EEC_TestUtil.mockDirectorContact(a);
        //AccountContactRole acr = EEC_TestUtil.mockAccountContactRole('Director', c, a);
        Investigation__c i = EEC_TestUtil.mockInvestigation(a);
        EEC_GenerateInvCoverLetterExtension cnt = new EEC_GenerateInvCoverLetterExtension(new ApexPages.StandardController(i));
        
        Contact co = cnt.getDirectorContact();
        System.assertEquals(c.FirstName, co.FirstName);
        System.assertEquals(c.LastName, co.LastName);
        System.assertEquals(c.Salutation, co.Salutation); 
    }
    
    /*@isTest static void testGetCaseNumbers(){ 
         Test.startTest();

        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        Contact co = EEC_TestUtil.mockContact();
        
        Case ca1 = EEC_TestUtil.mockCase(a, co);
        Case ca2 = EEC_TestUtil.mockCase(a, co);
        ca1 = [SELECT CaseNumber FROM Case WHERE Id = :ca1.Id];
        ca2 = [SELECT CaseNumber FROM Case WHERE Id = :ca2.Id];
        
        Investigation__c i = EEC_TestUtil.mockInvestigation(a);
        
        ca1.Investigation__c = i.Id; 
        ca2.Investigation__c = i.Id; 
 
        upsert ca1;
        upsert ca2;
 
        EEC_GenerateInvCoverLetterExtension cnt = new EEC_GenerateInvCoverLetterExtension(new ApexPages.StandardController(i));
        
        String result = cnt.getCaseNumbers();
        System.assert(result.contains(ca1.CaseNumber));
        System.assert(result.contains(ca2.CaseNumber));
        Test.stopTest();

    }*/
    
    @isTest static void testGetNonCompliantItems(){ 
        Investigation__c i = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        Non_Compliant__c nc1 = EEC_TestUtil.mockNonCompliant(i);
        Non_Compliant__c nc2 = EEC_TestUtil.mockNonCompliant(i);
        
        Regulation__c r1 = EEC_TestUtil.mockRegulation();
        Regulation__c r2 = EEC_TestUtil.mockRegulation();
        
        EEC_TestUtil.mockNonCompliantItemRegulation(nc1, r1);
        EEC_TestUtil.mockNonCompliantItemRegulation(nc1, r2);
        EEC_TestUtil.mockNonCompliantItemRegulation(nc2, r1);
        
        EEC_GenerateInvCoverLetterExtension cnt = new EEC_GenerateInvCoverLetterExtension(new ApexPages.StandardController(i));
        
        List<EEC_GenerateInvestigationPDFBase.InvestigationVisitChecklistItemWrapper> result = cnt.getNonCompliantItems();
        System.assertEquals(2, result.size());
        System.assert(result.get(0).standardRegulations.contains(r1.Name));
        System.assert(result.get(0).standardRegulations.contains(r2.Name));
        System.assert(result.get(1).standardRegulations.contains(r1.Name));
        System.assert(!result.get(1).standardRegulations.contains(','));
        System.assertEquals(null, result.get(0).inspectionItem);
        System.assertEquals(null, result.get(1).inspectionItem);
    }
    
    /*@isTest static void testGetInspecitonItems(){ 
        Investigation__c inv = EEC_TestUtil.mockInvestigation(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        
        Inspection__c i = EEC_TestUtil.mockInspection(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()));
        i.Investigation__c = inv.Id;
        upsert i;
        
        Standard_Inspection_Item__c stdIi = EEC_TestUtil.mockStdInspectionItem();
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, null);
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), 'Non-Compliant', false, 'HJelp');
        EEC_TestUtil.mockInspectionItem(i, EEC_TestUtil.mockRegulation(), null, true, null);
        EEC_TestUtil.mockInspectionItem(i, stdIi, 'Non-Compliant', false, null);
        EEC_TestUtil.mockInspectionItem(i, stdIi, 'Non-Compliant', false, 'Helo');
        EEC_TestUtil.mockInspectionItem(i, stdIi, null, false, null);
        
        Regulation__c r1 = EEC_TestUtil.mockRegulation();
        Regulation__c r2 = EEC_TestUtil.mockRegulation(); 
        
        EEC_GenerateInvCoverLetterExtension cnt = new EEC_GenerateInvCoverLetterExtension (new ApexPages.StandardController(inv));
        List<EEC_GenerateInvestigationPDFBase.InvestigationVisitChecklistItemWrapper> result = cnt.getInspecitonItems();
        System.assertEquals(4, result.size());
    }*/

    /*@isTest static void testGetOlderCase(){
        Account a = EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity());
        Contact co = EEC_TestUtil.mockContact();
        
        Case ca1 = EEC_TestUtil.mockCase(a, co);
        Case ca2 = EEC_TestUtil.mockCase(a, co);
        ca1 = [SELECT CaseNumber FROM Case WHERE Id = :ca1.Id];
        ca2 = [SELECT CaseNumber FROM Case WHERE Id = :ca2.Id];
        
        Investigation__c i = EEC_TestUtil.mockInvestigation(a);
        
        ca1.Investigation__c = i.Id; 
        ca2.Investigation__c = i.Id; 
 
        upsert ca1;
        upsert ca2;
 
        EEC_GenerateInvCoverLetterExtension cnt = new EEC_GenerateInvCoverLetterExtension(new ApexPages.StandardController(i));
        
        ca1 = [SELECT CreatedDate FROM Case WHERE ID = :ca1.Id];
        
        Datetime result = cnt.getOldestCaseDate(); 
        System.assertEquals(ca1.CreatedDate, result);
    }*/

}