EEC_InitBackup/src/objects/City__c.object
<CustomObject>
    <description>List of MA cities a provider can operate from</description>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OK</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Address_1__c</fullName>
        <description>Address 1</description>
        <inlineHelpText>At creation and if left blank, Address 1 will be populated with Provider address after saving.</inlineHelpText>
        <label>Street Address 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_2__c</fullName>
        <inlineHelpText>At creation and if left blank, Address 2 will be populated with Provider address after saving</inlineHelpText>
        <label>Street Address 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>At creation and if left blank, City will be populated with Provider address after saving</inlineHelpText>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offline_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag checked when the visit has been downloaded to be used on the offline app. Edits to such visit are not authorized</inlineHelpText>
        <label>Offline Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>&quot;MA&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Provide the different stage of an inspection</description>
        <label>Visit Status</label>
        <picklist>
            <picklistValues>
                <fullName>To be scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report to be sent to Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Report Sent to Provider, Awaiting feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback received, to review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Visit_Mode_Lock__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag checked when the visit mode is accessed by a user and remains locked for other users until its released or unlocked by the user.</description>
        <inlineHelpText>This flag checked when the visit mode is accessed by a user and remains locked for other users until its released or unlocked by the user.</inlineHelpText>
        <label>Visit Mode Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <inlineHelpText>At creation and if left blank, Zip Code will be populated with Provider zip code after saving</inlineHelpText>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>validAddress__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Unchecked if no coordinates found using geocoding API</description>
        <label>validAddress</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>visitLatitude__c</fullName>
        <description>Latitude part of geo-coordinates of the visit address</description>
        <label>visitLatitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>visitLongitude__c</fullName>
        <description>Longitude part of geo-coordinates of the visit address</description>
        <label>visitLongitude</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_batchGetVisitCoordinates.cls
global class EEC_batchGetVisitCoordinates implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful{
	String query;
	global EEC_batchGetVisitCoordinates(String queryString) {
		this.query = queryString;
	}
	global EEC_batchGetVisitCoordinates() {
		this.query = 'SELECT ID, Address_1__c, Address_2__c, City__c, State__c, Zip_Code__c, Status__c FROM Inspection__c';
		query += ' WHERE status__c IN (\'Scheduled\',\'To be scheduled\') AND validAddress__c = true';
		query += ' AND visitLongitude__c = null AND Offline_Lock__c = false AND Visit_Mode_Lock__c = false AND Address_1__c != null AND Zip_Code__c != null LIMIT 1';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Inspection__c> visits) {
		for(Inspection__c visit : visits){
			Map<String, String> addressParam = new Map<String, String>();
			addressParam.put('street', visit.Address_1__c);	
			addressParam.put('city', visit.City__c);
			addressParam.put('state', visit.State__c);
			addressParam.put('zipCode', visit.Zip_Code__c);

			Map<String, String> visitCoordinates = new Map<String, String>();

			visitCoordinates = EEC_geoCodeUtility.getLatLng(addressParam);
			
			if(visitCoordinates.get('status') == 'OK'){
				visit.visitLatitude__c = visitCoordinates.get('latitude');
				visit.visitLongitude__c = visitCoordinates.get('longitude');
				System.debug('-----> Visit: ' + visit);
			} else{
				System.debug('----->CoordinatesReceived: ' + visitCoordinates);
				visit.validAddress__c = false;
			}
			try{
				Update visit;
			} catch(Exception e){
				System.debug('-----> Visit Update Failed: ' + e.getMessage());
			}
		}
	}
	
	global void finish(Database.BatchableContext BC) {
		Integer visitWithoutCoordinates = [SELECT Count() 
																				FROM Inspection__c 
																				WHERE status__c IN ('Scheduled','To be scheduled') 
																					AND visitLatitude__c = null AND Offline_Lock__c = false 
																					AND Visit_Mode_Lock__c = false AND Address_1__c != null 
																					AND Zip_Code__c != null AND validAddress__c = true];
		if(!Test.isRunningTest() && visitWithoutCoordinates > 0){
			EEC_batchGetVisitCoordinates visitBatch = new EEC_batchGetVisitCoordinates();
			String cronId = System.scheduleBatch(visitBatch, 'EEC_BatchGetVisitCoordinatesCycle', 1);
			System.debug(cronId);
		}
	}

	/*private static Map<String, String> getCoordinatesFromExisting(Inspection__c newVisit){
		Map<String, String> visitCoordinates = new Map<String, String>();
		List<Inspection__c> existingVisit = new List<Inspection__c>();
		try {
			existingVisit = [SELECT ID, visitLatitude__c, visitLongitude__c FROM Inspection__c 
																WHERE Id !=: newVisit.id AND Address_1__c =: newVisit.Address_1__c AND Zip_Code__c =: newVisit.Zip_Code__c
																	AND visitLongitude__c != null limit 1];
		} catch(Exception e){}

		if(existingVisit.size() > 0){
			visitCoordinates.put('latitude', existingVisit[0].visitLatitude__c);
			visitCoordinates.put('longitude', existingVisit[0].visitLongitude__c);
			visitCoordinates.put('status', 'OK');
		} else {
			visitCoordinates.put('status', 'Not found');
		}
		return visitCoordinates;
	}*/
}