EEC_InitBackup/src/objects/Conditions_and_Limitations__c.object
<CustomObject>
    <fields>
        <fullName>Condition_Additional_Information__c</fullName>
        <inlineHelpText>To be filled if the standard condition selected needs some additional information (ex: Other)</inlineHelpText>
        <label>Condition Additional Information</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Condition_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Condition Name</label>
        <referenceTo>Condition__c</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Condition_On_License__c</fullName>
        <formula>IF ( FIND(&quot;#Effective_Date#&quot;,  Condition_Name__r.Full_Description__c ) &lt;&gt; 0,  

SUBSTITUTE(IF (FIND(&quot;#Add_Info#&quot;, Condition_Name__r.Full_Description__c ) &lt;&gt; 0, SUBSTITUTE(Condition_Name__r.Full_Description__c, &quot;#Add_Info#&quot;,  Condition_Additional_Information__c ), Condition_Name__r.Full_Description__c), &quot;#Effective_Date#&quot;,  TEXT(MONTH( Start_Date__c ))+&quot;/&quot; +TEXT(DAY( Start_Date__c ))+&quot;/&quot; +TEXT(YEAR( Start_Date__c ))),  

IF (FIND(&quot;#Add_Info#&quot;, Condition_Name__r.Full_Description__c ) &lt;&gt; 0, SUBSTITUTE(Condition_Name__r.Full_Description__c, &quot;#Add_Info#&quot;,  Condition_Additional_Information__c ), Condition_Name__r.Full_Description__c))</formula>
        <inlineHelpText>Condition as it&apos;ll be displayed on the license</inlineHelpText>
        <label>Condition Full Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conditions__c</fullName>
        <label>Conditions</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <formula>AND( Start_Date__c &lt;=  TODAY(),
OR(
ISBLANK(Expiration_Date__c), 
 Expiration_Date__c  &gt;= TODAY())
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Source_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Transaction</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Transaction selected must be associated to the provider this condition applies.</errorMessage>
            <filterItems>
                <field>Licensing_Transaction__c.Provider__c</field>
                <operation>equals</operation>
                <valueField>$Source.Provider__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Licensing_Transaction__c</referenceTo>
        <relationshipLabel>Conditions and Limitations</relationshipLabel>
        <relationshipName>Conditions_and_Limitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Conditions and Limitations</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conditions and Limitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Closed__c</fullName>
        <label>Date Transaction Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_LicensingCertificatePDFExtension.cls
public class EEC_LicensingCertificatePDFExtension {
    
    protected final Licensing_Transaction__c trans;
    public Licensing_Transaction__c lt {get;set;}
    public List<Conditions_and_Limitations__c> lstConditions {get;set;}
    
    public EEC_LicensingCertificatePDFExtension(ApexPages.StandardController ctr){
        this.trans = (Licensing_Transaction__c) ctr.getRecord();
        getProviderConditions();
    }
	
    public List<Conditions_and_Limitations__c> getProviderConditions()
    {
        Licensing_Transaction__c lt = [SELECT Id,Capacity__c, Date_Closed__c FROM Licensing_Transaction__c
                                      WHERE Id =: trans.Id];
        lstConditions = [SELECT Conditions__c,Condition_Additional_Information__c,
                         Condition_Name__c,Condition_On_License__c,CreatedById,
                         CreatedDate,Current__c,Expiration_Date__c,Id,
                         Name,Provider__c,Source_Transaction__c,
                         Start_Date__c FROM Conditions_and_Limitations__c 
                         WHERE Provider__c =: trans.Provider__c 
                         AND 
                         (
                             (Start_Date__c <=: lt.Date_Closed__c AND Expiration_Date__c >=: lt.Date_Closed__c) 
                          OR 
                             (Expiration_Date__c = null AND Start_Date__c <=: lt.Date_Closed__c)
                         )];
        
        
        return lstConditions;
    }
}