EEC_InitBackup/src/objects/EEC_HistoricalVisitItemStaging__c.object
<CustomObject>
    <description>Staging table used to load historic Visit Item Data into target object &apos;visit Items&apos;</description>
    <label>HistoricalVisitItemStaging</label>
    <nameField>
        <displayFormat>LVI-{0000}</displayFormat>
        <label>VisitItemStagingId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricalVisitItemStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EEC_HistoricalVisitStaging__c.object
<CustomObject>
    <description>Staging object used to load historic Visit Data into target object &apos;visits&apos;</description>
    <label>HistoricalVisitStaging</label>
    <nameField>
        <displayFormat>LV-{0000}</displayFormat>
        <label>VisitStagingId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricalVisitStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EEC_HistoricalVisitSubItemStaging__c.object
<CustomObject>
    <description>Staging object used to load historic Visit Sub Item Data into target object &apos;visit Items. Observations&apos;</description>
    <label>HistoricalVisitISubItemStaging</label>
    <nameField>
        <displayFormat>LVSI-{0000}</displayFormat>
        <label>VisitSubItemStagingId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoricalVisitSubItemStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/EEC_HistoryOfNonComplianceStaging__c.object
<CustomObject>
    <description>Staging object used to load historic Non Compliance Data into target objects Visits/Visit Items  or Investigation/Additional non-compliance</description>
    <label>HistoryOfNonComplianceStaging</label>
    <nameField>
        <displayFormat>NC-{000000}</displayFormat>
        <label>HistoryOfNonComplianceNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HistoryOfNonComplianceStaging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Inspection__c.object
<CustomObject>
    <description>Manages Inspection records for license, site, violation and other inspection types</description>
    <fields>
        <fullName>Investigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An Investigation may have one or more related Inspections</description>
        <label>Investigation</label>
        <referenceTo>Investigation__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit# {000000}</displayFormat>
        <label>Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Investigation__c.object
<CustomObject>
    <description>Investigations object is used to manage an investigation triggered by either a complaint, incident or 51A form</description>
    <fields>
        <fullName>isLegacyInvestigation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is to indicate that this is a legacy investigation.</description>
        <inlineHelpText>This is to indicate that this is a legacy investigation.</inlineHelpText>
        <label>isLegacyInvestigation</label>
        <type>Checkbox</type>
    </fields>
    <label>Investigation</label>
    <nameField>
        <displayFormat>Inv# {000000}</displayFormat>
        <label>Investigation No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_LEADJobsController.cls
public with sharing class EEC_LEADJobsController {
	
	 //Process LM 2010 Visit/ FCC Mobile Header Data
        public void processLegacyVisits() {
            Database.executeBatch(new EEC_Batch_ProcessLegacyVisits(),1);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Processing Legacy Visits...Please wait... !!!'));
         }  
         
         //Process FCC Mobile Visit Item Data
        public void processLegacyVisitItems() {
            Database.executeBatch(new EEC_Batch_ProcessLegacyVisitItems(),1);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Processing Legacy Visit Items...Please wait... !!!'));
         } 
         
         
          //Process EECRs Non-Complaince Visits Data
        public void processLegacyNonComplianceVisits() {
            Database.executeBatch(new EEC_Batch_ProcessLegacyNonCompVisits(),1);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Processing EECRs Non-compliance Visits...Please wait... !!!'));
         } 
         
            //Process EECRs Non-Complaince Visit Items Data
        public void processLegacyNonComplianceVisitItems() {
            Database.executeBatch(new EEC_Batch_ProcessLegacyNonCompVisitItems(),1);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Processing EECRs Non-compliance visit items...Please wait... !!!'));
         } 
            //This is to clear all staging data if there are any issues with import and need to start over. Qamar
        public void clearAllStagingRecords() {
            List<EEC_HistoricalVisitSubItemStaging__c> hvList1 = [SELECT ID FROM EEC_HistoricalVisitSubItemStaging__c];
            delete hvList1;

            List<EEC_HistoricalVisitItemStaging__c> hvList2 = [SELECT ID FROM EEC_HistoricalVisitItemStaging__c];
            delete hvList2;

            List<EEC_HistoricalVisitStaging__c> hvList3 = [SELECT ID FROM EEC_HistoricalVisitStaging__c];
            delete hvList3;

            List<EEC_HistoryOfNonComplianceStaging__c> hvList4 = [SELECT ID FROM EEC_HistoryOfNonComplianceStaging__c];
            delete hvList4;
        } 

        public void deleteAllLegacyVisits() {
            List<Inspection__c> vList = [SELECT ID FROM Inspection__c WHERE RecordType.Name = 'Legacy System Import Visit / Non Compliance'];
            delete vList;
        } 

        public void deleteAllLegacyInvestigations() {
            List<Investigation__c> vList = [SELECT ID FROM Investigation__c WHERE isLegacyInvestigation__c = true];
            delete vList;
        } 

}