EEC_InitBackup/src/objects/FileMap__c.object
<CustomObject>
    <description>This object contains relation object data for linking s3 file objects with their corresponding parent object.</description>
    <fields>
        <fullName>Object_Id__c</fullName>
        <description>The parent object ID.</description>
        <label>Object Id</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>This is the parent object name.</description>
        <label>Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_File__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is a link to the S3 file object reference.</description>
        <label>S3 File</label>
        <referenceTo>S3_File__c</referenceTo>
        <relationshipLabel>FileMaps</relationshipLabel>
        <relationshipName>FileMaps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>FileMap</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>FileMap Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FileMaps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Renewal</fullName>
        <active>true</active>
        <label>FCC Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/S3_File__c.object
<CustomObject>
    <description>This is an object for storing S3 file representations.</description>
    <fields>
        <fullName>Acl__c</fullName>
        <description>The access control level of the file.</description>
        <label>Acl</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bucket__c</fullName>
        <description>The name of the bucket the file is contained in.</description>
        <label>Bucket</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_Type__c</fullName>
        <description>The content type of the file.</description>
        <label>Content_Type</label>
        <length>125</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filename__c</fullName>
        <description>The name of the file.</description>
        <label>Filename</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <description>The prefix for the file.</description>
        <inlineHelpText>The originating object&apos;s ID typically.</inlineHelpText>
        <label>Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_BaseAttachmentsExtensionTest.cls
@isTest
public class EEC_BaseAttachmentsExtensionTest {
    
  public static void loadMock() {
    EEC_WebServiceMock mockCallout = new EEC_WebServiceMock();
    mockCallout.objectClassName = 'S3.DeleteObjectResponse_element';
    Test.setMock(WebServiceMock.class, mockCallout);
  }
    
  static testMethod void testAttachmentsExtensions() {
      EEC_TestUtil.mockAWSKeys();
      EEC_BaseAttachmentsExtensionTest.loadMock();
      
      Case c = EEC_TestUtil.mockCase(EEC_TestUtil.mockProvider(EEC_TestUtil.mockCity()), EEC_TestUtil.mockContact());
      ApexPages.currentPage().getParameters().put('id', c.Id);
      ApexPages.StandardController std = new ApexPages.StandardController(c);
      Test.startTest();
      EEC_IncidentsAttachmentsExtension incidentController = new EEC_IncidentsAttachmentsExtension(std);
      
      // Test Method
      S3_File__c file = new S3_File__c(
        Filename__c = 'testFile',
        Content_Type__c = 'image/png',
        Bucket__c = 'test',
        Acl__c = 'authenticated-read',
        Prefix__c = c.Id
      ); 
      insert file;  
        
      FileMap__c fileMap = new FileMap__c(
        Object_Id__c = c.Id,
        Object_Name__c = 'Licensing_Transaction__c',
        S3_File__c = file.Id
      );
      insert fileMap;
      
      incidentController.refreshAttachmentsList();
      Test.stopTest();
      System.assertNotEquals(null, incidentController.genetateS3Link(file.Id));
      incidentController.deleteAttachment(file.Filename__c);
      System.assertEquals(new List<S3_File__c>(), [Select Id From S3_File__c Where Id = :file.Id]);
      System.assertEquals(incidentController, incidentController.getCtrlInstance());
    }
    
    static testMethod void testLicenseAttachments() {
      EEC_BaseAttachmentsExtensionTest.loadMock();
      
      Account accnt = loadTestData(Page.EEC_ReviewSummarySubmission,'Apply for License Renewal','1');
      EEC_TransactionWizardController controller = new EEC_TransactionWizardController();
      controller.LicenseRecordTypeName = 'FCC_Renewal';
      Licensing_Transaction__c lic = [select Id from Licensing_Transaction__c where Provider__c = :accnt.Id limit 1];
        
      ApexPages.currentPage().getParameters().put('id', lic.Id);
      ApexPages.StandardController std = new ApexPages.StandardController(lic);  
        
      EEC_LicenseAttachmentsExtension licenseCtrl = new EEC_LicenseAttachmentsExtension(std);  
      Test.startTest();  
      // Test Method
      S3_File__c file = new S3_File__c(
        Filename__c = 'testFile',
        Content_Type__c = 'image/png',
        Bucket__c = 'test',
        Acl__c = 'authenticated-read',
        Prefix__c = lic.Id
      ); 
      insert file;  
        
      S3_File__c file2 = new S3_File__c(
        Filename__c = 'testFile2',
        Content_Type__c = 'image/png',
        Bucket__c = 'test',
        Acl__c = 'authenticated-read',
        Prefix__c = lic.Id
      ); 
      insert file2;  
        
      FileMap__c fileMap = new FileMap__c(
        Object_Id__c = lic.Id,
        Object_Name__c = 'Licensing_Transaction__c',
        S3_File__c = file.Id
      );
      insert fileMap;  
        
      FileMap__c fileMap2 = new FileMap__c(
        Object_Id__c = lic.Id,
        Object_Name__c = 'Licensing_Transaction__c',
        S3_File__c = file2.Id
      );
      insert fileMap2;    
        
      licenseCtrl.refreshAttachmentsList();
      Test.stopTest();
      System.assertNotEquals(null, licenseCtrl.genetateS3Link(file.Id));
      licenseCtrl.deleteAttachment(file.Filename__c);
      System.assertEquals(new List<S3_File__c>(), [Select Id From S3_File__c Where Id = :file.Id]);  
      System.assertEquals(licenseCtrl, licenseCtrl.getCtrlInstance());
      EEC_BaseAttachmentsExtensionTest.testReadOnlyAttachmentCtrl(licenseCtrl, file2);
    }
    
    static void testReadOnlyAttachmentCtrl(AttachActionInterface aif, S3_File__c file) {
      EEC_ReadOnlyAttachmentsCtrl ctrl = new EEC_ReadOnlyAttachmentsCtrl();
      ctrl.aif = aif;
      ctrl.fileToDelete = file.Filename__c;
      ctrl.generateFileId = file.Id;
      ctrl.attachmentsJson = '[{"Filename__c": "TestFile", "Prefix__c": "12345", "Content_Type__c": "image/png", "Acl__c": "authenticated-read", "Bucket__c": "test"}]';
      
      ctrl.genetateS3Link();
      ctrl.deleteAttachment();
      ctrl.saveAttachmentsFromJson();
        
      // Test generateMultiplePolicySignature  
      String exampleJson = '[{"filename": "testName", "type": "image/png"}]'; 
      List<Map<String,String>> result = EEC_ReadOnlyAttachmentsCtrl.generateMultiplePolicySignature('eec', 'authenticated-read', exampleJson);
      System.assertNotEquals(0, result.size());
      System.assertNotEquals(null, result.get(0).get('policy'));  
      System.assertNotEquals(null, result.get(0).get('signature'));
    }
    
    static Account loadTestData(PageReference lPageRef,String buttonLabel, String index){
        Account accnt = EEC_TestUtil.loadLicenseTransaction();
        PageReference pageRef = lPageRef;
        pageRef.getParameters().put('accountId',accnt.Id);
        pageRef.getParameters().put('buttonLabel',buttonLabel);
        pageRef.getParameters().put('index',index);
        Test.setCurrentPage(pageRef);
        EEC_TestUtil.mockAWSKeys();
        return accnt;
    }
}