EEC_InitBackup/src/objects/Inspection_Item__c.object
<CustomObject>
    <description>Inspection Items records (one or more) manage data for an individual Inspection record</description>
    <fields>
        <fullName>Additional_Inspection_Item_Name__c</fullName>
        <description>Allow user to name this additional inspection item</description>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Associated_regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For non standard items, this lookup allows the user to select the regulation associated with this inspection item.</description>
        <label>Associated regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_additional__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Outdoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review of Written Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sleep, Rest, Quiet Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff and Educators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toileting / Diapering / Handwashing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Safety</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_list__c</fullName>
        <description>Domain(Category) used for list.</description>
        <formula>TEXT( Category_additional__c ) &amp; IF(ISPICKVAL(Category_additional__c,&quot;&quot;) , Category_standard__c , &quot;&quot;)</formula>
        <label>Domain (list)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_standard__c</fullName>
        <description>Category of the inspection items</description>
        <formula>text(Standard_Inspection_Item__r.Category__c)</formula>
        <label>Domain</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_Item_Name__c</fullName>
        <formula>Standard_Inspection_Item__r.Name</formula>
        <label>Visit Item Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inspection_No__c</fullName>
        <description>The visit No. field identifies the master Inspection record for the Inspection Item detail record</description>
        <label>Visit No</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inspection_Result__c</fullName>
        <description>This picklist will be used during the visit in order to provide the result of the visit.</description>
        <label>Result</label>
        <picklist>
            <picklistValues>
                <fullName>Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Compliant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Assessed (tool abandoned)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Observations__c</fullName>
        <description>Notes related to the inspection</description>
        <label>Observations</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For standard visit item, this lookup allows the user to associated the inspection item with a standard item.</description>
        <label>Associated Standard Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items</relationshipLabel>
        <relationshipName>Inspection_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Mode_Ranking__c</fullName>
        <inlineHelpText>Allows you to sort visit items as they will be displayed in visit mode and on visit summary. Lowest ranking will be displayed first. Ranking should be set for each item. Items with empty rank will be displayed last.</inlineHelpText>
        <label>Visit Mode Ranking</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visit Item</label>
    <nameField>
        <displayFormat>VI-{000000}</displayFormat>
        <label>Visit Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Standard_Best_Practices__c.object
<CustomObject>
    <fields>
        <fullName>Best_Practice_Guidance__c</fullName>
        <label>Best Practice Guidance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <description>These picklist values are same as the list of domains in the Standard Visit Item</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Child Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Home Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster/Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General records/logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health/Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personnel Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Outdoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Plant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Standard Best Practices</label>
    <nameField>
        <label>Best Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Best Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Visit_Best_Practices__c.object
<CustomObject>
    <fields>
        <fullName>Associated_Visit__c</fullName>
        <label>Associated Visit</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Visit Best Practices</relationshipLabel>
        <relationshipName>Visit_Best_Practices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Best_Practice_Guidance__c</fullName>
        <formula>Best_Practice__r.Best_Practice_Guidance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Best Practice Guidance</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Best_Practice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Best Practice</label>
        <referenceTo>Standard_Best_Practices__c</referenceTo>
        <relationshipLabel>Visit Best Practices</relationshipLabel>
        <relationshipName>Visit_Best_Practices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Observation__c</fullName>
        <label>Observation</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Visit Best Practices</label>
    <nameField>
        <displayFormat>VBP-{0000}</displayFormat>
        <label>Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Best Practices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_GenerateVisitChecklistExtension.cls
public with sharing class EEC_GenerateVisitChecklistExtension extends EEC_GeneratePDFBase {

  public List<VisitChecklistItemWrapper> nonCompliantAssessedItems { get; set; }
  public List<VisitChecklistItemWrapper> compliantAssessedItems { get; set; }
  public List<VisitChecklistItemWrapper> compliantnoobservation { get; set; }
  public Map<String, Integer> domainComplianceCountMap { get; set; }
  public Map<String, Integer> domainComplianceTotalCountMap { get; set; }
  public Integer assessedItemsTotal { get; set; }
  public List<Inspection_Item__c> compliantwithobservation { get; set; }
  public List<Inspection_Item__c> compliantwithoutobservation { get; set; }

  public EEC_GenerateVisitChecklistExtension(ApexPages.StandardController stdController) {
    super(stdController);
    // Get the assessed items.
    nonCompliantAssessedItems = getAssessedStandardInspectionItemsWithStatus('Non-Compliant');
    compliantAssessedItems = getComplianceitemsWithObservation('Compliant');
    compliantnoobservation = getComplianceitemsWithoutObservation('Compliant');
  }

  public List<VisitChecklistItemWrapper> getAssessedStandardInspectionItems() {
    List<Inspection_Item__c> rows = [
                                     SELECT Associated_regulation__r.Name,Non_Assessed_Item__c,  Standard_Inspection_Item__c, Standard_Inspection_Item__r.Description__c,Visit_Mode_Ranking__c,
                                     Inspection_Item_Name__c, Category_list__c, Additional_Inspection_Item_Name__c, Category_standard__c, Inspection_Result__c, Observations__c,
                                     Category_additional__c
                                     FROM Inspection_Item__c
                                     WHERE Inspection_No__c = :visit.Id AND Non_Assessed_Item__c = false ];

    return augmentStandardInspectionItems(rows);
  }

  public List<VisitChecklistItemWrapper> getUnassessedStandardInspectionItems() {
    List<Inspection_Item__c> rows = [
                                     SELECT Associated_regulation__r.Name,Non_Assessed_Item__c, Standard_Inspection_Item__c, Inspection_Item_Name__c, Standard_Inspection_Item__r.Description__c,
                                     Additional_Inspection_Item_Name__c, Category_list__c, Category_standard__c, Observations__c, Category_additional__c
                                     FROM Inspection_Item__c
                                     WHERE Inspection_No__c = :visit.Id AND Non_Assessed_Item__c = true];

    return augmentStandardInspectionItems(rows);
  }

  /**
   * getTypeOfVisitHeaderText
   *
   * @description This function will determine the type of header text that should show up on V2 of the checklist pdf.
   * @author Darkis
   * @return String  
   */
  public String getTypeOfVisitHeaderText() {
    String typeOfVisit = this.visit.Type_of_Visit__c;

    if (typeOfVisit.equalsIgnoreCase('Monitoring') || typeOfVisit.equalsIgnoreCase('Enhanced Monitoring')) {
      return '';
    }

    if (typeOfVisit.contains('Renewal')) {
      return 'Renewal -';
    }
    return typeOfVisit + ' -';
  }

  public Boolean getNonComplaintAvailable() {
    return nonCompliantAssessedItems.size() > 0 ? true : false;
  }

  public Boolean getComplaintAvailable() {
    return compliantAssessedItems.size() > 0 ? true : false;
  }
  public Boolean getComplaintNoobservationAvailable() {
    return compliantnoobservation.size() > 0 ? true : false;
  }

  public Boolean getTechnicalAssistanceAvailable() {
    return this.getAdditionalInspectionItems().size() > 0 ? true : false;
  }

  public Set<String> getVisitOutcomesSummary() {
    // Get all assessed items for the visit.
    List<VisitChecklistItemWrapper> assessedItems = getAssessedStandardInspectionItems();
    assessedItemsTotal = assessedItems.size();
    List<String> applicableDomains = new List<String> ();
    domainComplianceCountMap = new Map<String, Integer> ();
    domainComplianceTotalCountMap = new Map<String, Integer> ();
    // 1. Loop through items
    for (VisitChecklistItemWrapper visitItemWrapper : assessedItems) {
      String domain = visitItemWrapper.inspectionItem.Category_list__c;
      // 2. Check if the item is observed compliant
      String result = String.valueOf(visitItemWrapper.inspectionItem.Inspection_Result__c);
      if (!String.isBlank(result) && result.equalsIgnoreCase('compliant')) {
        // 3. If Complaint then increment the mapping total.
        if (domainComplianceCountMap.containsKey(domain)) {
          domainComplianceCountMap.put(domain, domainComplianceCountMap.get(domain) + 1);
        } else {
          domainComplianceCountMap.put(domain, 1);
        }
      }

      if (!String.isBlank(result) && !domainComplianceCountMap.containsKey(domain)) {
        domainComplianceCountMap.put(domain, 0);
      }
	  if(!String.isBlank(result) && (result.equalsIgnoreCase('compliant') || result.equalsIgnoreCase('non-compliant'))){
          if (domainComplianceTotalCountMap.containsKey(domain)) {
            domainComplianceTotalCountMap.put(domain, domainComplianceTotalCountMap.get(domain) + 1);
          }
          else {
            domainComplianceTotalCountMap.put(domain, 1);
      	  }   
      }
      else if(!String.isBlank(result) && !domainComplianceTotalCountMap.containsKey(domain)){
            domainComplianceTotalCountMap.put(domain, 0);
      }  
    }
    // 4. Return the string list of domains that will then use the mapping to present the result. 
    return domainComplianceCountMap.keySet();
  }

  public List<Visit_Best_Practices__c> getVisitBestPractices() { 
    return[Select Best_Practice_Guidance__c, Observation__c, Best_Practice__r.Domain__c From Visit_Best_Practices__c Where Associated_Visit__c = : visit.Id];
  }

  private List<VisitChecklistItemWrapper> getAssessedStandardInspectionItemsWithStatus(String status) {
    List<Inspection_Item__c> rows = [
                                     SELECT Associated_regulation__r.Name,Non_Assessed_Item__c, Standard_Inspection_Item__c, Standard_Inspection_Item__r.Description__c,Visit_Mode_Ranking__c,
                                     Inspection_Item_Name__c, Category_list__c, Additional_Inspection_Item_Name__c, Category_standard__c, Inspection_Result__c, Observations__c,
                                     Category_additional__c
                                     FROM Inspection_Item__c
                                     WHERE Inspection_No__c = :visit.Id AND Non_Assessed_Item__c = false AND Inspection_Result__c = :status order by Visit_Mode_Ranking__c asc nulls last];

    return augmentStandardInspectionItems(rows);
  }
  private List<VisitChecklistItemWrapper> getComplianceitemsWithObservation(String status) {
  	compliantwithobservation=new list<Inspection_Item__c>();
    for(Inspection_Item__c Items : [SELECT Associated_regulation__r.Name,Non_Assessed_Item__c, Standard_Inspection_Item__c, Standard_Inspection_Item__r.Description__c,Visit_Mode_Ranking__c,
                                     Inspection_Item_Name__c, Category_list__c, Additional_Inspection_Item_Name__c, Category_standard__c, Inspection_Result__c, Observations__c,
                                     Category_additional__c
                                     FROM Inspection_Item__c
                                     WHERE Inspection_No__c = :visit.Id AND Non_Assessed_Item__c = false AND Inspection_Result__c = :status order by Visit_Mode_Ranking__c asc nulls last])
          {
          	if(String.isNotBlank(items.Observations__c)){
            	compliantwithobservation.add(items);
            }
                                     
       }

    return augmentStandardInspectionItems(compliantwithobservation);
  }
  private List<VisitChecklistItemWrapper> getComplianceitemsWithoutObservation(String status) {
  	compliantwithoutobservation=new list<Inspection_Item__c>();
    for(Inspection_Item__c Items : [SELECT Associated_regulation__r.Name,Non_Assessed_Item__c, Standard_Inspection_Item__c, Standard_Inspection_Item__r.Description__c,Visit_Mode_Ranking__c,
                                     Inspection_Item_Name__c, Category_list__c, Additional_Inspection_Item_Name__c, Category_standard__c, Inspection_Result__c, Observations__c,
                                     Category_additional__c
                                     FROM Inspection_Item__c
                                     WHERE Inspection_No__c = :visit.Id AND Non_Assessed_Item__c = false AND Inspection_Result__c = :status order by Visit_Mode_Ranking__c asc nulls last])
          {
          	if(String.isBlank(items.Observations__c)){
            	compliantwithoutobservation.add(items);
            }
                                     
       }

    return augmentStandardInspectionItems(compliantwithoutobservation);
  }
}