EEC_InitBackup/src/objects/Involved_Persons__c.object
<CustomObject>
    <description>This object will be used to capture the involved persons in a Complaint or a Incident.</description>
    <fields>
        <fullName>Age__c</fullName>
        <inlineHelpText>If child, please provide the (estimated) age of the child.</inlineHelpText>
        <label>Age</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Child_birth_date__c</fullName>
        <label>Child&apos;s birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_of_involvement__c</fullName>
        <inlineHelpText>Describe briefly the involvement of this person in the complaint / incident</inlineHelpText>
        <label>Description of involvement</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Involved_In__c</fullName>
        <description>Case this person is involved in</description>
        <label>Involved In</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Involved Persons</relationshipLabel>
        <relationshipName>Involved_Persons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Role__c</fullName>
        <description>To be filled if the chosen role is &quot;Other&quot;</description>
        <inlineHelpText>Please detail the role of this person in case you chose &quot;Other&quot;</inlineHelpText>
        <label>Other Role</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Address__c</fullName>
        <label>Parent/Guardian&apos;s Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Name__c</fullName>
        <label>Parent/Guardian&apos;s Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Guardian_Telephone_Number__c</fullName>
        <label>Parent/Guardian&apos;s Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Educator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provider Staff People</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Witness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Members of a Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Members of another Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Police Department</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource and Referral Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <inlineHelpText>Title of this person</inlineHelpText>
        <label>Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Involved Person</label>
    <nameField>
        <label>First and Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Involved Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_ComplaintsInformationController.cls
public without sharing class EEC_ComplaintsInformationController extends EEC_BaseComplaintsController { 
 
    public List<Involved_Persons__c> involvedPersons { get; set; }
    public Integer personToRemove { get; set; }
    
    public EEC_ComplaintsInformationController() {
        involvedPersons = [ 
            SELECT 
                Name, RecordType.Name, Child_birth_date__c, Parent_Guardian_Name__c, Parent_Guardian_Address__c, 
                Parent_Guardian_Telephone_Number__c, Role__c, Other_Role__c, Title__c, Description_of_involvement__c,Age__c 
            FROM 
                Involved_Persons__c
            WHERE 
                Involved_In__c = :complaint.Id
        ];
                
    } 
    private Id adultInvolvement = Schema.SObjectType.Involved_Persons__c.getRecordTypeInfosByName().get('Adult Involvement').getRecordTypeId();

    public void addInvolved() {   
        involvedPersons.add(new Involved_Persons__c(Involved_In__c = complaint.Id, Name = null)); 
    }

    public PageReference goToComplainerInfo() {
        upsert involvedPersons;
        upsertComplaint();
        return redirectWithId(Page.EEC_ComplaintReporterInfo);
    }

    public override PageReference backPage() {
        return Page.EEC_ComplaintsProviderInfo;
    }

    public void removeInvolved() {
        Involved_Persons__c ip = involvedPersons[personToRemove];
        
        if(ip.Id != NULL) {
            delete ip;
        }
        
        involvedPersons.remove(personToRemove);
    }

    public List<EEC_Question> getComplaintInformationQuestions() {
        return EEC_QuestionService.complaintInfoDescrQuestions;
    }

    public List<EEC_Question> getInvolvedQuestions() {
        return EEC_QuestionService.complaintInfoInvolvedQuestions(); 
    }

    public List<EEC_Question> getDCFFilingQuestions() {
        return EEC_QuestionService.complaintFilling; 
    }

    public List<EEC_Question> getSharedQuestions() {
        return EEC_QuestionService.complaintSharedProvider;  
    }

    public List<EEC_Question> getOtherInformationQuestions () {
        return EEC_QuestionService.complaintInformationOtherQuestions ;  
    }
}