EEC_InitBackup/src/objects/Junction_ChklInsp__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Checklist Reference and Standard Visit Items objects</description>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Random_Item_Domain__c</fullName>
        <inlineHelpText>Domain name that is used in case of Random Items. These can vary as most random items are associated to standard items in longer visit tools which contains more detailed domains.</inlineHelpText>
        <label>Random Item Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Plant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Space (Indoor &amp; Outdoor)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routine &amp; Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Random_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this item will be only added if picked as random by the system when using this tool.</inlineHelpText>
        <label>Random Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Checklist_Reference__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Tool Reference object and the detail JunctionChklInsp object</description>
        <label>Tool</label>
        <referenceTo>Standard_Checklist_Reference__c</referenceTo>
        <relationshipLabel>Associated Visit Items</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionChklInsp object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Tool Assignments</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Visit_Mode_Ranking__c</fullName>
        <inlineHelpText>Allows you to sort visit items as they will be displayed in visit mode and on visit summary. Lowest ranking will be displayed first. Ranking should be set for each item. Items with empty rank will be displayed last.</inlineHelpText>
        <label>Visit Mode Ranking</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tools Visit Items</label>
    <nameField>
        <displayFormat>JunctCI# {000000}</displayFormat>
        <label>JunctCINo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Junction_InspReg__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Visit Items and Regulations objects</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <description>This field implements the master-detail relationship between the master Regulation object and the detail JunctionInspReg object</description>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Associated Standard Visit Items</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionInspReg object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items Regulation</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Items Regulation</label>
    <nameField>
        <displayFormat>VIR# {000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items Regulation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>FCC_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>FCC High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GSA_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>GSA High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this checklist applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of how and when this checklist should be used.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Provide information related to the category of inspection items that could be used later to organize inspection items during a visit</description>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>BRC Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curriculum and Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipments and Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Involvement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infection Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inspections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mealtime, Food, Food Preparation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Hygiene</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Indoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Facility - Outdoors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Progress Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review of Written Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sleep, Rest, Quiet Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff and Educators</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toileting / Diapering / Handwashing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Safety</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the items to inspect</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Guidance__c</fullName>
        <label>Guidance</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_ToolVisitItems.cls
public with sharing class EEC_ToolVisitItems {
        public ID Toolid;
        private final Standard_Checklist_Reference__c Toolrecord;
        public list< Junction_ChklInsp__c>ToolItemList=new list<Junction_ChklInsp__c>();
        public list< Junction_ChklInsp__c>Totallist=new list<Junction_ChklInsp__c>();
        public list< Junction_InspReg__c>RegList=new list<Junction_InspReg__c>();
        public boolean key=false;
        public list< Standard_Inspection_Item__c>Stditemlist=new list<Standard_Inspection_Item__c>();
        public Set<Id> siSet = new Set<Id> ();
        public List<ToolWrapper> ToolWrapperlist { get; set; }
        public string applicableto;
        
        public EEC_ToolVisitItems(ApexPages.StandardController controller){
                this.Toolrecord = (Standard_Checklist_Reference__c) controller.getRecord();
                Toolid = Toolrecord.id;
                //applicableto=toolrecord.Applicable_To__c;
                system.debug('MMMMM'+Toolid);
                ToolItemList();
        }
        public pageReference redirect(){
                pageReference PREF= new pageReference('/'+Toolid);
                return PREF;
        }
    public class ToolWrapper implements Comparable {
        public Id Id { get; set; }
        public Standard_Inspection_Item__c sinspobj { get; set; }
        public String name { get; set; }
        public Integer rowIndex { get; set; }
        public String description { get; set; }
        public String domain { get; set; }
        public boolean nonassesseditem { get; set; }
        public boolean randomitem { get; set; }
        public boolean KeyIndicator { get; set; }
        public boolean FCCKey { get; set; }
        public boolean GSAKey { get; set; }
        public boolean RPKey { get; set; }
        public list< Junction_ChklInsp__c>ToolItemListW=new list<Junction_ChklInsp__c>();
        public list< Junction_ChklInsp__c>ToolItemList=new list<Junction_ChklInsp__c>();
        public Map<String, Id> regulationMap { get; set; }
        public String guidance { get; set; }
        public String applicableto { get; set; }
        public Id TId { get; set; }
        public Decimal ModeRank { get; set; }
        public Map<Id,Regulation__c> Checkmap{get;set;}
        
        public Integer compareTo(Object compareTo){
        	ToolWrapper WrapCompare = (ToolWrapper)compareTo;
        	system.debug('AAAAAA');
        	if(ModeRank<WrapCompare.ModeRank){
                return -1;
              }
           	else if(ModeRank>WrapCompare.ModeRank){
                return 1;
           	}
            else {
                if(KeyIndicator)
                 return -1;
               else if(WrapCompare.KeyIndicator)
                 return 1;
               else{
               	 if(randomitem){
               	 	 return 1;
               	 }else if(WrapCompare.randomitem){ 
               	 	 return -1;
               	}else{
                 if(name>WrapCompare.name){
                 	return -1;
                 }else if(name<WrapCompare.name){
                 	return 1;
                }else{
                	return 0;
               }
             }
           }
         }
      }
        public ToolWrapper(Standard_Inspection_Item__c sinsp, Map<Id, Map<String, String>> iRegMap,map<id,Junction_ChklInsp__c>titemmap,Map<id,map<id,Regulation__c>> STRmap,string Tool) {
                this.Id = sinsp.Id;
                this.sinspobj=sinsp;
                this.name = sinsp.name;
                this.description = sinsp.Description__c;
                this.rowIndex = rowIndex;
                //this.regulationMap = null;
                this.regulationMap = iRegMap.get(Id);
                this.checkmap=STRmap.get(Id);
                system.debug('Checkmap'+this.checkmap);
                this.keyindicator=false;
                this.FCCkey=false;
                this.GSAkey=false;
                this.RPkey=false;
                this.guidance = sinsp.Guidance__c;
                this.applicableto=tool;
                //this.Tid= tool.id;
                //ToolItemListW=[select id,name,Standard_Checklist_Reference__c,Random_Item__c,Random_Item_Domain__c,Standard_Inspection_Item__c from Junction_ChklInsp__c where Standard_Inspection_Item__c=:this.Id and Standard_Checklist_Reference__c =: this.tid and Random_Item__c=true];
                     if(titemmap.get(this.id).Random_Item__c==false){
                         this.domain = sinsp.Category__c;
                       }else{
                         this.domain = titemmap.get(this.id).Random_Item_Domain__c;
                       }
                       
                      if(titemmap.get(this.id).Visit_Mode_Ranking__c == null){
                         this.ModeRank = 99999;
                       }else{
                         this.ModeRank = titemmap.get(this.id).Visit_Mode_Ranking__c;
                       }
                       
                         this.nonassesseditem = titemmap.get(this.id).Non_Assessed_Item__c;
                         this.randomitem = titemmap.get(this.id).Random_Item__c;
                         system.debug('Assessed'+this.nonassesseditem);
           if(STRmap.get(this.Id) != null){     
            for(Regulation__c r: STRmap.get(this.Id).values()){
                if(!this.keyindicator && r.FCC_High_Risk_Reg__c && this.applicableto.contains('Family Child Care')){
                    this.keyindicator=true;
                }else
                if(!this.keyindicator && r.GSA_High_Risk_Reg__c&& (this.applicableto.contains('Large Group')||this.applicableto.contains('Small Group'))){
                 this.keyindicator=true;
                }else
                if(!this.keyindicator && r.R_P_High_Risk_Reg__c && (this.applicableto.contains('Foster Care Agency')||this.applicableto.contains('Adoption Agency')||this.applicableto.contains('Temporary Shelter')||this.applicableto.contains('Group Care'))){
                this.keyindicator=true;
                }
            }
           }
            /*for(Junction_ChklInsp__c J: [select id,name,Standard_Checklist_Reference__c,Standard_Checklist_Reference__r.Applicable_To__c,Standard_Inspection_Item__c from Junction_ChklInsp__c where Standard_Inspection_Item__c =: this.id and Standard_Checklist_Reference__c =:this.tid]){
                if(J.Standard_Checklist_Reference__r.Applicable_To__c.contains('Family Child Care') &&this.FCCkey){
                this.keyindicator=true;
                }else
                if(J.Standard_Checklist_Reference__r.Applicable_To__c.contains('Small Group')||J.Standard_Checklist_Reference__r.Applicable_To__c.contains('Large Group')&& this.GSAkey){
                this.keyindicator=true;
                }
            
            }*/
            
        }
        }
    
        public list<ToolWrapper> ToolItemList(){
                ToolWrapperlist = new list<ToolWrapper>();
                ToolItemList=[select id,name,Standard_Checklist_Reference__c,Standard_Inspection_Item__c,Standard_Checklist_Reference__r.Applicable_To__c,Random_Item__c from Junction_ChklInsp__c where Standard_Checklist_Reference__c=:Toolid];
                
        for(Junction_ChklInsp__c TL :ToolItemList ){
                siSet.add(TL.Standard_Inspection_Item__c);
                applicableto=TL.Standard_Checklist_Reference__r.Applicable_To__c;
        }
        TotalList=[select id,name,Standard_Checklist_Reference__c,Standard_Checklist_Reference__r.Applicable_To__c,Visit_Mode_Ranking__c,Non_Assessed_Item__c,Random_Item__c,Random_Item_Domain__c,Standard_Inspection_Item__c from Junction_ChklInsp__c where Standard_Inspection_Item__c in:siSet and Standard_Checklist_Reference__c =: Toolid];
        map<id,Junction_ChklInsp__c> toolitemmap=new map<id,Junction_ChklInsp__c>();
        for(Junction_ChklInsp__c J : Totallist){
        toolitemmap.put(J.Standard_Inspection_Item__c,J);
        }
        Stditemlist=[select id,name,Description__c,Category__c,guidance__c from Standard_Inspection_Item__c where id IN: siSet];
        Map<Id, Map<String, Id>> iregulationMap = new Map<Id, Map<String, String>> ();
        Map<String, String> jiMap;
        Map<id, Regulation__c> jiMap2;
        set<id> regset = new set<id>();
        map<id,Regulation__c> regmap = new map <id,Regulation__c>();
        map<id,map<id,Regulation__c>> SRmap = new map <id,map<id,Regulation__c>>();
            for (Junction_InspReg__c jir :[select Id, Regulation__c, Regulation__r.name, Regulation__r.article__c, Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c in :siSet]) {
                        regset.add(jir.Regulation__c);
            if (iregulationMap.containsKey(jir.Standard_Inspection_Item__c)) {
                iregulationMap.get(jir.Standard_Inspection_Item__c).put(jir.Regulation__r.name + ',', jir.Regulation__c);
            }
            else {
                jiMap = new Map<String, String> ();
                jiMap.put(jir.Regulation__r.name + ',', jir.Regulation__c);
                iregulationMap.put(jir.Standard_Inspection_Item__c, jiMap);
            }
         }
         for(Regulation__c R: [select id,name,FCC_High_Risk_Reg__c,GSA_High_Risk_Reg__c,R_P_High_Risk_Reg__c from Regulation__c where id IN: regset]){
                regmap.put(R.id,R);
         }         
         for (Junction_InspReg__c jir :[select Id, Regulation__c, Regulation__r.name, Regulation__r.article__c, Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c IN: siset and Regulation__c IN:regset ]) {
                if (SRmap.containsKey(jir.Standard_Inspection_Item__c)) {
                SRmap.get(jir.Standard_Inspection_Item__c).put(jir.Regulation__c, regmap.get(jir.Regulation__c));
            }
            else {
                jiMap2=new Map<id, Regulation__c>();
                jiMap2.put(jir.Regulation__c, regmap.get(jir.Regulation__c));
                SRmap.put(jir.Standard_Inspection_Item__c, jiMap2);
            }
         }         
        
        for(Standard_Inspection_Item__c SI :Stditemlist ){
                system.debug(SI.id+SI.name+'MMMMMMMM');
                ToolWrapper newWrapper = new ToolWrapper(SI, iregulationMap,toolitemmap,SRmap,applicableto);
                ToolWrapperlist.add(newWrapper);
                ToolWrapperlist.sort();
        }
        
   return ToolWrapperlist;
   }
}