EEC_InitBackup/src/objects/Junction_InspReg__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Visit Items and Regulations objects</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <description>This field implements the master-detail relationship between the master Regulation object and the detail JunctionInspReg object</description>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Associated Standard Visit Items</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionInspReg object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items Regulation</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Items Regulation</label>
    <nameField>
        <displayFormat>VIR# {000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items Regulation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_StandardItemRegulationsCtrlTest.cls
/**
 * EEC_StandardItemRegulationsCtrlTest
 * 
 * This test class covers the unit test behaviours for the EEC_StandardItemRegulationsController class.
 * @author Darkis
 */

@isTest
private class EEC_StandardItemRegulationsCtrlTest {
	
    static testMethod void testGetRegulationNames() {
        Standard_Inspection_Item__c stdInspectItem = EEC_TestUtil.mockStdInspectionItem();
        Junction_InspReg__c mockJuncObj = EEC_TestUtil.mockRegStdInsp(EEC_TestUtil.mockRegulation(), stdInspectItem);
        
        EEC_StandardItemRegulationsController controller = new EEC_StandardItemRegulationsController();
        controller.itemId = stdInspectItem.Id;
        
        System.debug('Result of request: ' + controller.getRegulationNames());        
        
        Junction_InspReg__c inspReg = [SELECT Regulation__r.Name FROM Junction_InspReg__c WHERE Standard_Inspection_Item__c = :stdInspectItem.Id];
        System.assertEquals(inspReg.Regulation__r.Name, controller.getRegulationNames());
    }
}