EEC_InitBackup/src/objects/Junction_ChklInsp__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Checklist Reference and Standard Visit Items objects</description>
    <fields>
        <fullName>Non_Assessed_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, it means that this visit item is only for information and does not need to be assessed during the visit</description>
        <inlineHelpText>If checked, this visit item is only for information and does not need to be assessed during the visit</inlineHelpText>
        <label>Non-Assessed Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Random_Item_Domain__c</fullName>
        <inlineHelpText>Domain name that is used in case of Random Items. These can vary as most random items are associated to standard items in longer visit tools which contains more detailed domains.</inlineHelpText>
        <label>Random Item Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoptive Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavior Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birth Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Care of Children</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Administration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Children Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Plant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Space (Indoor &amp; Outdoor)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Records</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Routine &amp; Activities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Random_Item__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this item will be only added if picked as random by the system when using this tool.</inlineHelpText>
        <label>Random Item</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_Checklist_Reference__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Tool Reference object and the detail JunctionChklInsp object</description>
        <label>Tool</label>
        <referenceTo>Standard_Checklist_Reference__c</referenceTo>
        <relationshipLabel>Associated Visit Items</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionChklInsp object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Tool Assignments</relationshipLabel>
        <relationshipName>Junction_ChklInsps</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tools Visit Items</label>
    <nameField>
        <displayFormat>JunctCI# {000000}</displayFormat>
        <label>JunctCINo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Visit Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Junction_InspReg__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Standard Visit Items and Regulations objects</description>
    <fields>
        <fullName>Regulation__c</fullName>
        <description>This field implements the master-detail relationship between the master Regulation object and the detail JunctionInspReg object</description>
        <label>Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Associated Standard Visit Items</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Standard_Inspection_Item__c</fullName>
        <description>This field implements the master-detail relationship between the master Standard Inspection Item object and the detail JunctionInspReg object</description>
        <label>Standard Visit Item</label>
        <referenceTo>Standard_Inspection_Item__c</referenceTo>
        <relationshipLabel>Visit Items Regulation</relationshipLabel>
        <relationshipName>Junction_InspRegs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visit Items Regulation</label>
    <nameField>
        <displayFormat>VIR# {000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Items Regulation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Article__c</fullName>
        <description>Regulation article</description>
        <label>Article</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Active__c</fullName>
        <description>Date this regulation must be applied</description>
        <inlineHelpText>Date this regulation must be applied by Provider</inlineHelpText>
        <label>Date Active</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FCC_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>FCC High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>GSA_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>GSA High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>R_P_High_Risk_Reg__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any non-compliance associated with this regulation will be counted as a substantiated non-compliance for the selection of the visit tool to use during monitoring / progress / enhanced monitoring visits.</inlineHelpText>
        <label>R&amp;P High Risk Reg</label>
        <type>Checkbox</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Checklist_Reference__c.object
<CustomObject>
    <description>Standard Checklist Reference object manages standard inspection checklists for all Provider Types</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this checklist applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>No_of_Random_Items_Per_Domain_to_Pick__c</fullName>
        <inlineHelpText>Number of Random Items that should be added to the visit tool key indicators when this visit tool is used. Select &quot;0&quot; if no random item should be added.</inlineHelpText>
        <label>No. of Random Items Per Domain to Pick</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Visit Tool</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/objects/Standard_Inspection_Item__c.object
<CustomObject>
    <description>The Standard Visit Items object manages data for each Provider Type&apos;s standard visit checklist</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this inspection item applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Standard Visit Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Visit Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EEC_Toolvisititemstest.cls
@isTest
private class EEC_Toolvisititemstest {
	static testMethod void testToolvisititem() {
    Standard_Checklist_Reference__c Tool = new Standard_Checklist_Reference__c(Name = 'Test',No_of_Random_Items_Per_Domain_to_Pick__c=2);
    string toolid= Tool.id;
    insert Tool;
    Standard_Inspection_Item__c SI = new Standard_Inspection_Item__c(name='SITEST');
    insert SI;
    Junction_ChklInsp__c JI= new Junction_ChklInsp__c(Standard_Inspection_Item__c=SI.id,Standard_Checklist_Reference__c=Tool.id,Non_Assessed_Item__c=true,Random_Item__c=false);
    insert JI;
    Regulation__c R = new Regulation__c(name='TestR',Date_Active__c=date.today());
    insert R;
    Junction_InspReg__c JR = new Junction_InspReg__c(Standard_Inspection_Item__c=SI.id,Regulation__c=R.id);
    insert JR;
    ApexPages.StandardController sc = new ApexPages.StandardController(Tool);
    EEC_ToolVisitItems ctr = new EEC_ToolVisitItems(sc);
    List<EEC_ToolVisitItems.ToolWrapper> iiWrapperList = new List<EEC_ToolVisitItems.ToolWrapper>();
    Map<Id, Map<String, Id>> iregulationMap = new Map<Id, Map<String, String>> ();
    Map<String, String> jiMap = new map<String, String>();
        Map<id, Regulation__c> jiMap2=new map <id, Regulation__c>();
    for (Junction_InspReg__c jir :[select Id, Regulation__c, Regulation__r.name, Regulation__r.article__c, Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c  =:SI.id]) {
			
            if (iregulationMap.containsKey(jir.Standard_Inspection_Item__c)) {
             	iregulationMap.get(jir.Standard_Inspection_Item__c).put(jir.Regulation__r.name + ',', jir.Regulation__c);
            }
            else {
            	jiMap = new Map<String, String> ();
                jiMap.put(jir.Regulation__r.name + ',', jir.Regulation__c);
                iregulationMap.put(jir.Standard_Inspection_Item__c, jiMap);
            }
         }
     map<id,Junction_ChklInsp__c> toolitemmap=new map<id,Junction_ChklInsp__c>();
     for(Junction_ChklInsp__c J : [select id,name,Standard_Checklist_Reference__c,Standard_Checklist_Reference__r.Applicable_To__c,Non_Assessed_Item__c,Random_Item__c,Random_Item_Domain__c,Standard_Inspection_Item__c from Junction_ChklInsp__c where Standard_Inspection_Item__c =:si.id and Standard_Checklist_Reference__c =: Tool.id]){
     	toolitemmap.put(J.Standard_Inspection_Item__c,J);
     	}
     map<id,Regulation__c> regmap = new map <id,Regulation__c>();
     for(Regulation__c Re: [select id,name,FCC_High_Risk_Reg__c,GSA_High_Risk_Reg__c,R_P_High_Risk_Reg__c from Regulation__c where id =: R.id]){
         	regmap.put(Re.id,Re);
         }
    	map<id,map<id,Regulation__c>> SRmap = new map <id,map<id,Regulation__c>>();
    for (Junction_InspReg__c jir :[select Id, Regulation__c, Regulation__r.name, Regulation__r.article__c, Standard_Inspection_Item__c from Junction_InspReg__c where Standard_Inspection_Item__c =: si.id and Regulation__c =:R.id ]) {
         	if (SRmap.containsKey(jir.Standard_Inspection_Item__c)) {
             	SRmap.get(jir.Standard_Inspection_Item__c).put(jir.Regulation__c, regmap.get(jir.Regulation__c));
            }
            else {
            	jiMap2=new Map<id, Regulation__c>();
                jiMap2.put(jir.Regulation__c, regmap.get(jir.Regulation__c));
                SRmap.put(jir.Standard_Inspection_Item__c, jiMap2);
            }
         }
     Test.startTest();
     ctr.ToolItemList();
     iiWrapperList.add(new EEC_ToolVisitItems.ToolWrapper(SI,iregulationmap,toolitemmap,SRMap,toolid));
     ctr.redirect();
    Test.stopTest();
    }
}