EEC_InitBackup/src/objects/Licensing_Transaction__c.object
<CustomObject>
    <description>Licenses object is used to manage license applications and provisional and full licenses.</description>
    <fields>
        <fullName>Provider__c</fullName>
        <label>Provider</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notContain</operation>
                <value>Umbrella</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Licensing Transactions</relationshipLabel>
        <relationshipName>Licensing_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>To Submit</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Manager Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved By Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (Processed)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed (License Issued / Updated)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Licensing_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Licensing Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Licensing Transactions</pluralLabel>
    <recordTypes>
        <fullName>FCC_Change_of_Household</fullName>
        <active>true</active>
        <label>FCC Change of Household</label>
    </recordTypes>
    <recordTypes>
        <fullName>FCC_Renewal</fullName>
        <active>true</active>
        <label>FCC Renewal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EEC_TestLicensingTransactionTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class EEC_TestLicensingTransactionTrigger {

    static testMethod void testLicensingTransactionTrigger() {
    	EEC_TestUtil.mockLeadConfig('Family Child Care', null);
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.MockCity());
        RecordType r = [select Id from RecordType where DeveloperName='FCC_Change_of_Household' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
    	
    }
   
   /*static testMethod void testLTRenewal() {
    	EEC_TestUtil.mockLeadConfig('Family Child Care', null);
        Account accnt = EEC_TestUtil.mockProvider(EEC_TestUtil.MockCity());
        RecordType r = [select Id from RecordType where DeveloperName='FCC_Renewal' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
    	
    }
    
    static testMethod void testLTChangeOfHousehold() {
    	Account accnt = EEC_TestUtil.loadLicenseTransaction();
    	RecordType r = [select Id from RecordType where DeveloperName='FCC_Change_of_Household' and sobjecttype='Licensing_Transaction__c'];
        Licensing_Transaction__c lic = new Licensing_Transaction__c(RecordTypeId=r.Id,Status__c='Submitted', Provider__c=accnt.Id,Submitter__c=Userinfo.getUserId());
        insert lic;
        EEC_TestUtil.mockHouseHold(lic, accnt);
    	
    }*/
    
}