EEC_InitBackup/src/objects/Regulation__c.object
<CustomObject>
    <description>Regulations object stores the EEC regulations data that are used to populate visit checklists.  These data are managed in the EEC regulations system of record and are updated via a system integration whenever a regulation is updated.</description>
    <fields>
        <fullName>Applicable_To__c</fullName>
        <description>Type of provider this regulation applies to</description>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Family Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adoption Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary Shelter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unlicensed Provider</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Article__c</fullName>
        <description>Regulation article</description>
        <label>Article</label>
        <length>100000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Regulation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Higher level regulation in the hierarchy</description>
        <label>Parent Regulation</label>
        <referenceTo>Regulation__c</referenceTo>
        <relationshipLabel>Regulations</relationshipLabel>
        <relationshipName>Regulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Regulation</label>
    <nameField>
        <label>Regulation No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regulations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EEC_InitBackup/src/classes/EEC_RegulationViewController.cls
public with sharing class EEC_RegulationViewController {
    
    public List<Regulation__c> childregs{get;set;}
    public Regulation__c regulation {get;set;}
    public ID regId {get;set;}
    //public ID insId {get;set;}
    public EEC_RegulationViewController(){       
       regId = ApexPages.currentPage().getParameters().get('id');
       //insId = ApexPages.currentPage().getParameters().get('inId');
       if(String.isNotBlank(regId)){
             regulation = [select Id,Name,Parent_Regulation__r.Name,Applicable_To__c,article__c from Regulation__c where Id = :regId];
             if (regulation != null ) 
             	getchildregs();
       }
       
    }
    
    public void getchildregs(){
    
       childregs = [select id,Name,Article__c from Regulation__c where Parent_Regulation__c = :regId];
          
    
    }
}